// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTgUserID holds the string denoting the tg_user_id field in the database.
	FieldTgUserID = "tg_user_id"
	// FieldTgUsername holds the string denoting the tg_username field in the database.
	FieldTgUsername = "tg_username"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldWalletAddress holds the string denoting the wallet_address field in the database.
	FieldWalletAddress = "wallet_address"
	// FieldBalanceTai holds the string denoting the balance_tai field in the database.
	FieldBalanceTai = "balance_tai"
	// FieldBalanceUsdt holds the string denoting the balance_usdt field in the database.
	FieldBalanceUsdt = "balance_usdt"
	// FieldFrozenBalance holds the string denoting the frozen_balance field in the database.
	FieldFrozenBalance = "frozen_balance"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldReferralCode holds the string denoting the referral_code field in the database.
	FieldReferralCode = "referral_code"
	// FieldReferredBy holds the string denoting the referred_by field in the database.
	FieldReferredBy = "referred_by"
	// FieldInviteCount holds the string denoting the invite_count field in the database.
	FieldInviteCount = "invite_count"
	// FieldTotalEarned holds the string denoting the total_earned field in the database.
	FieldTotalEarned = "total_earned"
	// FieldGuildID holds the string denoting the guild_id field in the database.
	FieldGuildID = "guild_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePets holds the string denoting the pets edge name in mutations.
	EdgePets = "pets"
	// Table holds the table name of the user in the database.
	Table = "users"
	// PetsTable is the table that holds the pets relation/edge.
	PetsTable = "pets"
	// PetsInverseTable is the table name for the Pet entity.
	// It exists in this package in order to avoid circular dependency with the "pet" package.
	PetsInverseTable = "pets"
	// PetsColumn is the table column denoting the pets relation/edge.
	PetsColumn = "owner_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldTgUserID,
	FieldTgUsername,
	FieldFirstName,
	FieldWalletAddress,
	FieldBalanceTai,
	FieldBalanceUsdt,
	FieldFrozenBalance,
	FieldRole,
	FieldReferralCode,
	FieldReferredBy,
	FieldInviteCount,
	FieldTotalEarned,
	FieldGuildID,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TgUsernameValidator is a validator for the "tg_username" field. It is called by the builders before save.
	TgUsernameValidator func(string) error
	// FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	FirstNameValidator func(string) error
	// WalletAddressValidator is a validator for the "wallet_address" field. It is called by the builders before save.
	WalletAddressValidator func(string) error
	// DefaultBalanceTai holds the default value on creation for the "balance_tai" field.
	DefaultBalanceTai float64
	// DefaultBalanceUsdt holds the default value on creation for the "balance_usdt" field.
	DefaultBalanceUsdt float64
	// DefaultFrozenBalance holds the default value on creation for the "frozen_balance" field.
	DefaultFrozenBalance float64
	// DefaultRole holds the default value on creation for the "role" field.
	DefaultRole string
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// ReferralCodeValidator is a validator for the "referral_code" field. It is called by the builders before save.
	ReferralCodeValidator func(string) error
	// DefaultInviteCount holds the default value on creation for the "invite_count" field.
	DefaultInviteCount int
	// DefaultTotalEarned holds the default value on creation for the "total_earned" field.
	DefaultTotalEarned float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTgUserID orders the results by the tg_user_id field.
func ByTgUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTgUserID, opts...).ToFunc()
}

// ByTgUsername orders the results by the tg_username field.
func ByTgUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTgUsername, opts...).ToFunc()
}

// ByFirstName orders the results by the first_name field.
func ByFirstName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstName, opts...).ToFunc()
}

// ByWalletAddress orders the results by the wallet_address field.
func ByWalletAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWalletAddress, opts...).ToFunc()
}

// ByBalanceTai orders the results by the balance_tai field.
func ByBalanceTai(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceTai, opts...).ToFunc()
}

// ByBalanceUsdt orders the results by the balance_usdt field.
func ByBalanceUsdt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceUsdt, opts...).ToFunc()
}

// ByFrozenBalance orders the results by the frozen_balance field.
func ByFrozenBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrozenBalance, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByReferralCode orders the results by the referral_code field.
func ByReferralCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferralCode, opts...).ToFunc()
}

// ByReferredBy orders the results by the referred_by field.
func ByReferredBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferredBy, opts...).ToFunc()
}

// ByInviteCount orders the results by the invite_count field.
func ByInviteCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteCount, opts...).ToFunc()
}

// ByTotalEarned orders the results by the total_earned field.
func ByTotalEarned(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalEarned, opts...).ToFunc()
}

// ByGuildID orders the results by the guild_id field.
func ByGuildID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGuildID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPetsCount orders the results by pets count.
func ByPetsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPetsStep(), opts...)
	}
}

// ByPets orders the results by pets terms.
func ByPets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPetsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPetsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PetsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PetsTable, PetsColumn),
	)
}
