// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// TgUserID applies equality check predicate on the "tg_user_id" field. It's identical to TgUserIDEQ.
func TgUserID(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTgUserID, v))
}

// TgUsername applies equality check predicate on the "tg_username" field. It's identical to TgUsernameEQ.
func TgUsername(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTgUsername, v))
}

// FirstName applies equality check predicate on the "first_name" field. It's identical to FirstNameEQ.
func FirstName(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldFirstName, v))
}

// WalletAddress applies equality check predicate on the "wallet_address" field. It's identical to WalletAddressEQ.
func WalletAddress(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldWalletAddress, v))
}

// BalanceTai applies equality check predicate on the "balance_tai" field. It's identical to BalanceTaiEQ.
func BalanceTai(v float64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBalanceTai, v))
}

// BalanceUsdt applies equality check predicate on the "balance_usdt" field. It's identical to BalanceUsdtEQ.
func BalanceUsdt(v float64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBalanceUsdt, v))
}

// FrozenBalance applies equality check predicate on the "frozen_balance" field. It's identical to FrozenBalanceEQ.
func FrozenBalance(v float64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldFrozenBalance, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRole, v))
}

// ReferralCode applies equality check predicate on the "referral_code" field. It's identical to ReferralCodeEQ.
func ReferralCode(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldReferralCode, v))
}

// ReferredBy applies equality check predicate on the "referred_by" field. It's identical to ReferredByEQ.
func ReferredBy(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldReferredBy, v))
}

// InviteCount applies equality check predicate on the "invite_count" field. It's identical to InviteCountEQ.
func InviteCount(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldInviteCount, v))
}

// TotalEarned applies equality check predicate on the "total_earned" field. It's identical to TotalEarnedEQ.
func TotalEarned(v float64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTotalEarned, v))
}

// GuildID applies equality check predicate on the "guild_id" field. It's identical to GuildIDEQ.
func GuildID(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGuildID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// TgUserIDEQ applies the EQ predicate on the "tg_user_id" field.
func TgUserIDEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTgUserID, v))
}

// TgUserIDNEQ applies the NEQ predicate on the "tg_user_id" field.
func TgUserIDNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTgUserID, v))
}

// TgUserIDIn applies the In predicate on the "tg_user_id" field.
func TgUserIDIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldTgUserID, vs...))
}

// TgUserIDNotIn applies the NotIn predicate on the "tg_user_id" field.
func TgUserIDNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTgUserID, vs...))
}

// TgUserIDGT applies the GT predicate on the "tg_user_id" field.
func TgUserIDGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldTgUserID, v))
}

// TgUserIDGTE applies the GTE predicate on the "tg_user_id" field.
func TgUserIDGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTgUserID, v))
}

// TgUserIDLT applies the LT predicate on the "tg_user_id" field.
func TgUserIDLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldTgUserID, v))
}

// TgUserIDLTE applies the LTE predicate on the "tg_user_id" field.
func TgUserIDLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTgUserID, v))
}

// TgUsernameEQ applies the EQ predicate on the "tg_username" field.
func TgUsernameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTgUsername, v))
}

// TgUsernameNEQ applies the NEQ predicate on the "tg_username" field.
func TgUsernameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTgUsername, v))
}

// TgUsernameIn applies the In predicate on the "tg_username" field.
func TgUsernameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldTgUsername, vs...))
}

// TgUsernameNotIn applies the NotIn predicate on the "tg_username" field.
func TgUsernameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTgUsername, vs...))
}

// TgUsernameGT applies the GT predicate on the "tg_username" field.
func TgUsernameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldTgUsername, v))
}

// TgUsernameGTE applies the GTE predicate on the "tg_username" field.
func TgUsernameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTgUsername, v))
}

// TgUsernameLT applies the LT predicate on the "tg_username" field.
func TgUsernameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldTgUsername, v))
}

// TgUsernameLTE applies the LTE predicate on the "tg_username" field.
func TgUsernameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTgUsername, v))
}

// TgUsernameContains applies the Contains predicate on the "tg_username" field.
func TgUsernameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldTgUsername, v))
}

// TgUsernameHasPrefix applies the HasPrefix predicate on the "tg_username" field.
func TgUsernameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldTgUsername, v))
}

// TgUsernameHasSuffix applies the HasSuffix predicate on the "tg_username" field.
func TgUsernameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldTgUsername, v))
}

// TgUsernameIsNil applies the IsNil predicate on the "tg_username" field.
func TgUsernameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldTgUsername))
}

// TgUsernameNotNil applies the NotNil predicate on the "tg_username" field.
func TgUsernameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldTgUsername))
}

// TgUsernameEqualFold applies the EqualFold predicate on the "tg_username" field.
func TgUsernameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldTgUsername, v))
}

// TgUsernameContainsFold applies the ContainsFold predicate on the "tg_username" field.
func TgUsernameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldTgUsername, v))
}

// FirstNameEQ applies the EQ predicate on the "first_name" field.
func FirstNameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldFirstName, v))
}

// FirstNameNEQ applies the NEQ predicate on the "first_name" field.
func FirstNameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldFirstName, v))
}

// FirstNameIn applies the In predicate on the "first_name" field.
func FirstNameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldFirstName, vs...))
}

// FirstNameNotIn applies the NotIn predicate on the "first_name" field.
func FirstNameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldFirstName, vs...))
}

// FirstNameGT applies the GT predicate on the "first_name" field.
func FirstNameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldFirstName, v))
}

// FirstNameGTE applies the GTE predicate on the "first_name" field.
func FirstNameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldFirstName, v))
}

// FirstNameLT applies the LT predicate on the "first_name" field.
func FirstNameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldFirstName, v))
}

// FirstNameLTE applies the LTE predicate on the "first_name" field.
func FirstNameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldFirstName, v))
}

// FirstNameContains applies the Contains predicate on the "first_name" field.
func FirstNameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldFirstName, v))
}

// FirstNameHasPrefix applies the HasPrefix predicate on the "first_name" field.
func FirstNameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldFirstName, v))
}

// FirstNameHasSuffix applies the HasSuffix predicate on the "first_name" field.
func FirstNameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldFirstName, v))
}

// FirstNameIsNil applies the IsNil predicate on the "first_name" field.
func FirstNameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldFirstName))
}

// FirstNameNotNil applies the NotNil predicate on the "first_name" field.
func FirstNameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldFirstName))
}

// FirstNameEqualFold applies the EqualFold predicate on the "first_name" field.
func FirstNameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldFirstName, v))
}

// FirstNameContainsFold applies the ContainsFold predicate on the "first_name" field.
func FirstNameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldFirstName, v))
}

// WalletAddressEQ applies the EQ predicate on the "wallet_address" field.
func WalletAddressEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldWalletAddress, v))
}

// WalletAddressNEQ applies the NEQ predicate on the "wallet_address" field.
func WalletAddressNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldWalletAddress, v))
}

// WalletAddressIn applies the In predicate on the "wallet_address" field.
func WalletAddressIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldWalletAddress, vs...))
}

// WalletAddressNotIn applies the NotIn predicate on the "wallet_address" field.
func WalletAddressNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldWalletAddress, vs...))
}

// WalletAddressGT applies the GT predicate on the "wallet_address" field.
func WalletAddressGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldWalletAddress, v))
}

// WalletAddressGTE applies the GTE predicate on the "wallet_address" field.
func WalletAddressGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldWalletAddress, v))
}

// WalletAddressLT applies the LT predicate on the "wallet_address" field.
func WalletAddressLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldWalletAddress, v))
}

// WalletAddressLTE applies the LTE predicate on the "wallet_address" field.
func WalletAddressLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldWalletAddress, v))
}

// WalletAddressContains applies the Contains predicate on the "wallet_address" field.
func WalletAddressContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldWalletAddress, v))
}

// WalletAddressHasPrefix applies the HasPrefix predicate on the "wallet_address" field.
func WalletAddressHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldWalletAddress, v))
}

// WalletAddressHasSuffix applies the HasSuffix predicate on the "wallet_address" field.
func WalletAddressHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldWalletAddress, v))
}

// WalletAddressIsNil applies the IsNil predicate on the "wallet_address" field.
func WalletAddressIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldWalletAddress))
}

// WalletAddressNotNil applies the NotNil predicate on the "wallet_address" field.
func WalletAddressNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldWalletAddress))
}

// WalletAddressEqualFold applies the EqualFold predicate on the "wallet_address" field.
func WalletAddressEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldWalletAddress, v))
}

// WalletAddressContainsFold applies the ContainsFold predicate on the "wallet_address" field.
func WalletAddressContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldWalletAddress, v))
}

// BalanceTaiEQ applies the EQ predicate on the "balance_tai" field.
func BalanceTaiEQ(v float64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBalanceTai, v))
}

// BalanceTaiNEQ applies the NEQ predicate on the "balance_tai" field.
func BalanceTaiNEQ(v float64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldBalanceTai, v))
}

// BalanceTaiIn applies the In predicate on the "balance_tai" field.
func BalanceTaiIn(vs ...float64) predicate.User {
	return predicate.User(sql.FieldIn(FieldBalanceTai, vs...))
}

// BalanceTaiNotIn applies the NotIn predicate on the "balance_tai" field.
func BalanceTaiNotIn(vs ...float64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldBalanceTai, vs...))
}

// BalanceTaiGT applies the GT predicate on the "balance_tai" field.
func BalanceTaiGT(v float64) predicate.User {
	return predicate.User(sql.FieldGT(FieldBalanceTai, v))
}

// BalanceTaiGTE applies the GTE predicate on the "balance_tai" field.
func BalanceTaiGTE(v float64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldBalanceTai, v))
}

// BalanceTaiLT applies the LT predicate on the "balance_tai" field.
func BalanceTaiLT(v float64) predicate.User {
	return predicate.User(sql.FieldLT(FieldBalanceTai, v))
}

// BalanceTaiLTE applies the LTE predicate on the "balance_tai" field.
func BalanceTaiLTE(v float64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldBalanceTai, v))
}

// BalanceUsdtEQ applies the EQ predicate on the "balance_usdt" field.
func BalanceUsdtEQ(v float64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBalanceUsdt, v))
}

// BalanceUsdtNEQ applies the NEQ predicate on the "balance_usdt" field.
func BalanceUsdtNEQ(v float64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldBalanceUsdt, v))
}

// BalanceUsdtIn applies the In predicate on the "balance_usdt" field.
func BalanceUsdtIn(vs ...float64) predicate.User {
	return predicate.User(sql.FieldIn(FieldBalanceUsdt, vs...))
}

// BalanceUsdtNotIn applies the NotIn predicate on the "balance_usdt" field.
func BalanceUsdtNotIn(vs ...float64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldBalanceUsdt, vs...))
}

// BalanceUsdtGT applies the GT predicate on the "balance_usdt" field.
func BalanceUsdtGT(v float64) predicate.User {
	return predicate.User(sql.FieldGT(FieldBalanceUsdt, v))
}

// BalanceUsdtGTE applies the GTE predicate on the "balance_usdt" field.
func BalanceUsdtGTE(v float64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldBalanceUsdt, v))
}

// BalanceUsdtLT applies the LT predicate on the "balance_usdt" field.
func BalanceUsdtLT(v float64) predicate.User {
	return predicate.User(sql.FieldLT(FieldBalanceUsdt, v))
}

// BalanceUsdtLTE applies the LTE predicate on the "balance_usdt" field.
func BalanceUsdtLTE(v float64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldBalanceUsdt, v))
}

// FrozenBalanceEQ applies the EQ predicate on the "frozen_balance" field.
func FrozenBalanceEQ(v float64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldFrozenBalance, v))
}

// FrozenBalanceNEQ applies the NEQ predicate on the "frozen_balance" field.
func FrozenBalanceNEQ(v float64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldFrozenBalance, v))
}

// FrozenBalanceIn applies the In predicate on the "frozen_balance" field.
func FrozenBalanceIn(vs ...float64) predicate.User {
	return predicate.User(sql.FieldIn(FieldFrozenBalance, vs...))
}

// FrozenBalanceNotIn applies the NotIn predicate on the "frozen_balance" field.
func FrozenBalanceNotIn(vs ...float64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldFrozenBalance, vs...))
}

// FrozenBalanceGT applies the GT predicate on the "frozen_balance" field.
func FrozenBalanceGT(v float64) predicate.User {
	return predicate.User(sql.FieldGT(FieldFrozenBalance, v))
}

// FrozenBalanceGTE applies the GTE predicate on the "frozen_balance" field.
func FrozenBalanceGTE(v float64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldFrozenBalance, v))
}

// FrozenBalanceLT applies the LT predicate on the "frozen_balance" field.
func FrozenBalanceLT(v float64) predicate.User {
	return predicate.User(sql.FieldLT(FieldFrozenBalance, v))
}

// FrozenBalanceLTE applies the LTE predicate on the "frozen_balance" field.
func FrozenBalanceLTE(v float64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldFrozenBalance, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldRole, v))
}

// ReferralCodeEQ applies the EQ predicate on the "referral_code" field.
func ReferralCodeEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldReferralCode, v))
}

// ReferralCodeNEQ applies the NEQ predicate on the "referral_code" field.
func ReferralCodeNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldReferralCode, v))
}

// ReferralCodeIn applies the In predicate on the "referral_code" field.
func ReferralCodeIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldReferralCode, vs...))
}

// ReferralCodeNotIn applies the NotIn predicate on the "referral_code" field.
func ReferralCodeNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldReferralCode, vs...))
}

// ReferralCodeGT applies the GT predicate on the "referral_code" field.
func ReferralCodeGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldReferralCode, v))
}

// ReferralCodeGTE applies the GTE predicate on the "referral_code" field.
func ReferralCodeGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldReferralCode, v))
}

// ReferralCodeLT applies the LT predicate on the "referral_code" field.
func ReferralCodeLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldReferralCode, v))
}

// ReferralCodeLTE applies the LTE predicate on the "referral_code" field.
func ReferralCodeLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldReferralCode, v))
}

// ReferralCodeContains applies the Contains predicate on the "referral_code" field.
func ReferralCodeContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldReferralCode, v))
}

// ReferralCodeHasPrefix applies the HasPrefix predicate on the "referral_code" field.
func ReferralCodeHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldReferralCode, v))
}

// ReferralCodeHasSuffix applies the HasSuffix predicate on the "referral_code" field.
func ReferralCodeHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldReferralCode, v))
}

// ReferralCodeIsNil applies the IsNil predicate on the "referral_code" field.
func ReferralCodeIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldReferralCode))
}

// ReferralCodeNotNil applies the NotNil predicate on the "referral_code" field.
func ReferralCodeNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldReferralCode))
}

// ReferralCodeEqualFold applies the EqualFold predicate on the "referral_code" field.
func ReferralCodeEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldReferralCode, v))
}

// ReferralCodeContainsFold applies the ContainsFold predicate on the "referral_code" field.
func ReferralCodeContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldReferralCode, v))
}

// ReferredByEQ applies the EQ predicate on the "referred_by" field.
func ReferredByEQ(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldReferredBy, v))
}

// ReferredByNEQ applies the NEQ predicate on the "referred_by" field.
func ReferredByNEQ(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldReferredBy, v))
}

// ReferredByIn applies the In predicate on the "referred_by" field.
func ReferredByIn(vs ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldReferredBy, vs...))
}

// ReferredByNotIn applies the NotIn predicate on the "referred_by" field.
func ReferredByNotIn(vs ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldReferredBy, vs...))
}

// ReferredByGT applies the GT predicate on the "referred_by" field.
func ReferredByGT(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldReferredBy, v))
}

// ReferredByGTE applies the GTE predicate on the "referred_by" field.
func ReferredByGTE(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldReferredBy, v))
}

// ReferredByLT applies the LT predicate on the "referred_by" field.
func ReferredByLT(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldReferredBy, v))
}

// ReferredByLTE applies the LTE predicate on the "referred_by" field.
func ReferredByLTE(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldReferredBy, v))
}

// ReferredByIsNil applies the IsNil predicate on the "referred_by" field.
func ReferredByIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldReferredBy))
}

// ReferredByNotNil applies the NotNil predicate on the "referred_by" field.
func ReferredByNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldReferredBy))
}

// InviteCountEQ applies the EQ predicate on the "invite_count" field.
func InviteCountEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldInviteCount, v))
}

// InviteCountNEQ applies the NEQ predicate on the "invite_count" field.
func InviteCountNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldInviteCount, v))
}

// InviteCountIn applies the In predicate on the "invite_count" field.
func InviteCountIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldInviteCount, vs...))
}

// InviteCountNotIn applies the NotIn predicate on the "invite_count" field.
func InviteCountNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldInviteCount, vs...))
}

// InviteCountGT applies the GT predicate on the "invite_count" field.
func InviteCountGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldInviteCount, v))
}

// InviteCountGTE applies the GTE predicate on the "invite_count" field.
func InviteCountGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldInviteCount, v))
}

// InviteCountLT applies the LT predicate on the "invite_count" field.
func InviteCountLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldInviteCount, v))
}

// InviteCountLTE applies the LTE predicate on the "invite_count" field.
func InviteCountLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldInviteCount, v))
}

// TotalEarnedEQ applies the EQ predicate on the "total_earned" field.
func TotalEarnedEQ(v float64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTotalEarned, v))
}

// TotalEarnedNEQ applies the NEQ predicate on the "total_earned" field.
func TotalEarnedNEQ(v float64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTotalEarned, v))
}

// TotalEarnedIn applies the In predicate on the "total_earned" field.
func TotalEarnedIn(vs ...float64) predicate.User {
	return predicate.User(sql.FieldIn(FieldTotalEarned, vs...))
}

// TotalEarnedNotIn applies the NotIn predicate on the "total_earned" field.
func TotalEarnedNotIn(vs ...float64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTotalEarned, vs...))
}

// TotalEarnedGT applies the GT predicate on the "total_earned" field.
func TotalEarnedGT(v float64) predicate.User {
	return predicate.User(sql.FieldGT(FieldTotalEarned, v))
}

// TotalEarnedGTE applies the GTE predicate on the "total_earned" field.
func TotalEarnedGTE(v float64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTotalEarned, v))
}

// TotalEarnedLT applies the LT predicate on the "total_earned" field.
func TotalEarnedLT(v float64) predicate.User {
	return predicate.User(sql.FieldLT(FieldTotalEarned, v))
}

// TotalEarnedLTE applies the LTE predicate on the "total_earned" field.
func TotalEarnedLTE(v float64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTotalEarned, v))
}

// GuildIDEQ applies the EQ predicate on the "guild_id" field.
func GuildIDEQ(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGuildID, v))
}

// GuildIDNEQ applies the NEQ predicate on the "guild_id" field.
func GuildIDNEQ(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldGuildID, v))
}

// GuildIDIn applies the In predicate on the "guild_id" field.
func GuildIDIn(vs ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldGuildID, vs...))
}

// GuildIDNotIn applies the NotIn predicate on the "guild_id" field.
func GuildIDNotIn(vs ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldGuildID, vs...))
}

// GuildIDGT applies the GT predicate on the "guild_id" field.
func GuildIDGT(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldGuildID, v))
}

// GuildIDGTE applies the GTE predicate on the "guild_id" field.
func GuildIDGTE(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldGuildID, v))
}

// GuildIDLT applies the LT predicate on the "guild_id" field.
func GuildIDLT(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldGuildID, v))
}

// GuildIDLTE applies the LTE predicate on the "guild_id" field.
func GuildIDLTE(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldGuildID, v))
}

// GuildIDIsNil applies the IsNil predicate on the "guild_id" field.
func GuildIDIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldGuildID))
}

// GuildIDNotNil applies the NotNil predicate on the "guild_id" field.
func GuildIDNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldGuildID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPets applies the HasEdge predicate on the "pets" edge.
func HasPets() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PetsTable, PetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPetsWith applies the HasEdge predicate on the "pets" edge with a given conditions (other predicates).
func HasPetsWith(preds ...predicate.Pet) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newPetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
