// Code generated by ent, DO NOT EDIT.

package order

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUserID, v))
}

// ItemType applies equality check predicate on the "item_type" field. It's identical to ItemTypeEQ.
func ItemType(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldItemType, v))
}

// ItemID applies equality check predicate on the "item_id" field. It's identical to ItemIDEQ.
func ItemID(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldItemID, v))
}

// Side applies equality check predicate on the "side" field. It's identical to SideEQ.
func Side(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldSide, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPrice, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCurrency, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldStatus, v))
}

// FilledAt applies equality check predicate on the "filled_at" field. It's identical to FilledAtEQ.
func FilledAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldFilledAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldUserID, v))
}

// ItemTypeEQ applies the EQ predicate on the "item_type" field.
func ItemTypeEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldItemType, v))
}

// ItemTypeNEQ applies the NEQ predicate on the "item_type" field.
func ItemTypeNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldItemType, v))
}

// ItemTypeIn applies the In predicate on the "item_type" field.
func ItemTypeIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldItemType, vs...))
}

// ItemTypeNotIn applies the NotIn predicate on the "item_type" field.
func ItemTypeNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldItemType, vs...))
}

// ItemTypeGT applies the GT predicate on the "item_type" field.
func ItemTypeGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldItemType, v))
}

// ItemTypeGTE applies the GTE predicate on the "item_type" field.
func ItemTypeGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldItemType, v))
}

// ItemTypeLT applies the LT predicate on the "item_type" field.
func ItemTypeLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldItemType, v))
}

// ItemTypeLTE applies the LTE predicate on the "item_type" field.
func ItemTypeLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldItemType, v))
}

// ItemTypeContains applies the Contains predicate on the "item_type" field.
func ItemTypeContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldItemType, v))
}

// ItemTypeHasPrefix applies the HasPrefix predicate on the "item_type" field.
func ItemTypeHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldItemType, v))
}

// ItemTypeHasSuffix applies the HasSuffix predicate on the "item_type" field.
func ItemTypeHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldItemType, v))
}

// ItemTypeEqualFold applies the EqualFold predicate on the "item_type" field.
func ItemTypeEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldItemType, v))
}

// ItemTypeContainsFold applies the ContainsFold predicate on the "item_type" field.
func ItemTypeContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldItemType, v))
}

// ItemIDEQ applies the EQ predicate on the "item_id" field.
func ItemIDEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldItemID, v))
}

// ItemIDNEQ applies the NEQ predicate on the "item_id" field.
func ItemIDNEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldItemID, v))
}

// ItemIDIn applies the In predicate on the "item_id" field.
func ItemIDIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldItemID, vs...))
}

// ItemIDNotIn applies the NotIn predicate on the "item_id" field.
func ItemIDNotIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldItemID, vs...))
}

// ItemIDGT applies the GT predicate on the "item_id" field.
func ItemIDGT(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldItemID, v))
}

// ItemIDGTE applies the GTE predicate on the "item_id" field.
func ItemIDGTE(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldItemID, v))
}

// ItemIDLT applies the LT predicate on the "item_id" field.
func ItemIDLT(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldItemID, v))
}

// ItemIDLTE applies the LTE predicate on the "item_id" field.
func ItemIDLTE(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldItemID, v))
}

// SideEQ applies the EQ predicate on the "side" field.
func SideEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldSide, v))
}

// SideNEQ applies the NEQ predicate on the "side" field.
func SideNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldSide, v))
}

// SideIn applies the In predicate on the "side" field.
func SideIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldSide, vs...))
}

// SideNotIn applies the NotIn predicate on the "side" field.
func SideNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldSide, vs...))
}

// SideGT applies the GT predicate on the "side" field.
func SideGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldSide, v))
}

// SideGTE applies the GTE predicate on the "side" field.
func SideGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldSide, v))
}

// SideLT applies the LT predicate on the "side" field.
func SideLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldSide, v))
}

// SideLTE applies the LTE predicate on the "side" field.
func SideLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldSide, v))
}

// SideContains applies the Contains predicate on the "side" field.
func SideContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldSide, v))
}

// SideHasPrefix applies the HasPrefix predicate on the "side" field.
func SideHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldSide, v))
}

// SideHasSuffix applies the HasSuffix predicate on the "side" field.
func SideHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldSide, v))
}

// SideEqualFold applies the EqualFold predicate on the "side" field.
func SideEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldSide, v))
}

// SideContainsFold applies the ContainsFold predicate on the "side" field.
func SideContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldSide, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldPrice, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldCurrency, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldStatus, v))
}

// FilledAtEQ applies the EQ predicate on the "filled_at" field.
func FilledAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldFilledAt, v))
}

// FilledAtNEQ applies the NEQ predicate on the "filled_at" field.
func FilledAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldFilledAt, v))
}

// FilledAtIn applies the In predicate on the "filled_at" field.
func FilledAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldFilledAt, vs...))
}

// FilledAtNotIn applies the NotIn predicate on the "filled_at" field.
func FilledAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldFilledAt, vs...))
}

// FilledAtGT applies the GT predicate on the "filled_at" field.
func FilledAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldFilledAt, v))
}

// FilledAtGTE applies the GTE predicate on the "filled_at" field.
func FilledAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldFilledAt, v))
}

// FilledAtLT applies the LT predicate on the "filled_at" field.
func FilledAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldFilledAt, v))
}

// FilledAtLTE applies the LTE predicate on the "filled_at" field.
func FilledAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldFilledAt, v))
}

// FilledAtIsNil applies the IsNil predicate on the "filled_at" field.
func FilledAtIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldFilledAt))
}

// FilledAtNotNil applies the NotNil predicate on the "filled_at" field.
func FilledAtNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldFilledAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldExpiresAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Order) predicate.Order {
	return predicate.Order(sql.NotPredicates(p))
}
