// Code generated by ent, DO NOT EDIT.

package trade

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldLTE(FieldID, id))
}

// ItemType applies equality check predicate on the "item_type" field. It's identical to ItemTypeEQ.
func ItemType(v string) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldItemType, v))
}

// ItemID applies equality check predicate on the "item_id" field. It's identical to ItemIDEQ.
func ItemID(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldItemID, v))
}

// SellerID applies equality check predicate on the "seller_id" field. It's identical to SellerIDEQ.
func SellerID(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldSellerID, v))
}

// BuyerID applies equality check predicate on the "buyer_id" field. It's identical to BuyerIDEQ.
func BuyerID(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldBuyerID, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldPrice, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldCurrency, v))
}

// FeeAmount applies equality check predicate on the "fee_amount" field. It's identical to FeeAmountEQ.
func FeeAmount(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldFeeAmount, v))
}

// FeeRate applies equality check predicate on the "fee_rate" field. It's identical to FeeRateEQ.
func FeeRate(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldFeeRate, v))
}

// IsMarketMaker applies equality check predicate on the "is_market_maker" field. It's identical to IsMarketMakerEQ.
func IsMarketMaker(v bool) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldIsMarketMaker, v))
}

// ChainTxHash applies equality check predicate on the "chain_tx_hash" field. It's identical to ChainTxHashEQ.
func ChainTxHash(v string) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldChainTxHash, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldCreatedAt, v))
}

// ItemTypeEQ applies the EQ predicate on the "item_type" field.
func ItemTypeEQ(v string) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldItemType, v))
}

// ItemTypeNEQ applies the NEQ predicate on the "item_type" field.
func ItemTypeNEQ(v string) predicate.Trade {
	return predicate.Trade(sql.FieldNEQ(FieldItemType, v))
}

// ItemTypeIn applies the In predicate on the "item_type" field.
func ItemTypeIn(vs ...string) predicate.Trade {
	return predicate.Trade(sql.FieldIn(FieldItemType, vs...))
}

// ItemTypeNotIn applies the NotIn predicate on the "item_type" field.
func ItemTypeNotIn(vs ...string) predicate.Trade {
	return predicate.Trade(sql.FieldNotIn(FieldItemType, vs...))
}

// ItemTypeGT applies the GT predicate on the "item_type" field.
func ItemTypeGT(v string) predicate.Trade {
	return predicate.Trade(sql.FieldGT(FieldItemType, v))
}

// ItemTypeGTE applies the GTE predicate on the "item_type" field.
func ItemTypeGTE(v string) predicate.Trade {
	return predicate.Trade(sql.FieldGTE(FieldItemType, v))
}

// ItemTypeLT applies the LT predicate on the "item_type" field.
func ItemTypeLT(v string) predicate.Trade {
	return predicate.Trade(sql.FieldLT(FieldItemType, v))
}

// ItemTypeLTE applies the LTE predicate on the "item_type" field.
func ItemTypeLTE(v string) predicate.Trade {
	return predicate.Trade(sql.FieldLTE(FieldItemType, v))
}

// ItemTypeContains applies the Contains predicate on the "item_type" field.
func ItemTypeContains(v string) predicate.Trade {
	return predicate.Trade(sql.FieldContains(FieldItemType, v))
}

// ItemTypeHasPrefix applies the HasPrefix predicate on the "item_type" field.
func ItemTypeHasPrefix(v string) predicate.Trade {
	return predicate.Trade(sql.FieldHasPrefix(FieldItemType, v))
}

// ItemTypeHasSuffix applies the HasSuffix predicate on the "item_type" field.
func ItemTypeHasSuffix(v string) predicate.Trade {
	return predicate.Trade(sql.FieldHasSuffix(FieldItemType, v))
}

// ItemTypeEqualFold applies the EqualFold predicate on the "item_type" field.
func ItemTypeEqualFold(v string) predicate.Trade {
	return predicate.Trade(sql.FieldEqualFold(FieldItemType, v))
}

// ItemTypeContainsFold applies the ContainsFold predicate on the "item_type" field.
func ItemTypeContainsFold(v string) predicate.Trade {
	return predicate.Trade(sql.FieldContainsFold(FieldItemType, v))
}

// ItemIDEQ applies the EQ predicate on the "item_id" field.
func ItemIDEQ(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldItemID, v))
}

// ItemIDNEQ applies the NEQ predicate on the "item_id" field.
func ItemIDNEQ(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldNEQ(FieldItemID, v))
}

// ItemIDIn applies the In predicate on the "item_id" field.
func ItemIDIn(vs ...uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldIn(FieldItemID, vs...))
}

// ItemIDNotIn applies the NotIn predicate on the "item_id" field.
func ItemIDNotIn(vs ...uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldNotIn(FieldItemID, vs...))
}

// ItemIDGT applies the GT predicate on the "item_id" field.
func ItemIDGT(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldGT(FieldItemID, v))
}

// ItemIDGTE applies the GTE predicate on the "item_id" field.
func ItemIDGTE(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldGTE(FieldItemID, v))
}

// ItemIDLT applies the LT predicate on the "item_id" field.
func ItemIDLT(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldLT(FieldItemID, v))
}

// ItemIDLTE applies the LTE predicate on the "item_id" field.
func ItemIDLTE(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldLTE(FieldItemID, v))
}

// SellerIDEQ applies the EQ predicate on the "seller_id" field.
func SellerIDEQ(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldSellerID, v))
}

// SellerIDNEQ applies the NEQ predicate on the "seller_id" field.
func SellerIDNEQ(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldNEQ(FieldSellerID, v))
}

// SellerIDIn applies the In predicate on the "seller_id" field.
func SellerIDIn(vs ...uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldIn(FieldSellerID, vs...))
}

// SellerIDNotIn applies the NotIn predicate on the "seller_id" field.
func SellerIDNotIn(vs ...uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldNotIn(FieldSellerID, vs...))
}

// SellerIDGT applies the GT predicate on the "seller_id" field.
func SellerIDGT(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldGT(FieldSellerID, v))
}

// SellerIDGTE applies the GTE predicate on the "seller_id" field.
func SellerIDGTE(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldGTE(FieldSellerID, v))
}

// SellerIDLT applies the LT predicate on the "seller_id" field.
func SellerIDLT(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldLT(FieldSellerID, v))
}

// SellerIDLTE applies the LTE predicate on the "seller_id" field.
func SellerIDLTE(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldLTE(FieldSellerID, v))
}

// BuyerIDEQ applies the EQ predicate on the "buyer_id" field.
func BuyerIDEQ(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldBuyerID, v))
}

// BuyerIDNEQ applies the NEQ predicate on the "buyer_id" field.
func BuyerIDNEQ(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldNEQ(FieldBuyerID, v))
}

// BuyerIDIn applies the In predicate on the "buyer_id" field.
func BuyerIDIn(vs ...uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldIn(FieldBuyerID, vs...))
}

// BuyerIDNotIn applies the NotIn predicate on the "buyer_id" field.
func BuyerIDNotIn(vs ...uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldNotIn(FieldBuyerID, vs...))
}

// BuyerIDGT applies the GT predicate on the "buyer_id" field.
func BuyerIDGT(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldGT(FieldBuyerID, v))
}

// BuyerIDGTE applies the GTE predicate on the "buyer_id" field.
func BuyerIDGTE(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldGTE(FieldBuyerID, v))
}

// BuyerIDLT applies the LT predicate on the "buyer_id" field.
func BuyerIDLT(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldLT(FieldBuyerID, v))
}

// BuyerIDLTE applies the LTE predicate on the "buyer_id" field.
func BuyerIDLTE(v uuid.UUID) predicate.Trade {
	return predicate.Trade(sql.FieldLTE(FieldBuyerID, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.Trade {
	return predicate.Trade(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.Trade {
	return predicate.Trade(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldLTE(FieldPrice, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Trade {
	return predicate.Trade(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Trade {
	return predicate.Trade(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Trade {
	return predicate.Trade(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Trade {
	return predicate.Trade(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Trade {
	return predicate.Trade(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Trade {
	return predicate.Trade(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Trade {
	return predicate.Trade(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Trade {
	return predicate.Trade(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Trade {
	return predicate.Trade(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Trade {
	return predicate.Trade(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Trade {
	return predicate.Trade(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Trade {
	return predicate.Trade(sql.FieldContainsFold(FieldCurrency, v))
}

// FeeAmountEQ applies the EQ predicate on the "fee_amount" field.
func FeeAmountEQ(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldFeeAmount, v))
}

// FeeAmountNEQ applies the NEQ predicate on the "fee_amount" field.
func FeeAmountNEQ(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldNEQ(FieldFeeAmount, v))
}

// FeeAmountIn applies the In predicate on the "fee_amount" field.
func FeeAmountIn(vs ...float64) predicate.Trade {
	return predicate.Trade(sql.FieldIn(FieldFeeAmount, vs...))
}

// FeeAmountNotIn applies the NotIn predicate on the "fee_amount" field.
func FeeAmountNotIn(vs ...float64) predicate.Trade {
	return predicate.Trade(sql.FieldNotIn(FieldFeeAmount, vs...))
}

// FeeAmountGT applies the GT predicate on the "fee_amount" field.
func FeeAmountGT(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldGT(FieldFeeAmount, v))
}

// FeeAmountGTE applies the GTE predicate on the "fee_amount" field.
func FeeAmountGTE(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldGTE(FieldFeeAmount, v))
}

// FeeAmountLT applies the LT predicate on the "fee_amount" field.
func FeeAmountLT(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldLT(FieldFeeAmount, v))
}

// FeeAmountLTE applies the LTE predicate on the "fee_amount" field.
func FeeAmountLTE(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldLTE(FieldFeeAmount, v))
}

// FeeRateEQ applies the EQ predicate on the "fee_rate" field.
func FeeRateEQ(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldFeeRate, v))
}

// FeeRateNEQ applies the NEQ predicate on the "fee_rate" field.
func FeeRateNEQ(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldNEQ(FieldFeeRate, v))
}

// FeeRateIn applies the In predicate on the "fee_rate" field.
func FeeRateIn(vs ...float64) predicate.Trade {
	return predicate.Trade(sql.FieldIn(FieldFeeRate, vs...))
}

// FeeRateNotIn applies the NotIn predicate on the "fee_rate" field.
func FeeRateNotIn(vs ...float64) predicate.Trade {
	return predicate.Trade(sql.FieldNotIn(FieldFeeRate, vs...))
}

// FeeRateGT applies the GT predicate on the "fee_rate" field.
func FeeRateGT(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldGT(FieldFeeRate, v))
}

// FeeRateGTE applies the GTE predicate on the "fee_rate" field.
func FeeRateGTE(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldGTE(FieldFeeRate, v))
}

// FeeRateLT applies the LT predicate on the "fee_rate" field.
func FeeRateLT(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldLT(FieldFeeRate, v))
}

// FeeRateLTE applies the LTE predicate on the "fee_rate" field.
func FeeRateLTE(v float64) predicate.Trade {
	return predicate.Trade(sql.FieldLTE(FieldFeeRate, v))
}

// IsMarketMakerEQ applies the EQ predicate on the "is_market_maker" field.
func IsMarketMakerEQ(v bool) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldIsMarketMaker, v))
}

// IsMarketMakerNEQ applies the NEQ predicate on the "is_market_maker" field.
func IsMarketMakerNEQ(v bool) predicate.Trade {
	return predicate.Trade(sql.FieldNEQ(FieldIsMarketMaker, v))
}

// ChainTxHashEQ applies the EQ predicate on the "chain_tx_hash" field.
func ChainTxHashEQ(v string) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldChainTxHash, v))
}

// ChainTxHashNEQ applies the NEQ predicate on the "chain_tx_hash" field.
func ChainTxHashNEQ(v string) predicate.Trade {
	return predicate.Trade(sql.FieldNEQ(FieldChainTxHash, v))
}

// ChainTxHashIn applies the In predicate on the "chain_tx_hash" field.
func ChainTxHashIn(vs ...string) predicate.Trade {
	return predicate.Trade(sql.FieldIn(FieldChainTxHash, vs...))
}

// ChainTxHashNotIn applies the NotIn predicate on the "chain_tx_hash" field.
func ChainTxHashNotIn(vs ...string) predicate.Trade {
	return predicate.Trade(sql.FieldNotIn(FieldChainTxHash, vs...))
}

// ChainTxHashGT applies the GT predicate on the "chain_tx_hash" field.
func ChainTxHashGT(v string) predicate.Trade {
	return predicate.Trade(sql.FieldGT(FieldChainTxHash, v))
}

// ChainTxHashGTE applies the GTE predicate on the "chain_tx_hash" field.
func ChainTxHashGTE(v string) predicate.Trade {
	return predicate.Trade(sql.FieldGTE(FieldChainTxHash, v))
}

// ChainTxHashLT applies the LT predicate on the "chain_tx_hash" field.
func ChainTxHashLT(v string) predicate.Trade {
	return predicate.Trade(sql.FieldLT(FieldChainTxHash, v))
}

// ChainTxHashLTE applies the LTE predicate on the "chain_tx_hash" field.
func ChainTxHashLTE(v string) predicate.Trade {
	return predicate.Trade(sql.FieldLTE(FieldChainTxHash, v))
}

// ChainTxHashContains applies the Contains predicate on the "chain_tx_hash" field.
func ChainTxHashContains(v string) predicate.Trade {
	return predicate.Trade(sql.FieldContains(FieldChainTxHash, v))
}

// ChainTxHashHasPrefix applies the HasPrefix predicate on the "chain_tx_hash" field.
func ChainTxHashHasPrefix(v string) predicate.Trade {
	return predicate.Trade(sql.FieldHasPrefix(FieldChainTxHash, v))
}

// ChainTxHashHasSuffix applies the HasSuffix predicate on the "chain_tx_hash" field.
func ChainTxHashHasSuffix(v string) predicate.Trade {
	return predicate.Trade(sql.FieldHasSuffix(FieldChainTxHash, v))
}

// ChainTxHashIsNil applies the IsNil predicate on the "chain_tx_hash" field.
func ChainTxHashIsNil() predicate.Trade {
	return predicate.Trade(sql.FieldIsNull(FieldChainTxHash))
}

// ChainTxHashNotNil applies the NotNil predicate on the "chain_tx_hash" field.
func ChainTxHashNotNil() predicate.Trade {
	return predicate.Trade(sql.FieldNotNull(FieldChainTxHash))
}

// ChainTxHashEqualFold applies the EqualFold predicate on the "chain_tx_hash" field.
func ChainTxHashEqualFold(v string) predicate.Trade {
	return predicate.Trade(sql.FieldEqualFold(FieldChainTxHash, v))
}

// ChainTxHashContainsFold applies the ContainsFold predicate on the "chain_tx_hash" field.
func ChainTxHashContainsFold(v string) predicate.Trade {
	return predicate.Trade(sql.FieldContainsFold(FieldChainTxHash, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Trade {
	return predicate.Trade(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Trade {
	return predicate.Trade(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Trade {
	return predicate.Trade(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Trade {
	return predicate.Trade(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Trade {
	return predicate.Trade(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Trade {
	return predicate.Trade(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Trade {
	return predicate.Trade(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Trade {
	return predicate.Trade(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Trade) predicate.Trade {
	return predicate.Trade(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Trade) predicate.Trade {
	return predicate.Trade(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Trade) predicate.Trade {
	return predicate.Trade(sql.NotPredicates(p))
}
