// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tii-mom/tai-protocol/backend/ent/bounty"
	"github.com/tii-mom/tai-protocol/backend/ent/predicate"
)

// BountyUpdate is the builder for updating Bounty entities.
type BountyUpdate struct {
	config
	hooks    []Hook
	mutation *BountyMutation
}

// Where appends a list predicates to the BountyUpdate builder.
func (_u *BountyUpdate) Where(ps ...predicate.Bounty) *BountyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *BountyUpdate) SetTitle(v string) *BountyUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BountyUpdate) SetNillableTitle(v *string) *BountyUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BountyUpdate) SetDescription(v string) *BountyUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BountyUpdate) SetNillableDescription(v *string) *BountyUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *BountyUpdate) ClearDescription() *BountyUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPublisherID sets the "publisher_id" field.
func (_u *BountyUpdate) SetPublisherID(v string) *BountyUpdate {
	_u.mutation.SetPublisherID(v)
	return _u
}

// SetNillablePublisherID sets the "publisher_id" field if the given value is not nil.
func (_u *BountyUpdate) SetNillablePublisherID(v *string) *BountyUpdate {
	if v != nil {
		_u.SetPublisherID(*v)
	}
	return _u
}

// SetDifficulty sets the "difficulty" field.
func (_u *BountyUpdate) SetDifficulty(v bounty.Difficulty) *BountyUpdate {
	_u.mutation.SetDifficulty(v)
	return _u
}

// SetNillableDifficulty sets the "difficulty" field if the given value is not nil.
func (_u *BountyUpdate) SetNillableDifficulty(v *bounty.Difficulty) *BountyUpdate {
	if v != nil {
		_u.SetDifficulty(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BountyUpdate) SetStatus(v bounty.Status) *BountyUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BountyUpdate) SetNillableStatus(v *bounty.Status) *BountyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAcceptorPetID sets the "acceptor_pet_id" field.
func (_u *BountyUpdate) SetAcceptorPetID(v string) *BountyUpdate {
	_u.mutation.SetAcceptorPetID(v)
	return _u
}

// SetNillableAcceptorPetID sets the "acceptor_pet_id" field if the given value is not nil.
func (_u *BountyUpdate) SetNillableAcceptorPetID(v *string) *BountyUpdate {
	if v != nil {
		_u.SetAcceptorPetID(*v)
	}
	return _u
}

// ClearAcceptorPetID clears the value of the "acceptor_pet_id" field.
func (_u *BountyUpdate) ClearAcceptorPetID() *BountyUpdate {
	_u.mutation.ClearAcceptorPetID()
	return _u
}

// SetRewardTai sets the "reward_tai" field.
func (_u *BountyUpdate) SetRewardTai(v float64) *BountyUpdate {
	_u.mutation.ResetRewardTai()
	_u.mutation.SetRewardTai(v)
	return _u
}

// SetNillableRewardTai sets the "reward_tai" field if the given value is not nil.
func (_u *BountyUpdate) SetNillableRewardTai(v *float64) *BountyUpdate {
	if v != nil {
		_u.SetRewardTai(*v)
	}
	return _u
}

// AddRewardTai adds value to the "reward_tai" field.
func (_u *BountyUpdate) AddRewardTai(v float64) *BountyUpdate {
	_u.mutation.AddRewardTai(v)
	return _u
}

// SetSubmission sets the "submission" field.
func (_u *BountyUpdate) SetSubmission(v string) *BountyUpdate {
	_u.mutation.SetSubmission(v)
	return _u
}

// SetNillableSubmission sets the "submission" field if the given value is not nil.
func (_u *BountyUpdate) SetNillableSubmission(v *string) *BountyUpdate {
	if v != nil {
		_u.SetSubmission(*v)
	}
	return _u
}

// ClearSubmission clears the value of the "submission" field.
func (_u *BountyUpdate) ClearSubmission() *BountyUpdate {
	_u.mutation.ClearSubmission()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BountyUpdate) SetCreatedAt(v time.Time) *BountyUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BountyUpdate) SetNillableCreatedAt(v *time.Time) *BountyUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *BountyUpdate) SetExpiresAt(v time.Time) *BountyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *BountyUpdate) SetNillableExpiresAt(v *time.Time) *BountyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *BountyUpdate) ClearExpiresAt() *BountyUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *BountyUpdate) SetCompletedAt(v time.Time) *BountyUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *BountyUpdate) SetNillableCompletedAt(v *time.Time) *BountyUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *BountyUpdate) ClearCompletedAt() *BountyUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the BountyMutation object of the builder.
func (_u *BountyUpdate) Mutation() *BountyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BountyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BountyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BountyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BountyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BountyUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := bounty.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Bounty.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublisherID(); ok {
		if err := bounty.PublisherIDValidator(v); err != nil {
			return &ValidationError{Name: "publisher_id", err: fmt.Errorf(`ent: validator failed for field "Bounty.publisher_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Difficulty(); ok {
		if err := bounty.DifficultyValidator(v); err != nil {
			return &ValidationError{Name: "difficulty", err: fmt.Errorf(`ent: validator failed for field "Bounty.difficulty": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := bounty.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Bounty.status": %w`, err)}
		}
	}
	return nil
}

func (_u *BountyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bounty.Table, bounty.Columns, sqlgraph.NewFieldSpec(bounty.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(bounty.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(bounty.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(bounty.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PublisherID(); ok {
		_spec.SetField(bounty.FieldPublisherID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Difficulty(); ok {
		_spec.SetField(bounty.FieldDifficulty, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(bounty.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AcceptorPetID(); ok {
		_spec.SetField(bounty.FieldAcceptorPetID, field.TypeString, value)
	}
	if _u.mutation.AcceptorPetIDCleared() {
		_spec.ClearField(bounty.FieldAcceptorPetID, field.TypeString)
	}
	if value, ok := _u.mutation.RewardTai(); ok {
		_spec.SetField(bounty.FieldRewardTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardTai(); ok {
		_spec.AddField(bounty.FieldRewardTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Submission(); ok {
		_spec.SetField(bounty.FieldSubmission, field.TypeString, value)
	}
	if _u.mutation.SubmissionCleared() {
		_spec.ClearField(bounty.FieldSubmission, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(bounty.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(bounty.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(bounty.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(bounty.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(bounty.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bounty.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BountyUpdateOne is the builder for updating a single Bounty entity.
type BountyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BountyMutation
}

// SetTitle sets the "title" field.
func (_u *BountyUpdateOne) SetTitle(v string) *BountyUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BountyUpdateOne) SetNillableTitle(v *string) *BountyUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BountyUpdateOne) SetDescription(v string) *BountyUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BountyUpdateOne) SetNillableDescription(v *string) *BountyUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *BountyUpdateOne) ClearDescription() *BountyUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPublisherID sets the "publisher_id" field.
func (_u *BountyUpdateOne) SetPublisherID(v string) *BountyUpdateOne {
	_u.mutation.SetPublisherID(v)
	return _u
}

// SetNillablePublisherID sets the "publisher_id" field if the given value is not nil.
func (_u *BountyUpdateOne) SetNillablePublisherID(v *string) *BountyUpdateOne {
	if v != nil {
		_u.SetPublisherID(*v)
	}
	return _u
}

// SetDifficulty sets the "difficulty" field.
func (_u *BountyUpdateOne) SetDifficulty(v bounty.Difficulty) *BountyUpdateOne {
	_u.mutation.SetDifficulty(v)
	return _u
}

// SetNillableDifficulty sets the "difficulty" field if the given value is not nil.
func (_u *BountyUpdateOne) SetNillableDifficulty(v *bounty.Difficulty) *BountyUpdateOne {
	if v != nil {
		_u.SetDifficulty(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BountyUpdateOne) SetStatus(v bounty.Status) *BountyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BountyUpdateOne) SetNillableStatus(v *bounty.Status) *BountyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAcceptorPetID sets the "acceptor_pet_id" field.
func (_u *BountyUpdateOne) SetAcceptorPetID(v string) *BountyUpdateOne {
	_u.mutation.SetAcceptorPetID(v)
	return _u
}

// SetNillableAcceptorPetID sets the "acceptor_pet_id" field if the given value is not nil.
func (_u *BountyUpdateOne) SetNillableAcceptorPetID(v *string) *BountyUpdateOne {
	if v != nil {
		_u.SetAcceptorPetID(*v)
	}
	return _u
}

// ClearAcceptorPetID clears the value of the "acceptor_pet_id" field.
func (_u *BountyUpdateOne) ClearAcceptorPetID() *BountyUpdateOne {
	_u.mutation.ClearAcceptorPetID()
	return _u
}

// SetRewardTai sets the "reward_tai" field.
func (_u *BountyUpdateOne) SetRewardTai(v float64) *BountyUpdateOne {
	_u.mutation.ResetRewardTai()
	_u.mutation.SetRewardTai(v)
	return _u
}

// SetNillableRewardTai sets the "reward_tai" field if the given value is not nil.
func (_u *BountyUpdateOne) SetNillableRewardTai(v *float64) *BountyUpdateOne {
	if v != nil {
		_u.SetRewardTai(*v)
	}
	return _u
}

// AddRewardTai adds value to the "reward_tai" field.
func (_u *BountyUpdateOne) AddRewardTai(v float64) *BountyUpdateOne {
	_u.mutation.AddRewardTai(v)
	return _u
}

// SetSubmission sets the "submission" field.
func (_u *BountyUpdateOne) SetSubmission(v string) *BountyUpdateOne {
	_u.mutation.SetSubmission(v)
	return _u
}

// SetNillableSubmission sets the "submission" field if the given value is not nil.
func (_u *BountyUpdateOne) SetNillableSubmission(v *string) *BountyUpdateOne {
	if v != nil {
		_u.SetSubmission(*v)
	}
	return _u
}

// ClearSubmission clears the value of the "submission" field.
func (_u *BountyUpdateOne) ClearSubmission() *BountyUpdateOne {
	_u.mutation.ClearSubmission()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BountyUpdateOne) SetCreatedAt(v time.Time) *BountyUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BountyUpdateOne) SetNillableCreatedAt(v *time.Time) *BountyUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *BountyUpdateOne) SetExpiresAt(v time.Time) *BountyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *BountyUpdateOne) SetNillableExpiresAt(v *time.Time) *BountyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *BountyUpdateOne) ClearExpiresAt() *BountyUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *BountyUpdateOne) SetCompletedAt(v time.Time) *BountyUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *BountyUpdateOne) SetNillableCompletedAt(v *time.Time) *BountyUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *BountyUpdateOne) ClearCompletedAt() *BountyUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the BountyMutation object of the builder.
func (_u *BountyUpdateOne) Mutation() *BountyMutation {
	return _u.mutation
}

// Where appends a list predicates to the BountyUpdate builder.
func (_u *BountyUpdateOne) Where(ps ...predicate.Bounty) *BountyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BountyUpdateOne) Select(field string, fields ...string) *BountyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Bounty entity.
func (_u *BountyUpdateOne) Save(ctx context.Context) (*Bounty, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BountyUpdateOne) SaveX(ctx context.Context) *Bounty {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BountyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BountyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BountyUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := bounty.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Bounty.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublisherID(); ok {
		if err := bounty.PublisherIDValidator(v); err != nil {
			return &ValidationError{Name: "publisher_id", err: fmt.Errorf(`ent: validator failed for field "Bounty.publisher_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Difficulty(); ok {
		if err := bounty.DifficultyValidator(v); err != nil {
			return &ValidationError{Name: "difficulty", err: fmt.Errorf(`ent: validator failed for field "Bounty.difficulty": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := bounty.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Bounty.status": %w`, err)}
		}
	}
	return nil
}

func (_u *BountyUpdateOne) sqlSave(ctx context.Context) (_node *Bounty, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bounty.Table, bounty.Columns, sqlgraph.NewFieldSpec(bounty.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Bounty.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bounty.FieldID)
		for _, f := range fields {
			if !bounty.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bounty.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(bounty.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(bounty.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(bounty.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PublisherID(); ok {
		_spec.SetField(bounty.FieldPublisherID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Difficulty(); ok {
		_spec.SetField(bounty.FieldDifficulty, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(bounty.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AcceptorPetID(); ok {
		_spec.SetField(bounty.FieldAcceptorPetID, field.TypeString, value)
	}
	if _u.mutation.AcceptorPetIDCleared() {
		_spec.ClearField(bounty.FieldAcceptorPetID, field.TypeString)
	}
	if value, ok := _u.mutation.RewardTai(); ok {
		_spec.SetField(bounty.FieldRewardTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardTai(); ok {
		_spec.AddField(bounty.FieldRewardTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Submission(); ok {
		_spec.SetField(bounty.FieldSubmission, field.TypeString, value)
	}
	if _u.mutation.SubmissionCleared() {
		_spec.ClearField(bounty.FieldSubmission, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(bounty.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(bounty.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(bounty.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(bounty.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(bounty.FieldCompletedAt, field.TypeTime)
	}
	_node = &Bounty{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bounty.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
