// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/pet"
	"github.com/tii-mom/tai-protocol/backend/ent/user"
)

// Pet is the model entity for the Pet schema.
type Pet struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID uuid.UUID `json:"owner_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Species holds the value of the "species" field.
	Species string `json:"species,omitempty"`
	// Quality holds the value of the "quality" field.
	Quality string `json:"quality,omitempty"`
	// Generation holds the value of the "generation" field.
	Generation int `json:"generation,omitempty"`
	// GrowthRate holds the value of the "growth_rate" field.
	GrowthRate float64 `json:"growth_rate,omitempty"`
	// AptHp holds the value of the "apt_hp" field.
	AptHp int `json:"apt_hp,omitempty"`
	// AptAtk holds the value of the "apt_atk" field.
	AptAtk int `json:"apt_atk,omitempty"`
	// AptDef holds the value of the "apt_def" field.
	AptDef int `json:"apt_def,omitempty"`
	// AptSpd holds the value of the "apt_spd" field.
	AptSpd int `json:"apt_spd,omitempty"`
	// AptInt holds the value of the "apt_int" field.
	AptInt int `json:"apt_int,omitempty"`
	// SkillSlots holds the value of the "skill_slots" field.
	SkillSlots int `json:"skill_slots,omitempty"`
	// Personality holds the value of the "personality" field.
	Personality string `json:"personality,omitempty"`
	// Level holds the value of the "level" field.
	Level int `json:"level,omitempty"`
	// Exp holds the value of the "exp" field.
	Exp int64 `json:"exp,omitempty"`
	// Mood holds the value of the "mood" field.
	Mood int `json:"mood,omitempty"`
	// Energy holds the value of the "energy" field.
	Energy int `json:"energy,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// TaiBalance holds the value of the "tai_balance" field.
	TaiBalance float64 `json:"tai_balance,omitempty"`
	// ImageURL holds the value of the "image_url" field.
	ImageURL string `json:"image_url,omitempty"`
	// IsOnChain holds the value of the "is_on_chain" field.
	IsOnChain bool `json:"is_on_chain,omitempty"`
	// ChainNftAddress holds the value of the "chain_nft_address" field.
	ChainNftAddress *string `json:"chain_nft_address,omitempty"`
	// ChainMintedAt holds the value of the "chain_minted_at" field.
	ChainMintedAt *time.Time `json:"chain_minted_at,omitempty"`
	// BreedCooldownUntil holds the value of the "breed_cooldown_until" field.
	BreedCooldownUntil *time.Time `json:"breed_cooldown_until,omitempty"`
	// TotalEarnedTai holds the value of the "total_earned_tai" field.
	TotalEarnedTai float64 `json:"total_earned_tai,omitempty"`
	// TotalSpentTai holds the value of the "total_spent_tai" field.
	TotalSpentTai float64 `json:"total_spent_tai,omitempty"`
	// TotalTokensUsed holds the value of the "total_tokens_used" field.
	TotalTokensUsed int64 `json:"total_tokens_used,omitempty"`
	// TotalTasksDone holds the value of the "total_tasks_done" field.
	TotalTasksDone int `json:"total_tasks_done,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PetQuery when eager-loading is set.
	Edges        PetEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PetEdges holds the relations/edges for other nodes in the graph.
type PetEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Skills holds the value of the skills edge.
	Skills []*PetSkill `json:"skills,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PetEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// SkillsOrErr returns the Skills value or an error if the edge
// was not loaded in eager-loading.
func (e PetEdges) SkillsOrErr() ([]*PetSkill, error) {
	if e.loadedTypes[1] {
		return e.Skills, nil
	}
	return nil, &NotLoadedError{edge: "skills"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Pet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pet.FieldIsOnChain:
			values[i] = new(sql.NullBool)
		case pet.FieldGrowthRate, pet.FieldTaiBalance, pet.FieldTotalEarnedTai, pet.FieldTotalSpentTai:
			values[i] = new(sql.NullFloat64)
		case pet.FieldGeneration, pet.FieldAptHp, pet.FieldAptAtk, pet.FieldAptDef, pet.FieldAptSpd, pet.FieldAptInt, pet.FieldSkillSlots, pet.FieldLevel, pet.FieldExp, pet.FieldMood, pet.FieldEnergy, pet.FieldTotalTokensUsed, pet.FieldTotalTasksDone:
			values[i] = new(sql.NullInt64)
		case pet.FieldName, pet.FieldSpecies, pet.FieldQuality, pet.FieldPersonality, pet.FieldStatus, pet.FieldImageURL, pet.FieldChainNftAddress:
			values[i] = new(sql.NullString)
		case pet.FieldChainMintedAt, pet.FieldBreedCooldownUntil, pet.FieldCreatedAt, pet.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case pet.FieldID, pet.FieldOwnerID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Pet fields.
func (_m *Pet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pet.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case pet.FieldOwnerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value != nil {
				_m.OwnerID = *value
			}
		case pet.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case pet.FieldSpecies:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field species", values[i])
			} else if value.Valid {
				_m.Species = value.String
			}
		case pet.FieldQuality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quality", values[i])
			} else if value.Valid {
				_m.Quality = value.String
			}
		case pet.FieldGeneration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field generation", values[i])
			} else if value.Valid {
				_m.Generation = int(value.Int64)
			}
		case pet.FieldGrowthRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field growth_rate", values[i])
			} else if value.Valid {
				_m.GrowthRate = value.Float64
			}
		case pet.FieldAptHp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field apt_hp", values[i])
			} else if value.Valid {
				_m.AptHp = int(value.Int64)
			}
		case pet.FieldAptAtk:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field apt_atk", values[i])
			} else if value.Valid {
				_m.AptAtk = int(value.Int64)
			}
		case pet.FieldAptDef:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field apt_def", values[i])
			} else if value.Valid {
				_m.AptDef = int(value.Int64)
			}
		case pet.FieldAptSpd:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field apt_spd", values[i])
			} else if value.Valid {
				_m.AptSpd = int(value.Int64)
			}
		case pet.FieldAptInt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field apt_int", values[i])
			} else if value.Valid {
				_m.AptInt = int(value.Int64)
			}
		case pet.FieldSkillSlots:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field skill_slots", values[i])
			} else if value.Valid {
				_m.SkillSlots = int(value.Int64)
			}
		case pet.FieldPersonality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field personality", values[i])
			} else if value.Valid {
				_m.Personality = value.String
			}
		case pet.FieldLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				_m.Level = int(value.Int64)
			}
		case pet.FieldExp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field exp", values[i])
			} else if value.Valid {
				_m.Exp = value.Int64
			}
		case pet.FieldMood:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mood", values[i])
			} else if value.Valid {
				_m.Mood = int(value.Int64)
			}
		case pet.FieldEnergy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field energy", values[i])
			} else if value.Valid {
				_m.Energy = int(value.Int64)
			}
		case pet.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case pet.FieldTaiBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field tai_balance", values[i])
			} else if value.Valid {
				_m.TaiBalance = value.Float64
			}
		case pet.FieldImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_url", values[i])
			} else if value.Valid {
				_m.ImageURL = value.String
			}
		case pet.FieldIsOnChain:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_on_chain", values[i])
			} else if value.Valid {
				_m.IsOnChain = value.Bool
			}
		case pet.FieldChainNftAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chain_nft_address", values[i])
			} else if value.Valid {
				_m.ChainNftAddress = new(string)
				*_m.ChainNftAddress = value.String
			}
		case pet.FieldChainMintedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field chain_minted_at", values[i])
			} else if value.Valid {
				_m.ChainMintedAt = new(time.Time)
				*_m.ChainMintedAt = value.Time
			}
		case pet.FieldBreedCooldownUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field breed_cooldown_until", values[i])
			} else if value.Valid {
				_m.BreedCooldownUntil = new(time.Time)
				*_m.BreedCooldownUntil = value.Time
			}
		case pet.FieldTotalEarnedTai:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_earned_tai", values[i])
			} else if value.Valid {
				_m.TotalEarnedTai = value.Float64
			}
		case pet.FieldTotalSpentTai:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_spent_tai", values[i])
			} else if value.Valid {
				_m.TotalSpentTai = value.Float64
			}
		case pet.FieldTotalTokensUsed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_tokens_used", values[i])
			} else if value.Valid {
				_m.TotalTokensUsed = value.Int64
			}
		case pet.FieldTotalTasksDone:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_tasks_done", values[i])
			} else if value.Valid {
				_m.TotalTasksDone = int(value.Int64)
			}
		case pet.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pet.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Pet.
// This includes values selected through modifiers, order, etc.
func (_m *Pet) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Pet entity.
func (_m *Pet) QueryOwner() *UserQuery {
	return NewPetClient(_m.config).QueryOwner(_m)
}

// QuerySkills queries the "skills" edge of the Pet entity.
func (_m *Pet) QuerySkills() *PetSkillQuery {
	return NewPetClient(_m.config).QuerySkills(_m)
}

// Update returns a builder for updating this Pet.
// Note that you need to call Pet.Unwrap() before calling this method if this Pet
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Pet) Update() *PetUpdateOne {
	return NewPetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Pet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Pet) Unwrap() *Pet {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Pet is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Pet) String() string {
	var builder strings.Builder
	builder.WriteString("Pet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("species=")
	builder.WriteString(_m.Species)
	builder.WriteString(", ")
	builder.WriteString("quality=")
	builder.WriteString(_m.Quality)
	builder.WriteString(", ")
	builder.WriteString("generation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Generation))
	builder.WriteString(", ")
	builder.WriteString("growth_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrowthRate))
	builder.WriteString(", ")
	builder.WriteString("apt_hp=")
	builder.WriteString(fmt.Sprintf("%v", _m.AptHp))
	builder.WriteString(", ")
	builder.WriteString("apt_atk=")
	builder.WriteString(fmt.Sprintf("%v", _m.AptAtk))
	builder.WriteString(", ")
	builder.WriteString("apt_def=")
	builder.WriteString(fmt.Sprintf("%v", _m.AptDef))
	builder.WriteString(", ")
	builder.WriteString("apt_spd=")
	builder.WriteString(fmt.Sprintf("%v", _m.AptSpd))
	builder.WriteString(", ")
	builder.WriteString("apt_int=")
	builder.WriteString(fmt.Sprintf("%v", _m.AptInt))
	builder.WriteString(", ")
	builder.WriteString("skill_slots=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkillSlots))
	builder.WriteString(", ")
	builder.WriteString("personality=")
	builder.WriteString(_m.Personality)
	builder.WriteString(", ")
	builder.WriteString("level=")
	builder.WriteString(fmt.Sprintf("%v", _m.Level))
	builder.WriteString(", ")
	builder.WriteString("exp=")
	builder.WriteString(fmt.Sprintf("%v", _m.Exp))
	builder.WriteString(", ")
	builder.WriteString("mood=")
	builder.WriteString(fmt.Sprintf("%v", _m.Mood))
	builder.WriteString(", ")
	builder.WriteString("energy=")
	builder.WriteString(fmt.Sprintf("%v", _m.Energy))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("tai_balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaiBalance))
	builder.WriteString(", ")
	builder.WriteString("image_url=")
	builder.WriteString(_m.ImageURL)
	builder.WriteString(", ")
	builder.WriteString("is_on_chain=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsOnChain))
	builder.WriteString(", ")
	if v := _m.ChainNftAddress; v != nil {
		builder.WriteString("chain_nft_address=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ChainMintedAt; v != nil {
		builder.WriteString("chain_minted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.BreedCooldownUntil; v != nil {
		builder.WriteString("breed_cooldown_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("total_earned_tai=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalEarnedTai))
	builder.WriteString(", ")
	builder.WriteString("total_spent_tai=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalSpentTai))
	builder.WriteString(", ")
	builder.WriteString("total_tokens_used=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalTokensUsed))
	builder.WriteString(", ")
	builder.WriteString("total_tasks_done=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalTasksDone))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Pets is a parsable slice of Pet.
type Pets []*Pet
