// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/pet"
	"github.com/tii-mom/tai-protocol/backend/ent/petskill"
	"github.com/tii-mom/tai-protocol/backend/ent/predicate"
	"github.com/tii-mom/tai-protocol/backend/ent/user"
)

// PetUpdate is the builder for updating Pet entities.
type PetUpdate struct {
	config
	hooks    []Hook
	mutation *PetMutation
}

// Where appends a list predicates to the PetUpdate builder.
func (_u *PetUpdate) Where(ps ...predicate.Pet) *PetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *PetUpdate) SetOwnerID(v uuid.UUID) *PetUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *PetUpdate) SetNillableOwnerID(v *uuid.UUID) *PetUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PetUpdate) SetName(v string) *PetUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PetUpdate) SetNillableName(v *string) *PetUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSpecies sets the "species" field.
func (_u *PetUpdate) SetSpecies(v string) *PetUpdate {
	_u.mutation.SetSpecies(v)
	return _u
}

// SetNillableSpecies sets the "species" field if the given value is not nil.
func (_u *PetUpdate) SetNillableSpecies(v *string) *PetUpdate {
	if v != nil {
		_u.SetSpecies(*v)
	}
	return _u
}

// SetQuality sets the "quality" field.
func (_u *PetUpdate) SetQuality(v string) *PetUpdate {
	_u.mutation.SetQuality(v)
	return _u
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_u *PetUpdate) SetNillableQuality(v *string) *PetUpdate {
	if v != nil {
		_u.SetQuality(*v)
	}
	return _u
}

// SetGeneration sets the "generation" field.
func (_u *PetUpdate) SetGeneration(v int) *PetUpdate {
	_u.mutation.ResetGeneration()
	_u.mutation.SetGeneration(v)
	return _u
}

// SetNillableGeneration sets the "generation" field if the given value is not nil.
func (_u *PetUpdate) SetNillableGeneration(v *int) *PetUpdate {
	if v != nil {
		_u.SetGeneration(*v)
	}
	return _u
}

// AddGeneration adds value to the "generation" field.
func (_u *PetUpdate) AddGeneration(v int) *PetUpdate {
	_u.mutation.AddGeneration(v)
	return _u
}

// SetGrowthRate sets the "growth_rate" field.
func (_u *PetUpdate) SetGrowthRate(v float64) *PetUpdate {
	_u.mutation.ResetGrowthRate()
	_u.mutation.SetGrowthRate(v)
	return _u
}

// SetNillableGrowthRate sets the "growth_rate" field if the given value is not nil.
func (_u *PetUpdate) SetNillableGrowthRate(v *float64) *PetUpdate {
	if v != nil {
		_u.SetGrowthRate(*v)
	}
	return _u
}

// AddGrowthRate adds value to the "growth_rate" field.
func (_u *PetUpdate) AddGrowthRate(v float64) *PetUpdate {
	_u.mutation.AddGrowthRate(v)
	return _u
}

// SetAptHp sets the "apt_hp" field.
func (_u *PetUpdate) SetAptHp(v int) *PetUpdate {
	_u.mutation.ResetAptHp()
	_u.mutation.SetAptHp(v)
	return _u
}

// SetNillableAptHp sets the "apt_hp" field if the given value is not nil.
func (_u *PetUpdate) SetNillableAptHp(v *int) *PetUpdate {
	if v != nil {
		_u.SetAptHp(*v)
	}
	return _u
}

// AddAptHp adds value to the "apt_hp" field.
func (_u *PetUpdate) AddAptHp(v int) *PetUpdate {
	_u.mutation.AddAptHp(v)
	return _u
}

// SetAptAtk sets the "apt_atk" field.
func (_u *PetUpdate) SetAptAtk(v int) *PetUpdate {
	_u.mutation.ResetAptAtk()
	_u.mutation.SetAptAtk(v)
	return _u
}

// SetNillableAptAtk sets the "apt_atk" field if the given value is not nil.
func (_u *PetUpdate) SetNillableAptAtk(v *int) *PetUpdate {
	if v != nil {
		_u.SetAptAtk(*v)
	}
	return _u
}

// AddAptAtk adds value to the "apt_atk" field.
func (_u *PetUpdate) AddAptAtk(v int) *PetUpdate {
	_u.mutation.AddAptAtk(v)
	return _u
}

// SetAptDef sets the "apt_def" field.
func (_u *PetUpdate) SetAptDef(v int) *PetUpdate {
	_u.mutation.ResetAptDef()
	_u.mutation.SetAptDef(v)
	return _u
}

// SetNillableAptDef sets the "apt_def" field if the given value is not nil.
func (_u *PetUpdate) SetNillableAptDef(v *int) *PetUpdate {
	if v != nil {
		_u.SetAptDef(*v)
	}
	return _u
}

// AddAptDef adds value to the "apt_def" field.
func (_u *PetUpdate) AddAptDef(v int) *PetUpdate {
	_u.mutation.AddAptDef(v)
	return _u
}

// SetAptSpd sets the "apt_spd" field.
func (_u *PetUpdate) SetAptSpd(v int) *PetUpdate {
	_u.mutation.ResetAptSpd()
	_u.mutation.SetAptSpd(v)
	return _u
}

// SetNillableAptSpd sets the "apt_spd" field if the given value is not nil.
func (_u *PetUpdate) SetNillableAptSpd(v *int) *PetUpdate {
	if v != nil {
		_u.SetAptSpd(*v)
	}
	return _u
}

// AddAptSpd adds value to the "apt_spd" field.
func (_u *PetUpdate) AddAptSpd(v int) *PetUpdate {
	_u.mutation.AddAptSpd(v)
	return _u
}

// SetAptInt sets the "apt_int" field.
func (_u *PetUpdate) SetAptInt(v int) *PetUpdate {
	_u.mutation.ResetAptInt()
	_u.mutation.SetAptInt(v)
	return _u
}

// SetNillableAptInt sets the "apt_int" field if the given value is not nil.
func (_u *PetUpdate) SetNillableAptInt(v *int) *PetUpdate {
	if v != nil {
		_u.SetAptInt(*v)
	}
	return _u
}

// AddAptInt adds value to the "apt_int" field.
func (_u *PetUpdate) AddAptInt(v int) *PetUpdate {
	_u.mutation.AddAptInt(v)
	return _u
}

// SetSkillSlots sets the "skill_slots" field.
func (_u *PetUpdate) SetSkillSlots(v int) *PetUpdate {
	_u.mutation.ResetSkillSlots()
	_u.mutation.SetSkillSlots(v)
	return _u
}

// SetNillableSkillSlots sets the "skill_slots" field if the given value is not nil.
func (_u *PetUpdate) SetNillableSkillSlots(v *int) *PetUpdate {
	if v != nil {
		_u.SetSkillSlots(*v)
	}
	return _u
}

// AddSkillSlots adds value to the "skill_slots" field.
func (_u *PetUpdate) AddSkillSlots(v int) *PetUpdate {
	_u.mutation.AddSkillSlots(v)
	return _u
}

// SetPersonality sets the "personality" field.
func (_u *PetUpdate) SetPersonality(v string) *PetUpdate {
	_u.mutation.SetPersonality(v)
	return _u
}

// SetNillablePersonality sets the "personality" field if the given value is not nil.
func (_u *PetUpdate) SetNillablePersonality(v *string) *PetUpdate {
	if v != nil {
		_u.SetPersonality(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *PetUpdate) SetLevel(v int) *PetUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *PetUpdate) SetNillableLevel(v *int) *PetUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *PetUpdate) AddLevel(v int) *PetUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// SetExp sets the "exp" field.
func (_u *PetUpdate) SetExp(v int64) *PetUpdate {
	_u.mutation.ResetExp()
	_u.mutation.SetExp(v)
	return _u
}

// SetNillableExp sets the "exp" field if the given value is not nil.
func (_u *PetUpdate) SetNillableExp(v *int64) *PetUpdate {
	if v != nil {
		_u.SetExp(*v)
	}
	return _u
}

// AddExp adds value to the "exp" field.
func (_u *PetUpdate) AddExp(v int64) *PetUpdate {
	_u.mutation.AddExp(v)
	return _u
}

// SetMood sets the "mood" field.
func (_u *PetUpdate) SetMood(v int) *PetUpdate {
	_u.mutation.ResetMood()
	_u.mutation.SetMood(v)
	return _u
}

// SetNillableMood sets the "mood" field if the given value is not nil.
func (_u *PetUpdate) SetNillableMood(v *int) *PetUpdate {
	if v != nil {
		_u.SetMood(*v)
	}
	return _u
}

// AddMood adds value to the "mood" field.
func (_u *PetUpdate) AddMood(v int) *PetUpdate {
	_u.mutation.AddMood(v)
	return _u
}

// SetEnergy sets the "energy" field.
func (_u *PetUpdate) SetEnergy(v int) *PetUpdate {
	_u.mutation.ResetEnergy()
	_u.mutation.SetEnergy(v)
	return _u
}

// SetNillableEnergy sets the "energy" field if the given value is not nil.
func (_u *PetUpdate) SetNillableEnergy(v *int) *PetUpdate {
	if v != nil {
		_u.SetEnergy(*v)
	}
	return _u
}

// AddEnergy adds value to the "energy" field.
func (_u *PetUpdate) AddEnergy(v int) *PetUpdate {
	_u.mutation.AddEnergy(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PetUpdate) SetStatus(v string) *PetUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PetUpdate) SetNillableStatus(v *string) *PetUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTaiBalance sets the "tai_balance" field.
func (_u *PetUpdate) SetTaiBalance(v float64) *PetUpdate {
	_u.mutation.ResetTaiBalance()
	_u.mutation.SetTaiBalance(v)
	return _u
}

// SetNillableTaiBalance sets the "tai_balance" field if the given value is not nil.
func (_u *PetUpdate) SetNillableTaiBalance(v *float64) *PetUpdate {
	if v != nil {
		_u.SetTaiBalance(*v)
	}
	return _u
}

// AddTaiBalance adds value to the "tai_balance" field.
func (_u *PetUpdate) AddTaiBalance(v float64) *PetUpdate {
	_u.mutation.AddTaiBalance(v)
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *PetUpdate) SetImageURL(v string) *PetUpdate {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *PetUpdate) SetNillableImageURL(v *string) *PetUpdate {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// ClearImageURL clears the value of the "image_url" field.
func (_u *PetUpdate) ClearImageURL() *PetUpdate {
	_u.mutation.ClearImageURL()
	return _u
}

// SetIsOnChain sets the "is_on_chain" field.
func (_u *PetUpdate) SetIsOnChain(v bool) *PetUpdate {
	_u.mutation.SetIsOnChain(v)
	return _u
}

// SetNillableIsOnChain sets the "is_on_chain" field if the given value is not nil.
func (_u *PetUpdate) SetNillableIsOnChain(v *bool) *PetUpdate {
	if v != nil {
		_u.SetIsOnChain(*v)
	}
	return _u
}

// SetChainNftAddress sets the "chain_nft_address" field.
func (_u *PetUpdate) SetChainNftAddress(v string) *PetUpdate {
	_u.mutation.SetChainNftAddress(v)
	return _u
}

// SetNillableChainNftAddress sets the "chain_nft_address" field if the given value is not nil.
func (_u *PetUpdate) SetNillableChainNftAddress(v *string) *PetUpdate {
	if v != nil {
		_u.SetChainNftAddress(*v)
	}
	return _u
}

// ClearChainNftAddress clears the value of the "chain_nft_address" field.
func (_u *PetUpdate) ClearChainNftAddress() *PetUpdate {
	_u.mutation.ClearChainNftAddress()
	return _u
}

// SetChainMintedAt sets the "chain_minted_at" field.
func (_u *PetUpdate) SetChainMintedAt(v time.Time) *PetUpdate {
	_u.mutation.SetChainMintedAt(v)
	return _u
}

// SetNillableChainMintedAt sets the "chain_minted_at" field if the given value is not nil.
func (_u *PetUpdate) SetNillableChainMintedAt(v *time.Time) *PetUpdate {
	if v != nil {
		_u.SetChainMintedAt(*v)
	}
	return _u
}

// ClearChainMintedAt clears the value of the "chain_minted_at" field.
func (_u *PetUpdate) ClearChainMintedAt() *PetUpdate {
	_u.mutation.ClearChainMintedAt()
	return _u
}

// SetBreedCooldownUntil sets the "breed_cooldown_until" field.
func (_u *PetUpdate) SetBreedCooldownUntil(v time.Time) *PetUpdate {
	_u.mutation.SetBreedCooldownUntil(v)
	return _u
}

// SetNillableBreedCooldownUntil sets the "breed_cooldown_until" field if the given value is not nil.
func (_u *PetUpdate) SetNillableBreedCooldownUntil(v *time.Time) *PetUpdate {
	if v != nil {
		_u.SetBreedCooldownUntil(*v)
	}
	return _u
}

// ClearBreedCooldownUntil clears the value of the "breed_cooldown_until" field.
func (_u *PetUpdate) ClearBreedCooldownUntil() *PetUpdate {
	_u.mutation.ClearBreedCooldownUntil()
	return _u
}

// SetTotalEarnedTai sets the "total_earned_tai" field.
func (_u *PetUpdate) SetTotalEarnedTai(v float64) *PetUpdate {
	_u.mutation.ResetTotalEarnedTai()
	_u.mutation.SetTotalEarnedTai(v)
	return _u
}

// SetNillableTotalEarnedTai sets the "total_earned_tai" field if the given value is not nil.
func (_u *PetUpdate) SetNillableTotalEarnedTai(v *float64) *PetUpdate {
	if v != nil {
		_u.SetTotalEarnedTai(*v)
	}
	return _u
}

// AddTotalEarnedTai adds value to the "total_earned_tai" field.
func (_u *PetUpdate) AddTotalEarnedTai(v float64) *PetUpdate {
	_u.mutation.AddTotalEarnedTai(v)
	return _u
}

// SetTotalSpentTai sets the "total_spent_tai" field.
func (_u *PetUpdate) SetTotalSpentTai(v float64) *PetUpdate {
	_u.mutation.ResetTotalSpentTai()
	_u.mutation.SetTotalSpentTai(v)
	return _u
}

// SetNillableTotalSpentTai sets the "total_spent_tai" field if the given value is not nil.
func (_u *PetUpdate) SetNillableTotalSpentTai(v *float64) *PetUpdate {
	if v != nil {
		_u.SetTotalSpentTai(*v)
	}
	return _u
}

// AddTotalSpentTai adds value to the "total_spent_tai" field.
func (_u *PetUpdate) AddTotalSpentTai(v float64) *PetUpdate {
	_u.mutation.AddTotalSpentTai(v)
	return _u
}

// SetTotalTokensUsed sets the "total_tokens_used" field.
func (_u *PetUpdate) SetTotalTokensUsed(v int64) *PetUpdate {
	_u.mutation.ResetTotalTokensUsed()
	_u.mutation.SetTotalTokensUsed(v)
	return _u
}

// SetNillableTotalTokensUsed sets the "total_tokens_used" field if the given value is not nil.
func (_u *PetUpdate) SetNillableTotalTokensUsed(v *int64) *PetUpdate {
	if v != nil {
		_u.SetTotalTokensUsed(*v)
	}
	return _u
}

// AddTotalTokensUsed adds value to the "total_tokens_used" field.
func (_u *PetUpdate) AddTotalTokensUsed(v int64) *PetUpdate {
	_u.mutation.AddTotalTokensUsed(v)
	return _u
}

// SetTotalTasksDone sets the "total_tasks_done" field.
func (_u *PetUpdate) SetTotalTasksDone(v int) *PetUpdate {
	_u.mutation.ResetTotalTasksDone()
	_u.mutation.SetTotalTasksDone(v)
	return _u
}

// SetNillableTotalTasksDone sets the "total_tasks_done" field if the given value is not nil.
func (_u *PetUpdate) SetNillableTotalTasksDone(v *int) *PetUpdate {
	if v != nil {
		_u.SetTotalTasksDone(*v)
	}
	return _u
}

// AddTotalTasksDone adds value to the "total_tasks_done" field.
func (_u *PetUpdate) AddTotalTasksDone(v int) *PetUpdate {
	_u.mutation.AddTotalTasksDone(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PetUpdate) SetUpdatedAt(v time.Time) *PetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *PetUpdate) SetOwner(v *User) *PetUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddSkillIDs adds the "skills" edge to the PetSkill entity by IDs.
func (_u *PetUpdate) AddSkillIDs(ids ...uuid.UUID) *PetUpdate {
	_u.mutation.AddSkillIDs(ids...)
	return _u
}

// AddSkills adds the "skills" edges to the PetSkill entity.
func (_u *PetUpdate) AddSkills(v ...*PetSkill) *PetUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSkillIDs(ids...)
}

// Mutation returns the PetMutation object of the builder.
func (_u *PetUpdate) Mutation() *PetMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *PetUpdate) ClearOwner() *PetUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearSkills clears all "skills" edges to the PetSkill entity.
func (_u *PetUpdate) ClearSkills() *PetUpdate {
	_u.mutation.ClearSkills()
	return _u
}

// RemoveSkillIDs removes the "skills" edge to PetSkill entities by IDs.
func (_u *PetUpdate) RemoveSkillIDs(ids ...uuid.UUID) *PetUpdate {
	_u.mutation.RemoveSkillIDs(ids...)
	return _u
}

// RemoveSkills removes "skills" edges to PetSkill entities.
func (_u *PetUpdate) RemoveSkills(v ...*PetSkill) *PetUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSkillIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PetUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PetUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := pet.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Pet.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Species(); ok {
		if err := pet.SpeciesValidator(v); err != nil {
			return &ValidationError{Name: "species", err: fmt.Errorf(`ent: validator failed for field "Pet.species": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quality(); ok {
		if err := pet.QualityValidator(v); err != nil {
			return &ValidationError{Name: "quality", err: fmt.Errorf(`ent: validator failed for field "Pet.quality": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Personality(); ok {
		if err := pet.PersonalityValidator(v); err != nil {
			return &ValidationError{Name: "personality", err: fmt.Errorf(`ent: validator failed for field "Pet.personality": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := pet.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Pet.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageURL(); ok {
		if err := pet.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "Pet.image_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChainNftAddress(); ok {
		if err := pet.ChainNftAddressValidator(v); err != nil {
			return &ValidationError{Name: "chain_nft_address", err: fmt.Errorf(`ent: validator failed for field "Pet.chain_nft_address": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pet.owner"`)
	}
	return nil
}

func (_u *PetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pet.Table, pet.Columns, sqlgraph.NewFieldSpec(pet.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pet.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Species(); ok {
		_spec.SetField(pet.FieldSpecies, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quality(); ok {
		_spec.SetField(pet.FieldQuality, field.TypeString, value)
	}
	if value, ok := _u.mutation.Generation(); ok {
		_spec.SetField(pet.FieldGeneration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGeneration(); ok {
		_spec.AddField(pet.FieldGeneration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GrowthRate(); ok {
		_spec.SetField(pet.FieldGrowthRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrowthRate(); ok {
		_spec.AddField(pet.FieldGrowthRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AptHp(); ok {
		_spec.SetField(pet.FieldAptHp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAptHp(); ok {
		_spec.AddField(pet.FieldAptHp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AptAtk(); ok {
		_spec.SetField(pet.FieldAptAtk, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAptAtk(); ok {
		_spec.AddField(pet.FieldAptAtk, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AptDef(); ok {
		_spec.SetField(pet.FieldAptDef, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAptDef(); ok {
		_spec.AddField(pet.FieldAptDef, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AptSpd(); ok {
		_spec.SetField(pet.FieldAptSpd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAptSpd(); ok {
		_spec.AddField(pet.FieldAptSpd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AptInt(); ok {
		_spec.SetField(pet.FieldAptInt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAptInt(); ok {
		_spec.AddField(pet.FieldAptInt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SkillSlots(); ok {
		_spec.SetField(pet.FieldSkillSlots, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSkillSlots(); ok {
		_spec.AddField(pet.FieldSkillSlots, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Personality(); ok {
		_spec.SetField(pet.FieldPersonality, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(pet.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(pet.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Exp(); ok {
		_spec.SetField(pet.FieldExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExp(); ok {
		_spec.AddField(pet.FieldExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Mood(); ok {
		_spec.SetField(pet.FieldMood, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMood(); ok {
		_spec.AddField(pet.FieldMood, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Energy(); ok {
		_spec.SetField(pet.FieldEnergy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEnergy(); ok {
		_spec.AddField(pet.FieldEnergy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(pet.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaiBalance(); ok {
		_spec.SetField(pet.FieldTaiBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTaiBalance(); ok {
		_spec.AddField(pet.FieldTaiBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(pet.FieldImageURL, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(pet.FieldImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.IsOnChain(); ok {
		_spec.SetField(pet.FieldIsOnChain, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ChainNftAddress(); ok {
		_spec.SetField(pet.FieldChainNftAddress, field.TypeString, value)
	}
	if _u.mutation.ChainNftAddressCleared() {
		_spec.ClearField(pet.FieldChainNftAddress, field.TypeString)
	}
	if value, ok := _u.mutation.ChainMintedAt(); ok {
		_spec.SetField(pet.FieldChainMintedAt, field.TypeTime, value)
	}
	if _u.mutation.ChainMintedAtCleared() {
		_spec.ClearField(pet.FieldChainMintedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BreedCooldownUntil(); ok {
		_spec.SetField(pet.FieldBreedCooldownUntil, field.TypeTime, value)
	}
	if _u.mutation.BreedCooldownUntilCleared() {
		_spec.ClearField(pet.FieldBreedCooldownUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.TotalEarnedTai(); ok {
		_spec.SetField(pet.FieldTotalEarnedTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalEarnedTai(); ok {
		_spec.AddField(pet.FieldTotalEarnedTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalSpentTai(); ok {
		_spec.SetField(pet.FieldTotalSpentTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalSpentTai(); ok {
		_spec.AddField(pet.FieldTotalSpentTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalTokensUsed(); ok {
		_spec.SetField(pet.FieldTotalTokensUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokensUsed(); ok {
		_spec.AddField(pet.FieldTotalTokensUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTasksDone(); ok {
		_spec.SetField(pet.FieldTotalTasksDone, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalTasksDone(); ok {
		_spec.AddField(pet.FieldTotalTasksDone, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pet.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pet.OwnerTable,
			Columns: []string{pet.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pet.OwnerTable,
			Columns: []string{pet.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pet.SkillsTable,
			Columns: []string{pet.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(petskill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSkillsIDs(); len(nodes) > 0 && !_u.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pet.SkillsTable,
			Columns: []string{pet.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(petskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pet.SkillsTable,
			Columns: []string{pet.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(petskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PetUpdateOne is the builder for updating a single Pet entity.
type PetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PetMutation
}

// SetOwnerID sets the "owner_id" field.
func (_u *PetUpdateOne) SetOwnerID(v uuid.UUID) *PetUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableOwnerID(v *uuid.UUID) *PetUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PetUpdateOne) SetName(v string) *PetUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableName(v *string) *PetUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSpecies sets the "species" field.
func (_u *PetUpdateOne) SetSpecies(v string) *PetUpdateOne {
	_u.mutation.SetSpecies(v)
	return _u
}

// SetNillableSpecies sets the "species" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableSpecies(v *string) *PetUpdateOne {
	if v != nil {
		_u.SetSpecies(*v)
	}
	return _u
}

// SetQuality sets the "quality" field.
func (_u *PetUpdateOne) SetQuality(v string) *PetUpdateOne {
	_u.mutation.SetQuality(v)
	return _u
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableQuality(v *string) *PetUpdateOne {
	if v != nil {
		_u.SetQuality(*v)
	}
	return _u
}

// SetGeneration sets the "generation" field.
func (_u *PetUpdateOne) SetGeneration(v int) *PetUpdateOne {
	_u.mutation.ResetGeneration()
	_u.mutation.SetGeneration(v)
	return _u
}

// SetNillableGeneration sets the "generation" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableGeneration(v *int) *PetUpdateOne {
	if v != nil {
		_u.SetGeneration(*v)
	}
	return _u
}

// AddGeneration adds value to the "generation" field.
func (_u *PetUpdateOne) AddGeneration(v int) *PetUpdateOne {
	_u.mutation.AddGeneration(v)
	return _u
}

// SetGrowthRate sets the "growth_rate" field.
func (_u *PetUpdateOne) SetGrowthRate(v float64) *PetUpdateOne {
	_u.mutation.ResetGrowthRate()
	_u.mutation.SetGrowthRate(v)
	return _u
}

// SetNillableGrowthRate sets the "growth_rate" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableGrowthRate(v *float64) *PetUpdateOne {
	if v != nil {
		_u.SetGrowthRate(*v)
	}
	return _u
}

// AddGrowthRate adds value to the "growth_rate" field.
func (_u *PetUpdateOne) AddGrowthRate(v float64) *PetUpdateOne {
	_u.mutation.AddGrowthRate(v)
	return _u
}

// SetAptHp sets the "apt_hp" field.
func (_u *PetUpdateOne) SetAptHp(v int) *PetUpdateOne {
	_u.mutation.ResetAptHp()
	_u.mutation.SetAptHp(v)
	return _u
}

// SetNillableAptHp sets the "apt_hp" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableAptHp(v *int) *PetUpdateOne {
	if v != nil {
		_u.SetAptHp(*v)
	}
	return _u
}

// AddAptHp adds value to the "apt_hp" field.
func (_u *PetUpdateOne) AddAptHp(v int) *PetUpdateOne {
	_u.mutation.AddAptHp(v)
	return _u
}

// SetAptAtk sets the "apt_atk" field.
func (_u *PetUpdateOne) SetAptAtk(v int) *PetUpdateOne {
	_u.mutation.ResetAptAtk()
	_u.mutation.SetAptAtk(v)
	return _u
}

// SetNillableAptAtk sets the "apt_atk" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableAptAtk(v *int) *PetUpdateOne {
	if v != nil {
		_u.SetAptAtk(*v)
	}
	return _u
}

// AddAptAtk adds value to the "apt_atk" field.
func (_u *PetUpdateOne) AddAptAtk(v int) *PetUpdateOne {
	_u.mutation.AddAptAtk(v)
	return _u
}

// SetAptDef sets the "apt_def" field.
func (_u *PetUpdateOne) SetAptDef(v int) *PetUpdateOne {
	_u.mutation.ResetAptDef()
	_u.mutation.SetAptDef(v)
	return _u
}

// SetNillableAptDef sets the "apt_def" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableAptDef(v *int) *PetUpdateOne {
	if v != nil {
		_u.SetAptDef(*v)
	}
	return _u
}

// AddAptDef adds value to the "apt_def" field.
func (_u *PetUpdateOne) AddAptDef(v int) *PetUpdateOne {
	_u.mutation.AddAptDef(v)
	return _u
}

// SetAptSpd sets the "apt_spd" field.
func (_u *PetUpdateOne) SetAptSpd(v int) *PetUpdateOne {
	_u.mutation.ResetAptSpd()
	_u.mutation.SetAptSpd(v)
	return _u
}

// SetNillableAptSpd sets the "apt_spd" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableAptSpd(v *int) *PetUpdateOne {
	if v != nil {
		_u.SetAptSpd(*v)
	}
	return _u
}

// AddAptSpd adds value to the "apt_spd" field.
func (_u *PetUpdateOne) AddAptSpd(v int) *PetUpdateOne {
	_u.mutation.AddAptSpd(v)
	return _u
}

// SetAptInt sets the "apt_int" field.
func (_u *PetUpdateOne) SetAptInt(v int) *PetUpdateOne {
	_u.mutation.ResetAptInt()
	_u.mutation.SetAptInt(v)
	return _u
}

// SetNillableAptInt sets the "apt_int" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableAptInt(v *int) *PetUpdateOne {
	if v != nil {
		_u.SetAptInt(*v)
	}
	return _u
}

// AddAptInt adds value to the "apt_int" field.
func (_u *PetUpdateOne) AddAptInt(v int) *PetUpdateOne {
	_u.mutation.AddAptInt(v)
	return _u
}

// SetSkillSlots sets the "skill_slots" field.
func (_u *PetUpdateOne) SetSkillSlots(v int) *PetUpdateOne {
	_u.mutation.ResetSkillSlots()
	_u.mutation.SetSkillSlots(v)
	return _u
}

// SetNillableSkillSlots sets the "skill_slots" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableSkillSlots(v *int) *PetUpdateOne {
	if v != nil {
		_u.SetSkillSlots(*v)
	}
	return _u
}

// AddSkillSlots adds value to the "skill_slots" field.
func (_u *PetUpdateOne) AddSkillSlots(v int) *PetUpdateOne {
	_u.mutation.AddSkillSlots(v)
	return _u
}

// SetPersonality sets the "personality" field.
func (_u *PetUpdateOne) SetPersonality(v string) *PetUpdateOne {
	_u.mutation.SetPersonality(v)
	return _u
}

// SetNillablePersonality sets the "personality" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillablePersonality(v *string) *PetUpdateOne {
	if v != nil {
		_u.SetPersonality(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *PetUpdateOne) SetLevel(v int) *PetUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableLevel(v *int) *PetUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *PetUpdateOne) AddLevel(v int) *PetUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// SetExp sets the "exp" field.
func (_u *PetUpdateOne) SetExp(v int64) *PetUpdateOne {
	_u.mutation.ResetExp()
	_u.mutation.SetExp(v)
	return _u
}

// SetNillableExp sets the "exp" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableExp(v *int64) *PetUpdateOne {
	if v != nil {
		_u.SetExp(*v)
	}
	return _u
}

// AddExp adds value to the "exp" field.
func (_u *PetUpdateOne) AddExp(v int64) *PetUpdateOne {
	_u.mutation.AddExp(v)
	return _u
}

// SetMood sets the "mood" field.
func (_u *PetUpdateOne) SetMood(v int) *PetUpdateOne {
	_u.mutation.ResetMood()
	_u.mutation.SetMood(v)
	return _u
}

// SetNillableMood sets the "mood" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableMood(v *int) *PetUpdateOne {
	if v != nil {
		_u.SetMood(*v)
	}
	return _u
}

// AddMood adds value to the "mood" field.
func (_u *PetUpdateOne) AddMood(v int) *PetUpdateOne {
	_u.mutation.AddMood(v)
	return _u
}

// SetEnergy sets the "energy" field.
func (_u *PetUpdateOne) SetEnergy(v int) *PetUpdateOne {
	_u.mutation.ResetEnergy()
	_u.mutation.SetEnergy(v)
	return _u
}

// SetNillableEnergy sets the "energy" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableEnergy(v *int) *PetUpdateOne {
	if v != nil {
		_u.SetEnergy(*v)
	}
	return _u
}

// AddEnergy adds value to the "energy" field.
func (_u *PetUpdateOne) AddEnergy(v int) *PetUpdateOne {
	_u.mutation.AddEnergy(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PetUpdateOne) SetStatus(v string) *PetUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableStatus(v *string) *PetUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTaiBalance sets the "tai_balance" field.
func (_u *PetUpdateOne) SetTaiBalance(v float64) *PetUpdateOne {
	_u.mutation.ResetTaiBalance()
	_u.mutation.SetTaiBalance(v)
	return _u
}

// SetNillableTaiBalance sets the "tai_balance" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableTaiBalance(v *float64) *PetUpdateOne {
	if v != nil {
		_u.SetTaiBalance(*v)
	}
	return _u
}

// AddTaiBalance adds value to the "tai_balance" field.
func (_u *PetUpdateOne) AddTaiBalance(v float64) *PetUpdateOne {
	_u.mutation.AddTaiBalance(v)
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *PetUpdateOne) SetImageURL(v string) *PetUpdateOne {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableImageURL(v *string) *PetUpdateOne {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// ClearImageURL clears the value of the "image_url" field.
func (_u *PetUpdateOne) ClearImageURL() *PetUpdateOne {
	_u.mutation.ClearImageURL()
	return _u
}

// SetIsOnChain sets the "is_on_chain" field.
func (_u *PetUpdateOne) SetIsOnChain(v bool) *PetUpdateOne {
	_u.mutation.SetIsOnChain(v)
	return _u
}

// SetNillableIsOnChain sets the "is_on_chain" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableIsOnChain(v *bool) *PetUpdateOne {
	if v != nil {
		_u.SetIsOnChain(*v)
	}
	return _u
}

// SetChainNftAddress sets the "chain_nft_address" field.
func (_u *PetUpdateOne) SetChainNftAddress(v string) *PetUpdateOne {
	_u.mutation.SetChainNftAddress(v)
	return _u
}

// SetNillableChainNftAddress sets the "chain_nft_address" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableChainNftAddress(v *string) *PetUpdateOne {
	if v != nil {
		_u.SetChainNftAddress(*v)
	}
	return _u
}

// ClearChainNftAddress clears the value of the "chain_nft_address" field.
func (_u *PetUpdateOne) ClearChainNftAddress() *PetUpdateOne {
	_u.mutation.ClearChainNftAddress()
	return _u
}

// SetChainMintedAt sets the "chain_minted_at" field.
func (_u *PetUpdateOne) SetChainMintedAt(v time.Time) *PetUpdateOne {
	_u.mutation.SetChainMintedAt(v)
	return _u
}

// SetNillableChainMintedAt sets the "chain_minted_at" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableChainMintedAt(v *time.Time) *PetUpdateOne {
	if v != nil {
		_u.SetChainMintedAt(*v)
	}
	return _u
}

// ClearChainMintedAt clears the value of the "chain_minted_at" field.
func (_u *PetUpdateOne) ClearChainMintedAt() *PetUpdateOne {
	_u.mutation.ClearChainMintedAt()
	return _u
}

// SetBreedCooldownUntil sets the "breed_cooldown_until" field.
func (_u *PetUpdateOne) SetBreedCooldownUntil(v time.Time) *PetUpdateOne {
	_u.mutation.SetBreedCooldownUntil(v)
	return _u
}

// SetNillableBreedCooldownUntil sets the "breed_cooldown_until" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableBreedCooldownUntil(v *time.Time) *PetUpdateOne {
	if v != nil {
		_u.SetBreedCooldownUntil(*v)
	}
	return _u
}

// ClearBreedCooldownUntil clears the value of the "breed_cooldown_until" field.
func (_u *PetUpdateOne) ClearBreedCooldownUntil() *PetUpdateOne {
	_u.mutation.ClearBreedCooldownUntil()
	return _u
}

// SetTotalEarnedTai sets the "total_earned_tai" field.
func (_u *PetUpdateOne) SetTotalEarnedTai(v float64) *PetUpdateOne {
	_u.mutation.ResetTotalEarnedTai()
	_u.mutation.SetTotalEarnedTai(v)
	return _u
}

// SetNillableTotalEarnedTai sets the "total_earned_tai" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableTotalEarnedTai(v *float64) *PetUpdateOne {
	if v != nil {
		_u.SetTotalEarnedTai(*v)
	}
	return _u
}

// AddTotalEarnedTai adds value to the "total_earned_tai" field.
func (_u *PetUpdateOne) AddTotalEarnedTai(v float64) *PetUpdateOne {
	_u.mutation.AddTotalEarnedTai(v)
	return _u
}

// SetTotalSpentTai sets the "total_spent_tai" field.
func (_u *PetUpdateOne) SetTotalSpentTai(v float64) *PetUpdateOne {
	_u.mutation.ResetTotalSpentTai()
	_u.mutation.SetTotalSpentTai(v)
	return _u
}

// SetNillableTotalSpentTai sets the "total_spent_tai" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableTotalSpentTai(v *float64) *PetUpdateOne {
	if v != nil {
		_u.SetTotalSpentTai(*v)
	}
	return _u
}

// AddTotalSpentTai adds value to the "total_spent_tai" field.
func (_u *PetUpdateOne) AddTotalSpentTai(v float64) *PetUpdateOne {
	_u.mutation.AddTotalSpentTai(v)
	return _u
}

// SetTotalTokensUsed sets the "total_tokens_used" field.
func (_u *PetUpdateOne) SetTotalTokensUsed(v int64) *PetUpdateOne {
	_u.mutation.ResetTotalTokensUsed()
	_u.mutation.SetTotalTokensUsed(v)
	return _u
}

// SetNillableTotalTokensUsed sets the "total_tokens_used" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableTotalTokensUsed(v *int64) *PetUpdateOne {
	if v != nil {
		_u.SetTotalTokensUsed(*v)
	}
	return _u
}

// AddTotalTokensUsed adds value to the "total_tokens_used" field.
func (_u *PetUpdateOne) AddTotalTokensUsed(v int64) *PetUpdateOne {
	_u.mutation.AddTotalTokensUsed(v)
	return _u
}

// SetTotalTasksDone sets the "total_tasks_done" field.
func (_u *PetUpdateOne) SetTotalTasksDone(v int) *PetUpdateOne {
	_u.mutation.ResetTotalTasksDone()
	_u.mutation.SetTotalTasksDone(v)
	return _u
}

// SetNillableTotalTasksDone sets the "total_tasks_done" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableTotalTasksDone(v *int) *PetUpdateOne {
	if v != nil {
		_u.SetTotalTasksDone(*v)
	}
	return _u
}

// AddTotalTasksDone adds value to the "total_tasks_done" field.
func (_u *PetUpdateOne) AddTotalTasksDone(v int) *PetUpdateOne {
	_u.mutation.AddTotalTasksDone(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PetUpdateOne) SetUpdatedAt(v time.Time) *PetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *PetUpdateOne) SetOwner(v *User) *PetUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddSkillIDs adds the "skills" edge to the PetSkill entity by IDs.
func (_u *PetUpdateOne) AddSkillIDs(ids ...uuid.UUID) *PetUpdateOne {
	_u.mutation.AddSkillIDs(ids...)
	return _u
}

// AddSkills adds the "skills" edges to the PetSkill entity.
func (_u *PetUpdateOne) AddSkills(v ...*PetSkill) *PetUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSkillIDs(ids...)
}

// Mutation returns the PetMutation object of the builder.
func (_u *PetUpdateOne) Mutation() *PetMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *PetUpdateOne) ClearOwner() *PetUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearSkills clears all "skills" edges to the PetSkill entity.
func (_u *PetUpdateOne) ClearSkills() *PetUpdateOne {
	_u.mutation.ClearSkills()
	return _u
}

// RemoveSkillIDs removes the "skills" edge to PetSkill entities by IDs.
func (_u *PetUpdateOne) RemoveSkillIDs(ids ...uuid.UUID) *PetUpdateOne {
	_u.mutation.RemoveSkillIDs(ids...)
	return _u
}

// RemoveSkills removes "skills" edges to PetSkill entities.
func (_u *PetUpdateOne) RemoveSkills(v ...*PetSkill) *PetUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSkillIDs(ids...)
}

// Where appends a list predicates to the PetUpdate builder.
func (_u *PetUpdateOne) Where(ps ...predicate.Pet) *PetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PetUpdateOne) Select(field string, fields ...string) *PetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Pet entity.
func (_u *PetUpdateOne) Save(ctx context.Context) (*Pet, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PetUpdateOne) SaveX(ctx context.Context) *Pet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PetUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := pet.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Pet.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Species(); ok {
		if err := pet.SpeciesValidator(v); err != nil {
			return &ValidationError{Name: "species", err: fmt.Errorf(`ent: validator failed for field "Pet.species": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quality(); ok {
		if err := pet.QualityValidator(v); err != nil {
			return &ValidationError{Name: "quality", err: fmt.Errorf(`ent: validator failed for field "Pet.quality": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Personality(); ok {
		if err := pet.PersonalityValidator(v); err != nil {
			return &ValidationError{Name: "personality", err: fmt.Errorf(`ent: validator failed for field "Pet.personality": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := pet.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Pet.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageURL(); ok {
		if err := pet.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "Pet.image_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChainNftAddress(); ok {
		if err := pet.ChainNftAddressValidator(v); err != nil {
			return &ValidationError{Name: "chain_nft_address", err: fmt.Errorf(`ent: validator failed for field "Pet.chain_nft_address": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pet.owner"`)
	}
	return nil
}

func (_u *PetUpdateOne) sqlSave(ctx context.Context) (_node *Pet, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pet.Table, pet.Columns, sqlgraph.NewFieldSpec(pet.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pet.FieldID)
		for _, f := range fields {
			if !pet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pet.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Species(); ok {
		_spec.SetField(pet.FieldSpecies, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quality(); ok {
		_spec.SetField(pet.FieldQuality, field.TypeString, value)
	}
	if value, ok := _u.mutation.Generation(); ok {
		_spec.SetField(pet.FieldGeneration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGeneration(); ok {
		_spec.AddField(pet.FieldGeneration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GrowthRate(); ok {
		_spec.SetField(pet.FieldGrowthRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrowthRate(); ok {
		_spec.AddField(pet.FieldGrowthRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AptHp(); ok {
		_spec.SetField(pet.FieldAptHp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAptHp(); ok {
		_spec.AddField(pet.FieldAptHp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AptAtk(); ok {
		_spec.SetField(pet.FieldAptAtk, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAptAtk(); ok {
		_spec.AddField(pet.FieldAptAtk, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AptDef(); ok {
		_spec.SetField(pet.FieldAptDef, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAptDef(); ok {
		_spec.AddField(pet.FieldAptDef, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AptSpd(); ok {
		_spec.SetField(pet.FieldAptSpd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAptSpd(); ok {
		_spec.AddField(pet.FieldAptSpd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AptInt(); ok {
		_spec.SetField(pet.FieldAptInt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAptInt(); ok {
		_spec.AddField(pet.FieldAptInt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SkillSlots(); ok {
		_spec.SetField(pet.FieldSkillSlots, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSkillSlots(); ok {
		_spec.AddField(pet.FieldSkillSlots, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Personality(); ok {
		_spec.SetField(pet.FieldPersonality, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(pet.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(pet.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Exp(); ok {
		_spec.SetField(pet.FieldExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExp(); ok {
		_spec.AddField(pet.FieldExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Mood(); ok {
		_spec.SetField(pet.FieldMood, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMood(); ok {
		_spec.AddField(pet.FieldMood, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Energy(); ok {
		_spec.SetField(pet.FieldEnergy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEnergy(); ok {
		_spec.AddField(pet.FieldEnergy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(pet.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaiBalance(); ok {
		_spec.SetField(pet.FieldTaiBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTaiBalance(); ok {
		_spec.AddField(pet.FieldTaiBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(pet.FieldImageURL, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(pet.FieldImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.IsOnChain(); ok {
		_spec.SetField(pet.FieldIsOnChain, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ChainNftAddress(); ok {
		_spec.SetField(pet.FieldChainNftAddress, field.TypeString, value)
	}
	if _u.mutation.ChainNftAddressCleared() {
		_spec.ClearField(pet.FieldChainNftAddress, field.TypeString)
	}
	if value, ok := _u.mutation.ChainMintedAt(); ok {
		_spec.SetField(pet.FieldChainMintedAt, field.TypeTime, value)
	}
	if _u.mutation.ChainMintedAtCleared() {
		_spec.ClearField(pet.FieldChainMintedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BreedCooldownUntil(); ok {
		_spec.SetField(pet.FieldBreedCooldownUntil, field.TypeTime, value)
	}
	if _u.mutation.BreedCooldownUntilCleared() {
		_spec.ClearField(pet.FieldBreedCooldownUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.TotalEarnedTai(); ok {
		_spec.SetField(pet.FieldTotalEarnedTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalEarnedTai(); ok {
		_spec.AddField(pet.FieldTotalEarnedTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalSpentTai(); ok {
		_spec.SetField(pet.FieldTotalSpentTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalSpentTai(); ok {
		_spec.AddField(pet.FieldTotalSpentTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalTokensUsed(); ok {
		_spec.SetField(pet.FieldTotalTokensUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokensUsed(); ok {
		_spec.AddField(pet.FieldTotalTokensUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTasksDone(); ok {
		_spec.SetField(pet.FieldTotalTasksDone, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalTasksDone(); ok {
		_spec.AddField(pet.FieldTotalTasksDone, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pet.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pet.OwnerTable,
			Columns: []string{pet.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pet.OwnerTable,
			Columns: []string{pet.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pet.SkillsTable,
			Columns: []string{pet.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(petskill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSkillsIDs(); len(nodes) > 0 && !_u.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pet.SkillsTable,
			Columns: []string{pet.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(petskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pet.SkillsTable,
			Columns: []string{pet.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(petskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Pet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
