// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/pet"
	"github.com/tii-mom/tai-protocol/backend/ent/petskill"
	"github.com/tii-mom/tai-protocol/backend/ent/user"
)

// PetCreate is the builder for creating a Pet entity.
type PetCreate struct {
	config
	mutation *PetMutation
	hooks    []Hook
}

// SetOwnerID sets the "owner_id" field.
func (_c *PetCreate) SetOwnerID(v uuid.UUID) *PetCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PetCreate) SetName(v string) *PetCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *PetCreate) SetNillableName(v *string) *PetCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetSpecies sets the "species" field.
func (_c *PetCreate) SetSpecies(v string) *PetCreate {
	_c.mutation.SetSpecies(v)
	return _c
}

// SetQuality sets the "quality" field.
func (_c *PetCreate) SetQuality(v string) *PetCreate {
	_c.mutation.SetQuality(v)
	return _c
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_c *PetCreate) SetNillableQuality(v *string) *PetCreate {
	if v != nil {
		_c.SetQuality(*v)
	}
	return _c
}

// SetGeneration sets the "generation" field.
func (_c *PetCreate) SetGeneration(v int) *PetCreate {
	_c.mutation.SetGeneration(v)
	return _c
}

// SetNillableGeneration sets the "generation" field if the given value is not nil.
func (_c *PetCreate) SetNillableGeneration(v *int) *PetCreate {
	if v != nil {
		_c.SetGeneration(*v)
	}
	return _c
}

// SetGrowthRate sets the "growth_rate" field.
func (_c *PetCreate) SetGrowthRate(v float64) *PetCreate {
	_c.mutation.SetGrowthRate(v)
	return _c
}

// SetNillableGrowthRate sets the "growth_rate" field if the given value is not nil.
func (_c *PetCreate) SetNillableGrowthRate(v *float64) *PetCreate {
	if v != nil {
		_c.SetGrowthRate(*v)
	}
	return _c
}

// SetAptHp sets the "apt_hp" field.
func (_c *PetCreate) SetAptHp(v int) *PetCreate {
	_c.mutation.SetAptHp(v)
	return _c
}

// SetNillableAptHp sets the "apt_hp" field if the given value is not nil.
func (_c *PetCreate) SetNillableAptHp(v *int) *PetCreate {
	if v != nil {
		_c.SetAptHp(*v)
	}
	return _c
}

// SetAptAtk sets the "apt_atk" field.
func (_c *PetCreate) SetAptAtk(v int) *PetCreate {
	_c.mutation.SetAptAtk(v)
	return _c
}

// SetNillableAptAtk sets the "apt_atk" field if the given value is not nil.
func (_c *PetCreate) SetNillableAptAtk(v *int) *PetCreate {
	if v != nil {
		_c.SetAptAtk(*v)
	}
	return _c
}

// SetAptDef sets the "apt_def" field.
func (_c *PetCreate) SetAptDef(v int) *PetCreate {
	_c.mutation.SetAptDef(v)
	return _c
}

// SetNillableAptDef sets the "apt_def" field if the given value is not nil.
func (_c *PetCreate) SetNillableAptDef(v *int) *PetCreate {
	if v != nil {
		_c.SetAptDef(*v)
	}
	return _c
}

// SetAptSpd sets the "apt_spd" field.
func (_c *PetCreate) SetAptSpd(v int) *PetCreate {
	_c.mutation.SetAptSpd(v)
	return _c
}

// SetNillableAptSpd sets the "apt_spd" field if the given value is not nil.
func (_c *PetCreate) SetNillableAptSpd(v *int) *PetCreate {
	if v != nil {
		_c.SetAptSpd(*v)
	}
	return _c
}

// SetAptInt sets the "apt_int" field.
func (_c *PetCreate) SetAptInt(v int) *PetCreate {
	_c.mutation.SetAptInt(v)
	return _c
}

// SetNillableAptInt sets the "apt_int" field if the given value is not nil.
func (_c *PetCreate) SetNillableAptInt(v *int) *PetCreate {
	if v != nil {
		_c.SetAptInt(*v)
	}
	return _c
}

// SetSkillSlots sets the "skill_slots" field.
func (_c *PetCreate) SetSkillSlots(v int) *PetCreate {
	_c.mutation.SetSkillSlots(v)
	return _c
}

// SetNillableSkillSlots sets the "skill_slots" field if the given value is not nil.
func (_c *PetCreate) SetNillableSkillSlots(v *int) *PetCreate {
	if v != nil {
		_c.SetSkillSlots(*v)
	}
	return _c
}

// SetPersonality sets the "personality" field.
func (_c *PetCreate) SetPersonality(v string) *PetCreate {
	_c.mutation.SetPersonality(v)
	return _c
}

// SetNillablePersonality sets the "personality" field if the given value is not nil.
func (_c *PetCreate) SetNillablePersonality(v *string) *PetCreate {
	if v != nil {
		_c.SetPersonality(*v)
	}
	return _c
}

// SetLevel sets the "level" field.
func (_c *PetCreate) SetLevel(v int) *PetCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_c *PetCreate) SetNillableLevel(v *int) *PetCreate {
	if v != nil {
		_c.SetLevel(*v)
	}
	return _c
}

// SetExp sets the "exp" field.
func (_c *PetCreate) SetExp(v int64) *PetCreate {
	_c.mutation.SetExp(v)
	return _c
}

// SetNillableExp sets the "exp" field if the given value is not nil.
func (_c *PetCreate) SetNillableExp(v *int64) *PetCreate {
	if v != nil {
		_c.SetExp(*v)
	}
	return _c
}

// SetMood sets the "mood" field.
func (_c *PetCreate) SetMood(v int) *PetCreate {
	_c.mutation.SetMood(v)
	return _c
}

// SetNillableMood sets the "mood" field if the given value is not nil.
func (_c *PetCreate) SetNillableMood(v *int) *PetCreate {
	if v != nil {
		_c.SetMood(*v)
	}
	return _c
}

// SetEnergy sets the "energy" field.
func (_c *PetCreate) SetEnergy(v int) *PetCreate {
	_c.mutation.SetEnergy(v)
	return _c
}

// SetNillableEnergy sets the "energy" field if the given value is not nil.
func (_c *PetCreate) SetNillableEnergy(v *int) *PetCreate {
	if v != nil {
		_c.SetEnergy(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PetCreate) SetStatus(v string) *PetCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PetCreate) SetNillableStatus(v *string) *PetCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTaiBalance sets the "tai_balance" field.
func (_c *PetCreate) SetTaiBalance(v float64) *PetCreate {
	_c.mutation.SetTaiBalance(v)
	return _c
}

// SetNillableTaiBalance sets the "tai_balance" field if the given value is not nil.
func (_c *PetCreate) SetNillableTaiBalance(v *float64) *PetCreate {
	if v != nil {
		_c.SetTaiBalance(*v)
	}
	return _c
}

// SetImageURL sets the "image_url" field.
func (_c *PetCreate) SetImageURL(v string) *PetCreate {
	_c.mutation.SetImageURL(v)
	return _c
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_c *PetCreate) SetNillableImageURL(v *string) *PetCreate {
	if v != nil {
		_c.SetImageURL(*v)
	}
	return _c
}

// SetIsOnChain sets the "is_on_chain" field.
func (_c *PetCreate) SetIsOnChain(v bool) *PetCreate {
	_c.mutation.SetIsOnChain(v)
	return _c
}

// SetNillableIsOnChain sets the "is_on_chain" field if the given value is not nil.
func (_c *PetCreate) SetNillableIsOnChain(v *bool) *PetCreate {
	if v != nil {
		_c.SetIsOnChain(*v)
	}
	return _c
}

// SetChainNftAddress sets the "chain_nft_address" field.
func (_c *PetCreate) SetChainNftAddress(v string) *PetCreate {
	_c.mutation.SetChainNftAddress(v)
	return _c
}

// SetNillableChainNftAddress sets the "chain_nft_address" field if the given value is not nil.
func (_c *PetCreate) SetNillableChainNftAddress(v *string) *PetCreate {
	if v != nil {
		_c.SetChainNftAddress(*v)
	}
	return _c
}

// SetChainMintedAt sets the "chain_minted_at" field.
func (_c *PetCreate) SetChainMintedAt(v time.Time) *PetCreate {
	_c.mutation.SetChainMintedAt(v)
	return _c
}

// SetNillableChainMintedAt sets the "chain_minted_at" field if the given value is not nil.
func (_c *PetCreate) SetNillableChainMintedAt(v *time.Time) *PetCreate {
	if v != nil {
		_c.SetChainMintedAt(*v)
	}
	return _c
}

// SetBreedCooldownUntil sets the "breed_cooldown_until" field.
func (_c *PetCreate) SetBreedCooldownUntil(v time.Time) *PetCreate {
	_c.mutation.SetBreedCooldownUntil(v)
	return _c
}

// SetNillableBreedCooldownUntil sets the "breed_cooldown_until" field if the given value is not nil.
func (_c *PetCreate) SetNillableBreedCooldownUntil(v *time.Time) *PetCreate {
	if v != nil {
		_c.SetBreedCooldownUntil(*v)
	}
	return _c
}

// SetTotalEarnedTai sets the "total_earned_tai" field.
func (_c *PetCreate) SetTotalEarnedTai(v float64) *PetCreate {
	_c.mutation.SetTotalEarnedTai(v)
	return _c
}

// SetNillableTotalEarnedTai sets the "total_earned_tai" field if the given value is not nil.
func (_c *PetCreate) SetNillableTotalEarnedTai(v *float64) *PetCreate {
	if v != nil {
		_c.SetTotalEarnedTai(*v)
	}
	return _c
}

// SetTotalSpentTai sets the "total_spent_tai" field.
func (_c *PetCreate) SetTotalSpentTai(v float64) *PetCreate {
	_c.mutation.SetTotalSpentTai(v)
	return _c
}

// SetNillableTotalSpentTai sets the "total_spent_tai" field if the given value is not nil.
func (_c *PetCreate) SetNillableTotalSpentTai(v *float64) *PetCreate {
	if v != nil {
		_c.SetTotalSpentTai(*v)
	}
	return _c
}

// SetTotalTokensUsed sets the "total_tokens_used" field.
func (_c *PetCreate) SetTotalTokensUsed(v int64) *PetCreate {
	_c.mutation.SetTotalTokensUsed(v)
	return _c
}

// SetNillableTotalTokensUsed sets the "total_tokens_used" field if the given value is not nil.
func (_c *PetCreate) SetNillableTotalTokensUsed(v *int64) *PetCreate {
	if v != nil {
		_c.SetTotalTokensUsed(*v)
	}
	return _c
}

// SetTotalTasksDone sets the "total_tasks_done" field.
func (_c *PetCreate) SetTotalTasksDone(v int) *PetCreate {
	_c.mutation.SetTotalTasksDone(v)
	return _c
}

// SetNillableTotalTasksDone sets the "total_tasks_done" field if the given value is not nil.
func (_c *PetCreate) SetNillableTotalTasksDone(v *int) *PetCreate {
	if v != nil {
		_c.SetTotalTasksDone(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PetCreate) SetCreatedAt(v time.Time) *PetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PetCreate) SetNillableCreatedAt(v *time.Time) *PetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PetCreate) SetUpdatedAt(v time.Time) *PetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PetCreate) SetNillableUpdatedAt(v *time.Time) *PetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PetCreate) SetID(v uuid.UUID) *PetCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PetCreate) SetNillableID(v *uuid.UUID) *PetCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *PetCreate) SetOwner(v *User) *PetCreate {
	return _c.SetOwnerID(v.ID)
}

// AddSkillIDs adds the "skills" edge to the PetSkill entity by IDs.
func (_c *PetCreate) AddSkillIDs(ids ...uuid.UUID) *PetCreate {
	_c.mutation.AddSkillIDs(ids...)
	return _c
}

// AddSkills adds the "skills" edges to the PetSkill entity.
func (_c *PetCreate) AddSkills(v ...*PetSkill) *PetCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSkillIDs(ids...)
}

// Mutation returns the PetMutation object of the builder.
func (_c *PetCreate) Mutation() *PetMutation {
	return _c.mutation
}

// Save creates the Pet in the database.
func (_c *PetCreate) Save(ctx context.Context) (*Pet, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PetCreate) SaveX(ctx context.Context) *Pet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PetCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := pet.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Quality(); !ok {
		v := pet.DefaultQuality
		_c.mutation.SetQuality(v)
	}
	if _, ok := _c.mutation.Generation(); !ok {
		v := pet.DefaultGeneration
		_c.mutation.SetGeneration(v)
	}
	if _, ok := _c.mutation.GrowthRate(); !ok {
		v := pet.DefaultGrowthRate
		_c.mutation.SetGrowthRate(v)
	}
	if _, ok := _c.mutation.AptHp(); !ok {
		v := pet.DefaultAptHp
		_c.mutation.SetAptHp(v)
	}
	if _, ok := _c.mutation.AptAtk(); !ok {
		v := pet.DefaultAptAtk
		_c.mutation.SetAptAtk(v)
	}
	if _, ok := _c.mutation.AptDef(); !ok {
		v := pet.DefaultAptDef
		_c.mutation.SetAptDef(v)
	}
	if _, ok := _c.mutation.AptSpd(); !ok {
		v := pet.DefaultAptSpd
		_c.mutation.SetAptSpd(v)
	}
	if _, ok := _c.mutation.AptInt(); !ok {
		v := pet.DefaultAptInt
		_c.mutation.SetAptInt(v)
	}
	if _, ok := _c.mutation.SkillSlots(); !ok {
		v := pet.DefaultSkillSlots
		_c.mutation.SetSkillSlots(v)
	}
	if _, ok := _c.mutation.Personality(); !ok {
		v := pet.DefaultPersonality
		_c.mutation.SetPersonality(v)
	}
	if _, ok := _c.mutation.Level(); !ok {
		v := pet.DefaultLevel
		_c.mutation.SetLevel(v)
	}
	if _, ok := _c.mutation.Exp(); !ok {
		v := pet.DefaultExp
		_c.mutation.SetExp(v)
	}
	if _, ok := _c.mutation.Mood(); !ok {
		v := pet.DefaultMood
		_c.mutation.SetMood(v)
	}
	if _, ok := _c.mutation.Energy(); !ok {
		v := pet.DefaultEnergy
		_c.mutation.SetEnergy(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := pet.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TaiBalance(); !ok {
		v := pet.DefaultTaiBalance
		_c.mutation.SetTaiBalance(v)
	}
	if _, ok := _c.mutation.IsOnChain(); !ok {
		v := pet.DefaultIsOnChain
		_c.mutation.SetIsOnChain(v)
	}
	if _, ok := _c.mutation.TotalEarnedTai(); !ok {
		v := pet.DefaultTotalEarnedTai
		_c.mutation.SetTotalEarnedTai(v)
	}
	if _, ok := _c.mutation.TotalSpentTai(); !ok {
		v := pet.DefaultTotalSpentTai
		_c.mutation.SetTotalSpentTai(v)
	}
	if _, ok := _c.mutation.TotalTokensUsed(); !ok {
		v := pet.DefaultTotalTokensUsed
		_c.mutation.SetTotalTokensUsed(v)
	}
	if _, ok := _c.mutation.TotalTasksDone(); !ok {
		v := pet.DefaultTotalTasksDone
		_c.mutation.SetTotalTasksDone(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pet.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := pet.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := pet.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PetCreate) check() error {
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "Pet.owner_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Pet.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := pet.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Pet.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Species(); !ok {
		return &ValidationError{Name: "species", err: errors.New(`ent: missing required field "Pet.species"`)}
	}
	if v, ok := _c.mutation.Species(); ok {
		if err := pet.SpeciesValidator(v); err != nil {
			return &ValidationError{Name: "species", err: fmt.Errorf(`ent: validator failed for field "Pet.species": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quality(); !ok {
		return &ValidationError{Name: "quality", err: errors.New(`ent: missing required field "Pet.quality"`)}
	}
	if v, ok := _c.mutation.Quality(); ok {
		if err := pet.QualityValidator(v); err != nil {
			return &ValidationError{Name: "quality", err: fmt.Errorf(`ent: validator failed for field "Pet.quality": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Generation(); !ok {
		return &ValidationError{Name: "generation", err: errors.New(`ent: missing required field "Pet.generation"`)}
	}
	if _, ok := _c.mutation.GrowthRate(); !ok {
		return &ValidationError{Name: "growth_rate", err: errors.New(`ent: missing required field "Pet.growth_rate"`)}
	}
	if _, ok := _c.mutation.AptHp(); !ok {
		return &ValidationError{Name: "apt_hp", err: errors.New(`ent: missing required field "Pet.apt_hp"`)}
	}
	if _, ok := _c.mutation.AptAtk(); !ok {
		return &ValidationError{Name: "apt_atk", err: errors.New(`ent: missing required field "Pet.apt_atk"`)}
	}
	if _, ok := _c.mutation.AptDef(); !ok {
		return &ValidationError{Name: "apt_def", err: errors.New(`ent: missing required field "Pet.apt_def"`)}
	}
	if _, ok := _c.mutation.AptSpd(); !ok {
		return &ValidationError{Name: "apt_spd", err: errors.New(`ent: missing required field "Pet.apt_spd"`)}
	}
	if _, ok := _c.mutation.AptInt(); !ok {
		return &ValidationError{Name: "apt_int", err: errors.New(`ent: missing required field "Pet.apt_int"`)}
	}
	if _, ok := _c.mutation.SkillSlots(); !ok {
		return &ValidationError{Name: "skill_slots", err: errors.New(`ent: missing required field "Pet.skill_slots"`)}
	}
	if _, ok := _c.mutation.Personality(); !ok {
		return &ValidationError{Name: "personality", err: errors.New(`ent: missing required field "Pet.personality"`)}
	}
	if v, ok := _c.mutation.Personality(); ok {
		if err := pet.PersonalityValidator(v); err != nil {
			return &ValidationError{Name: "personality", err: fmt.Errorf(`ent: validator failed for field "Pet.personality": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "Pet.level"`)}
	}
	if _, ok := _c.mutation.Exp(); !ok {
		return &ValidationError{Name: "exp", err: errors.New(`ent: missing required field "Pet.exp"`)}
	}
	if _, ok := _c.mutation.Mood(); !ok {
		return &ValidationError{Name: "mood", err: errors.New(`ent: missing required field "Pet.mood"`)}
	}
	if _, ok := _c.mutation.Energy(); !ok {
		return &ValidationError{Name: "energy", err: errors.New(`ent: missing required field "Pet.energy"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Pet.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := pet.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Pet.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaiBalance(); !ok {
		return &ValidationError{Name: "tai_balance", err: errors.New(`ent: missing required field "Pet.tai_balance"`)}
	}
	if v, ok := _c.mutation.ImageURL(); ok {
		if err := pet.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "Pet.image_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsOnChain(); !ok {
		return &ValidationError{Name: "is_on_chain", err: errors.New(`ent: missing required field "Pet.is_on_chain"`)}
	}
	if v, ok := _c.mutation.ChainNftAddress(); ok {
		if err := pet.ChainNftAddressValidator(v); err != nil {
			return &ValidationError{Name: "chain_nft_address", err: fmt.Errorf(`ent: validator failed for field "Pet.chain_nft_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalEarnedTai(); !ok {
		return &ValidationError{Name: "total_earned_tai", err: errors.New(`ent: missing required field "Pet.total_earned_tai"`)}
	}
	if _, ok := _c.mutation.TotalSpentTai(); !ok {
		return &ValidationError{Name: "total_spent_tai", err: errors.New(`ent: missing required field "Pet.total_spent_tai"`)}
	}
	if _, ok := _c.mutation.TotalTokensUsed(); !ok {
		return &ValidationError{Name: "total_tokens_used", err: errors.New(`ent: missing required field "Pet.total_tokens_used"`)}
	}
	if _, ok := _c.mutation.TotalTasksDone(); !ok {
		return &ValidationError{Name: "total_tasks_done", err: errors.New(`ent: missing required field "Pet.total_tasks_done"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Pet.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Pet.updated_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Pet.owner"`)}
	}
	return nil
}

func (_c *PetCreate) sqlSave(ctx context.Context) (*Pet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PetCreate) createSpec() (*Pet, *sqlgraph.CreateSpec) {
	var (
		_node = &Pet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pet.Table, sqlgraph.NewFieldSpec(pet.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(pet.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Species(); ok {
		_spec.SetField(pet.FieldSpecies, field.TypeString, value)
		_node.Species = value
	}
	if value, ok := _c.mutation.Quality(); ok {
		_spec.SetField(pet.FieldQuality, field.TypeString, value)
		_node.Quality = value
	}
	if value, ok := _c.mutation.Generation(); ok {
		_spec.SetField(pet.FieldGeneration, field.TypeInt, value)
		_node.Generation = value
	}
	if value, ok := _c.mutation.GrowthRate(); ok {
		_spec.SetField(pet.FieldGrowthRate, field.TypeFloat64, value)
		_node.GrowthRate = value
	}
	if value, ok := _c.mutation.AptHp(); ok {
		_spec.SetField(pet.FieldAptHp, field.TypeInt, value)
		_node.AptHp = value
	}
	if value, ok := _c.mutation.AptAtk(); ok {
		_spec.SetField(pet.FieldAptAtk, field.TypeInt, value)
		_node.AptAtk = value
	}
	if value, ok := _c.mutation.AptDef(); ok {
		_spec.SetField(pet.FieldAptDef, field.TypeInt, value)
		_node.AptDef = value
	}
	if value, ok := _c.mutation.AptSpd(); ok {
		_spec.SetField(pet.FieldAptSpd, field.TypeInt, value)
		_node.AptSpd = value
	}
	if value, ok := _c.mutation.AptInt(); ok {
		_spec.SetField(pet.FieldAptInt, field.TypeInt, value)
		_node.AptInt = value
	}
	if value, ok := _c.mutation.SkillSlots(); ok {
		_spec.SetField(pet.FieldSkillSlots, field.TypeInt, value)
		_node.SkillSlots = value
	}
	if value, ok := _c.mutation.Personality(); ok {
		_spec.SetField(pet.FieldPersonality, field.TypeString, value)
		_node.Personality = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(pet.FieldLevel, field.TypeInt, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Exp(); ok {
		_spec.SetField(pet.FieldExp, field.TypeInt64, value)
		_node.Exp = value
	}
	if value, ok := _c.mutation.Mood(); ok {
		_spec.SetField(pet.FieldMood, field.TypeInt, value)
		_node.Mood = value
	}
	if value, ok := _c.mutation.Energy(); ok {
		_spec.SetField(pet.FieldEnergy, field.TypeInt, value)
		_node.Energy = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(pet.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TaiBalance(); ok {
		_spec.SetField(pet.FieldTaiBalance, field.TypeFloat64, value)
		_node.TaiBalance = value
	}
	if value, ok := _c.mutation.ImageURL(); ok {
		_spec.SetField(pet.FieldImageURL, field.TypeString, value)
		_node.ImageURL = value
	}
	if value, ok := _c.mutation.IsOnChain(); ok {
		_spec.SetField(pet.FieldIsOnChain, field.TypeBool, value)
		_node.IsOnChain = value
	}
	if value, ok := _c.mutation.ChainNftAddress(); ok {
		_spec.SetField(pet.FieldChainNftAddress, field.TypeString, value)
		_node.ChainNftAddress = &value
	}
	if value, ok := _c.mutation.ChainMintedAt(); ok {
		_spec.SetField(pet.FieldChainMintedAt, field.TypeTime, value)
		_node.ChainMintedAt = &value
	}
	if value, ok := _c.mutation.BreedCooldownUntil(); ok {
		_spec.SetField(pet.FieldBreedCooldownUntil, field.TypeTime, value)
		_node.BreedCooldownUntil = &value
	}
	if value, ok := _c.mutation.TotalEarnedTai(); ok {
		_spec.SetField(pet.FieldTotalEarnedTai, field.TypeFloat64, value)
		_node.TotalEarnedTai = value
	}
	if value, ok := _c.mutation.TotalSpentTai(); ok {
		_spec.SetField(pet.FieldTotalSpentTai, field.TypeFloat64, value)
		_node.TotalSpentTai = value
	}
	if value, ok := _c.mutation.TotalTokensUsed(); ok {
		_spec.SetField(pet.FieldTotalTokensUsed, field.TypeInt64, value)
		_node.TotalTokensUsed = value
	}
	if value, ok := _c.mutation.TotalTasksDone(); ok {
		_spec.SetField(pet.FieldTotalTasksDone, field.TypeInt, value)
		_node.TotalTasksDone = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pet.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pet.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pet.OwnerTable,
			Columns: []string{pet.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pet.SkillsTable,
			Columns: []string{pet.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(petskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PetCreateBulk is the builder for creating many Pet entities in bulk.
type PetCreateBulk struct {
	config
	err      error
	builders []*PetCreate
}

// Save creates the Pet entities in the database.
func (_c *PetCreateBulk) Save(ctx context.Context) ([]*Pet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Pet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PetCreateBulk) SaveX(ctx context.Context) []*Pet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
