// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/petskill"
	"github.com/tii-mom/tai-protocol/backend/ent/predicate"
)

// PetSkillUpdate is the builder for updating PetSkill entities.
type PetSkillUpdate struct {
	config
	hooks    []Hook
	mutation *PetSkillMutation
}

// Where appends a list predicates to the PetSkillUpdate builder.
func (_u *PetSkillUpdate) Where(ps ...predicate.PetSkill) *PetSkillUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPetID sets the "pet_id" field.
func (_u *PetSkillUpdate) SetPetID(v uuid.UUID) *PetSkillUpdate {
	_u.mutation.SetPetID(v)
	return _u
}

// SetNillablePetID sets the "pet_id" field if the given value is not nil.
func (_u *PetSkillUpdate) SetNillablePetID(v *uuid.UUID) *PetSkillUpdate {
	if v != nil {
		_u.SetPetID(*v)
	}
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *PetSkillUpdate) SetSkillID(v uuid.UUID) *PetSkillUpdate {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *PetSkillUpdate) SetNillableSkillID(v *uuid.UUID) *PetSkillUpdate {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetSlotIndex sets the "slot_index" field.
func (_u *PetSkillUpdate) SetSlotIndex(v int) *PetSkillUpdate {
	_u.mutation.ResetSlotIndex()
	_u.mutation.SetSlotIndex(v)
	return _u
}

// SetNillableSlotIndex sets the "slot_index" field if the given value is not nil.
func (_u *PetSkillUpdate) SetNillableSlotIndex(v *int) *PetSkillUpdate {
	if v != nil {
		_u.SetSlotIndex(*v)
	}
	return _u
}

// AddSlotIndex adds value to the "slot_index" field.
func (_u *PetSkillUpdate) AddSlotIndex(v int) *PetSkillUpdate {
	_u.mutation.AddSlotIndex(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *PetSkillUpdate) SetSource(v string) *PetSkillUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *PetSkillUpdate) SetNillableSource(v *string) *PetSkillUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetEquippedAt sets the "equipped_at" field.
func (_u *PetSkillUpdate) SetEquippedAt(v time.Time) *PetSkillUpdate {
	_u.mutation.SetEquippedAt(v)
	return _u
}

// SetNillableEquippedAt sets the "equipped_at" field if the given value is not nil.
func (_u *PetSkillUpdate) SetNillableEquippedAt(v *time.Time) *PetSkillUpdate {
	if v != nil {
		_u.SetEquippedAt(*v)
	}
	return _u
}

// Mutation returns the PetSkillMutation object of the builder.
func (_u *PetSkillUpdate) Mutation() *PetSkillMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PetSkillUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PetSkillUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PetSkillUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PetSkillUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PetSkillUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := petskill.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "PetSkill.source": %w`, err)}
		}
	}
	return nil
}

func (_u *PetSkillUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(petskill.Table, petskill.Columns, sqlgraph.NewFieldSpec(petskill.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PetID(); ok {
		_spec.SetField(petskill.FieldPetID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.SkillID(); ok {
		_spec.SetField(petskill.FieldSkillID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.SlotIndex(); ok {
		_spec.SetField(petskill.FieldSlotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSlotIndex(); ok {
		_spec.AddField(petskill.FieldSlotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(petskill.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.EquippedAt(); ok {
		_spec.SetField(petskill.FieldEquippedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{petskill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PetSkillUpdateOne is the builder for updating a single PetSkill entity.
type PetSkillUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PetSkillMutation
}

// SetPetID sets the "pet_id" field.
func (_u *PetSkillUpdateOne) SetPetID(v uuid.UUID) *PetSkillUpdateOne {
	_u.mutation.SetPetID(v)
	return _u
}

// SetNillablePetID sets the "pet_id" field if the given value is not nil.
func (_u *PetSkillUpdateOne) SetNillablePetID(v *uuid.UUID) *PetSkillUpdateOne {
	if v != nil {
		_u.SetPetID(*v)
	}
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *PetSkillUpdateOne) SetSkillID(v uuid.UUID) *PetSkillUpdateOne {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *PetSkillUpdateOne) SetNillableSkillID(v *uuid.UUID) *PetSkillUpdateOne {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetSlotIndex sets the "slot_index" field.
func (_u *PetSkillUpdateOne) SetSlotIndex(v int) *PetSkillUpdateOne {
	_u.mutation.ResetSlotIndex()
	_u.mutation.SetSlotIndex(v)
	return _u
}

// SetNillableSlotIndex sets the "slot_index" field if the given value is not nil.
func (_u *PetSkillUpdateOne) SetNillableSlotIndex(v *int) *PetSkillUpdateOne {
	if v != nil {
		_u.SetSlotIndex(*v)
	}
	return _u
}

// AddSlotIndex adds value to the "slot_index" field.
func (_u *PetSkillUpdateOne) AddSlotIndex(v int) *PetSkillUpdateOne {
	_u.mutation.AddSlotIndex(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *PetSkillUpdateOne) SetSource(v string) *PetSkillUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *PetSkillUpdateOne) SetNillableSource(v *string) *PetSkillUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetEquippedAt sets the "equipped_at" field.
func (_u *PetSkillUpdateOne) SetEquippedAt(v time.Time) *PetSkillUpdateOne {
	_u.mutation.SetEquippedAt(v)
	return _u
}

// SetNillableEquippedAt sets the "equipped_at" field if the given value is not nil.
func (_u *PetSkillUpdateOne) SetNillableEquippedAt(v *time.Time) *PetSkillUpdateOne {
	if v != nil {
		_u.SetEquippedAt(*v)
	}
	return _u
}

// Mutation returns the PetSkillMutation object of the builder.
func (_u *PetSkillUpdateOne) Mutation() *PetSkillMutation {
	return _u.mutation
}

// Where appends a list predicates to the PetSkillUpdate builder.
func (_u *PetSkillUpdateOne) Where(ps ...predicate.PetSkill) *PetSkillUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PetSkillUpdateOne) Select(field string, fields ...string) *PetSkillUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PetSkill entity.
func (_u *PetSkillUpdateOne) Save(ctx context.Context) (*PetSkill, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PetSkillUpdateOne) SaveX(ctx context.Context) *PetSkill {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PetSkillUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PetSkillUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PetSkillUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := petskill.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "PetSkill.source": %w`, err)}
		}
	}
	return nil
}

func (_u *PetSkillUpdateOne) sqlSave(ctx context.Context) (_node *PetSkill, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(petskill.Table, petskill.Columns, sqlgraph.NewFieldSpec(petskill.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PetSkill.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, petskill.FieldID)
		for _, f := range fields {
			if !petskill.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != petskill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PetID(); ok {
		_spec.SetField(petskill.FieldPetID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.SkillID(); ok {
		_spec.SetField(petskill.FieldSkillID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.SlotIndex(); ok {
		_spec.SetField(petskill.FieldSlotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSlotIndex(); ok {
		_spec.AddField(petskill.FieldSlotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(petskill.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.EquippedAt(); ok {
		_spec.SetField(petskill.FieldEquippedAt, field.TypeTime, value)
	}
	_node = &PetSkill{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{petskill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
