// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/petskill"
)

// PetSkill is the model entity for the PetSkill schema.
type PetSkill struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PetID holds the value of the "pet_id" field.
	PetID uuid.UUID `json:"pet_id,omitempty"`
	// SkillID holds the value of the "skill_id" field.
	SkillID uuid.UUID `json:"skill_id,omitempty"`
	// SlotIndex holds the value of the "slot_index" field.
	SlotIndex int `json:"slot_index,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// EquippedAt holds the value of the "equipped_at" field.
	EquippedAt   time.Time `json:"equipped_at,omitempty"`
	pet_skills   *uuid.UUID
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PetSkill) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case petskill.FieldSlotIndex:
			values[i] = new(sql.NullInt64)
		case petskill.FieldSource:
			values[i] = new(sql.NullString)
		case petskill.FieldEquippedAt:
			values[i] = new(sql.NullTime)
		case petskill.FieldID, petskill.FieldPetID, petskill.FieldSkillID:
			values[i] = new(uuid.UUID)
		case petskill.ForeignKeys[0]: // pet_skills
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PetSkill fields.
func (_m *PetSkill) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case petskill.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case petskill.FieldPetID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field pet_id", values[i])
			} else if value != nil {
				_m.PetID = *value
			}
		case petskill.FieldSkillID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field skill_id", values[i])
			} else if value != nil {
				_m.SkillID = *value
			}
		case petskill.FieldSlotIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field slot_index", values[i])
			} else if value.Valid {
				_m.SlotIndex = int(value.Int64)
			}
		case petskill.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case petskill.FieldEquippedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field equipped_at", values[i])
			} else if value.Valid {
				_m.EquippedAt = value.Time
			}
		case petskill.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field pet_skills", values[i])
			} else if value.Valid {
				_m.pet_skills = new(uuid.UUID)
				*_m.pet_skills = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PetSkill.
// This includes values selected through modifiers, order, etc.
func (_m *PetSkill) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PetSkill.
// Note that you need to call PetSkill.Unwrap() before calling this method if this PetSkill
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PetSkill) Update() *PetSkillUpdateOne {
	return NewPetSkillClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PetSkill entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PetSkill) Unwrap() *PetSkill {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PetSkill is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PetSkill) String() string {
	var builder strings.Builder
	builder.WriteString("PetSkill(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("pet_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PetID))
	builder.WriteString(", ")
	builder.WriteString("skill_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkillID))
	builder.WriteString(", ")
	builder.WriteString("slot_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.SlotIndex))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("equipped_at=")
	builder.WriteString(_m.EquippedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PetSkills is a parsable slice of PetSkill.
type PetSkills []*PetSkill
