// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/petskill"
)

// PetSkillCreate is the builder for creating a PetSkill entity.
type PetSkillCreate struct {
	config
	mutation *PetSkillMutation
	hooks    []Hook
}

// SetPetID sets the "pet_id" field.
func (_c *PetSkillCreate) SetPetID(v uuid.UUID) *PetSkillCreate {
	_c.mutation.SetPetID(v)
	return _c
}

// SetSkillID sets the "skill_id" field.
func (_c *PetSkillCreate) SetSkillID(v uuid.UUID) *PetSkillCreate {
	_c.mutation.SetSkillID(v)
	return _c
}

// SetSlotIndex sets the "slot_index" field.
func (_c *PetSkillCreate) SetSlotIndex(v int) *PetSkillCreate {
	_c.mutation.SetSlotIndex(v)
	return _c
}

// SetNillableSlotIndex sets the "slot_index" field if the given value is not nil.
func (_c *PetSkillCreate) SetNillableSlotIndex(v *int) *PetSkillCreate {
	if v != nil {
		_c.SetSlotIndex(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *PetSkillCreate) SetSource(v string) *PetSkillCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *PetSkillCreate) SetNillableSource(v *string) *PetSkillCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetEquippedAt sets the "equipped_at" field.
func (_c *PetSkillCreate) SetEquippedAt(v time.Time) *PetSkillCreate {
	_c.mutation.SetEquippedAt(v)
	return _c
}

// SetNillableEquippedAt sets the "equipped_at" field if the given value is not nil.
func (_c *PetSkillCreate) SetNillableEquippedAt(v *time.Time) *PetSkillCreate {
	if v != nil {
		_c.SetEquippedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PetSkillCreate) SetID(v uuid.UUID) *PetSkillCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PetSkillCreate) SetNillableID(v *uuid.UUID) *PetSkillCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PetSkillMutation object of the builder.
func (_c *PetSkillCreate) Mutation() *PetSkillMutation {
	return _c.mutation
}

// Save creates the PetSkill in the database.
func (_c *PetSkillCreate) Save(ctx context.Context) (*PetSkill, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PetSkillCreate) SaveX(ctx context.Context) *PetSkill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PetSkillCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PetSkillCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PetSkillCreate) defaults() {
	if _, ok := _c.mutation.SlotIndex(); !ok {
		v := petskill.DefaultSlotIndex
		_c.mutation.SetSlotIndex(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := petskill.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.EquippedAt(); !ok {
		v := petskill.DefaultEquippedAt()
		_c.mutation.SetEquippedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := petskill.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PetSkillCreate) check() error {
	if _, ok := _c.mutation.PetID(); !ok {
		return &ValidationError{Name: "pet_id", err: errors.New(`ent: missing required field "PetSkill.pet_id"`)}
	}
	if _, ok := _c.mutation.SkillID(); !ok {
		return &ValidationError{Name: "skill_id", err: errors.New(`ent: missing required field "PetSkill.skill_id"`)}
	}
	if _, ok := _c.mutation.SlotIndex(); !ok {
		return &ValidationError{Name: "slot_index", err: errors.New(`ent: missing required field "PetSkill.slot_index"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "PetSkill.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := petskill.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "PetSkill.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EquippedAt(); !ok {
		return &ValidationError{Name: "equipped_at", err: errors.New(`ent: missing required field "PetSkill.equipped_at"`)}
	}
	return nil
}

func (_c *PetSkillCreate) sqlSave(ctx context.Context) (*PetSkill, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PetSkillCreate) createSpec() (*PetSkill, *sqlgraph.CreateSpec) {
	var (
		_node = &PetSkill{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(petskill.Table, sqlgraph.NewFieldSpec(petskill.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PetID(); ok {
		_spec.SetField(petskill.FieldPetID, field.TypeUUID, value)
		_node.PetID = value
	}
	if value, ok := _c.mutation.SkillID(); ok {
		_spec.SetField(petskill.FieldSkillID, field.TypeUUID, value)
		_node.SkillID = value
	}
	if value, ok := _c.mutation.SlotIndex(); ok {
		_spec.SetField(petskill.FieldSlotIndex, field.TypeInt, value)
		_node.SlotIndex = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(petskill.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.EquippedAt(); ok {
		_spec.SetField(petskill.FieldEquippedAt, field.TypeTime, value)
		_node.EquippedAt = value
	}
	return _node, _spec
}

// PetSkillCreateBulk is the builder for creating many PetSkill entities in bulk.
type PetSkillCreateBulk struct {
	config
	err      error
	builders []*PetSkillCreate
}

// Save creates the PetSkill entities in the database.
func (_c *PetSkillCreateBulk) Save(ctx context.Context) ([]*PetSkill, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PetSkill, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PetSkillMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PetSkillCreateBulk) SaveX(ctx context.Context) []*PetSkill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PetSkillCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PetSkillCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
