// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/bounty"
	"github.com/tii-mom/tai-protocol/backend/ent/guild"
	"github.com/tii-mom/tai-protocol/backend/ent/order"
	"github.com/tii-mom/tai-protocol/backend/ent/pet"
	"github.com/tii-mom/tai-protocol/backend/ent/petskill"
	"github.com/tii-mom/tai-protocol/backend/ent/schema"
	"github.com/tii-mom/tai-protocol/backend/ent/skill"
	"github.com/tii-mom/tai-protocol/backend/ent/trade"
	"github.com/tii-mom/tai-protocol/backend/ent/usagelog"
	"github.com/tii-mom/tai-protocol/backend/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bountyFields := schema.Bounty{}.Fields()
	_ = bountyFields
	// bountyDescTitle is the schema descriptor for title field.
	bountyDescTitle := bountyFields[1].Descriptor()
	// bounty.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	bounty.TitleValidator = bountyDescTitle.Validators[0].(func(string) error)
	// bountyDescPublisherID is the schema descriptor for publisher_id field.
	bountyDescPublisherID := bountyFields[3].Descriptor()
	// bounty.PublisherIDValidator is a validator for the "publisher_id" field. It is called by the builders before save.
	bounty.PublisherIDValidator = bountyDescPublisherID.Validators[0].(func(string) error)
	// bountyDescRewardTai is the schema descriptor for reward_tai field.
	bountyDescRewardTai := bountyFields[7].Descriptor()
	// bounty.DefaultRewardTai holds the default value on creation for the reward_tai field.
	bounty.DefaultRewardTai = bountyDescRewardTai.Default.(float64)
	// bountyDescCreatedAt is the schema descriptor for created_at field.
	bountyDescCreatedAt := bountyFields[9].Descriptor()
	// bounty.DefaultCreatedAt holds the default value on creation for the created_at field.
	bounty.DefaultCreatedAt = bountyDescCreatedAt.Default.(func() time.Time)
	// bountyDescID is the schema descriptor for id field.
	bountyDescID := bountyFields[0].Descriptor()
	// bounty.DefaultID holds the default value on creation for the id field.
	bounty.DefaultID = bountyDescID.Default.(func() uuid.UUID)
	guildFields := schema.Guild{}.Fields()
	_ = guildFields
	// guildDescName is the schema descriptor for name field.
	guildDescName := guildFields[1].Descriptor()
	// guild.NameValidator is a validator for the "name" field. It is called by the builders before save.
	guild.NameValidator = guildDescName.Validators[0].(func(string) error)
	// guildDescLevel is the schema descriptor for level field.
	guildDescLevel := guildFields[3].Descriptor()
	// guild.DefaultLevel holds the default value on creation for the level field.
	guild.DefaultLevel = guildDescLevel.Default.(int)
	// guildDescReputation is the schema descriptor for reputation field.
	guildDescReputation := guildFields[4].Descriptor()
	// guild.DefaultReputation holds the default value on creation for the reputation field.
	guild.DefaultReputation = guildDescReputation.Default.(int64)
	// guildDescMemberCount is the schema descriptor for member_count field.
	guildDescMemberCount := guildFields[5].Descriptor()
	// guild.DefaultMemberCount holds the default value on creation for the member_count field.
	guild.DefaultMemberCount = guildDescMemberCount.Default.(int)
	// guildDescMaxMembers is the schema descriptor for max_members field.
	guildDescMaxMembers := guildFields[6].Descriptor()
	// guild.DefaultMaxMembers holds the default value on creation for the max_members field.
	guild.DefaultMaxMembers = guildDescMaxMembers.Default.(int)
	// guildDescSeasonRank is the schema descriptor for season_rank field.
	guildDescSeasonRank := guildFields[7].Descriptor()
	// guild.DefaultSeasonRank holds the default value on creation for the season_rank field.
	guild.DefaultSeasonRank = guildDescSeasonRank.Default.(int)
	// guildDescCreatedAt is the schema descriptor for created_at field.
	guildDescCreatedAt := guildFields[8].Descriptor()
	// guild.DefaultCreatedAt holds the default value on creation for the created_at field.
	guild.DefaultCreatedAt = guildDescCreatedAt.Default.(func() time.Time)
	// guildDescID is the schema descriptor for id field.
	guildDescID := guildFields[0].Descriptor()
	// guild.DefaultID holds the default value on creation for the id field.
	guild.DefaultID = guildDescID.Default.(func() uuid.UUID)
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescItemType is the schema descriptor for item_type field.
	orderDescItemType := orderFields[2].Descriptor()
	// order.ItemTypeValidator is a validator for the "item_type" field. It is called by the builders before save.
	order.ItemTypeValidator = orderDescItemType.Validators[0].(func(string) error)
	// orderDescSide is the schema descriptor for side field.
	orderDescSide := orderFields[4].Descriptor()
	// order.SideValidator is a validator for the "side" field. It is called by the builders before save.
	order.SideValidator = orderDescSide.Validators[0].(func(string) error)
	// orderDescCurrency is the schema descriptor for currency field.
	orderDescCurrency := orderFields[6].Descriptor()
	// order.DefaultCurrency holds the default value on creation for the currency field.
	order.DefaultCurrency = orderDescCurrency.Default.(string)
	// order.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	order.CurrencyValidator = orderDescCurrency.Validators[0].(func(string) error)
	// orderDescStatus is the schema descriptor for status field.
	orderDescStatus := orderFields[7].Descriptor()
	// order.DefaultStatus holds the default value on creation for the status field.
	order.DefaultStatus = orderDescStatus.Default.(string)
	// order.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	order.StatusValidator = orderDescStatus.Validators[0].(func(string) error)
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderFields[10].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescID is the schema descriptor for id field.
	orderDescID := orderFields[0].Descriptor()
	// order.DefaultID holds the default value on creation for the id field.
	order.DefaultID = orderDescID.Default.(func() uuid.UUID)
	petFields := schema.Pet{}.Fields()
	_ = petFields
	// petDescName is the schema descriptor for name field.
	petDescName := petFields[2].Descriptor()
	// pet.DefaultName holds the default value on creation for the name field.
	pet.DefaultName = petDescName.Default.(string)
	// pet.NameValidator is a validator for the "name" field. It is called by the builders before save.
	pet.NameValidator = petDescName.Validators[0].(func(string) error)
	// petDescSpecies is the schema descriptor for species field.
	petDescSpecies := petFields[3].Descriptor()
	// pet.SpeciesValidator is a validator for the "species" field. It is called by the builders before save.
	pet.SpeciesValidator = petDescSpecies.Validators[0].(func(string) error)
	// petDescQuality is the schema descriptor for quality field.
	petDescQuality := petFields[4].Descriptor()
	// pet.DefaultQuality holds the default value on creation for the quality field.
	pet.DefaultQuality = petDescQuality.Default.(string)
	// pet.QualityValidator is a validator for the "quality" field. It is called by the builders before save.
	pet.QualityValidator = petDescQuality.Validators[0].(func(string) error)
	// petDescGeneration is the schema descriptor for generation field.
	petDescGeneration := petFields[5].Descriptor()
	// pet.DefaultGeneration holds the default value on creation for the generation field.
	pet.DefaultGeneration = petDescGeneration.Default.(int)
	// petDescGrowthRate is the schema descriptor for growth_rate field.
	petDescGrowthRate := petFields[6].Descriptor()
	// pet.DefaultGrowthRate holds the default value on creation for the growth_rate field.
	pet.DefaultGrowthRate = petDescGrowthRate.Default.(float64)
	// petDescAptHp is the schema descriptor for apt_hp field.
	petDescAptHp := petFields[7].Descriptor()
	// pet.DefaultAptHp holds the default value on creation for the apt_hp field.
	pet.DefaultAptHp = petDescAptHp.Default.(int)
	// petDescAptAtk is the schema descriptor for apt_atk field.
	petDescAptAtk := petFields[8].Descriptor()
	// pet.DefaultAptAtk holds the default value on creation for the apt_atk field.
	pet.DefaultAptAtk = petDescAptAtk.Default.(int)
	// petDescAptDef is the schema descriptor for apt_def field.
	petDescAptDef := petFields[9].Descriptor()
	// pet.DefaultAptDef holds the default value on creation for the apt_def field.
	pet.DefaultAptDef = petDescAptDef.Default.(int)
	// petDescAptSpd is the schema descriptor for apt_spd field.
	petDescAptSpd := petFields[10].Descriptor()
	// pet.DefaultAptSpd holds the default value on creation for the apt_spd field.
	pet.DefaultAptSpd = petDescAptSpd.Default.(int)
	// petDescAptInt is the schema descriptor for apt_int field.
	petDescAptInt := petFields[11].Descriptor()
	// pet.DefaultAptInt holds the default value on creation for the apt_int field.
	pet.DefaultAptInt = petDescAptInt.Default.(int)
	// petDescSkillSlots is the schema descriptor for skill_slots field.
	petDescSkillSlots := petFields[12].Descriptor()
	// pet.DefaultSkillSlots holds the default value on creation for the skill_slots field.
	pet.DefaultSkillSlots = petDescSkillSlots.Default.(int)
	// petDescPersonality is the schema descriptor for personality field.
	petDescPersonality := petFields[13].Descriptor()
	// pet.DefaultPersonality holds the default value on creation for the personality field.
	pet.DefaultPersonality = petDescPersonality.Default.(string)
	// pet.PersonalityValidator is a validator for the "personality" field. It is called by the builders before save.
	pet.PersonalityValidator = petDescPersonality.Validators[0].(func(string) error)
	// petDescLevel is the schema descriptor for level field.
	petDescLevel := petFields[14].Descriptor()
	// pet.DefaultLevel holds the default value on creation for the level field.
	pet.DefaultLevel = petDescLevel.Default.(int)
	// petDescExp is the schema descriptor for exp field.
	petDescExp := petFields[15].Descriptor()
	// pet.DefaultExp holds the default value on creation for the exp field.
	pet.DefaultExp = petDescExp.Default.(int64)
	// petDescMood is the schema descriptor for mood field.
	petDescMood := petFields[16].Descriptor()
	// pet.DefaultMood holds the default value on creation for the mood field.
	pet.DefaultMood = petDescMood.Default.(int)
	// petDescEnergy is the schema descriptor for energy field.
	petDescEnergy := petFields[17].Descriptor()
	// pet.DefaultEnergy holds the default value on creation for the energy field.
	pet.DefaultEnergy = petDescEnergy.Default.(int)
	// petDescStatus is the schema descriptor for status field.
	petDescStatus := petFields[18].Descriptor()
	// pet.DefaultStatus holds the default value on creation for the status field.
	pet.DefaultStatus = petDescStatus.Default.(string)
	// pet.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	pet.StatusValidator = petDescStatus.Validators[0].(func(string) error)
	// petDescTaiBalance is the schema descriptor for tai_balance field.
	petDescTaiBalance := petFields[19].Descriptor()
	// pet.DefaultTaiBalance holds the default value on creation for the tai_balance field.
	pet.DefaultTaiBalance = petDescTaiBalance.Default.(float64)
	// petDescImageURL is the schema descriptor for image_url field.
	petDescImageURL := petFields[20].Descriptor()
	// pet.ImageURLValidator is a validator for the "image_url" field. It is called by the builders before save.
	pet.ImageURLValidator = petDescImageURL.Validators[0].(func(string) error)
	// petDescIsOnChain is the schema descriptor for is_on_chain field.
	petDescIsOnChain := petFields[21].Descriptor()
	// pet.DefaultIsOnChain holds the default value on creation for the is_on_chain field.
	pet.DefaultIsOnChain = petDescIsOnChain.Default.(bool)
	// petDescChainNftAddress is the schema descriptor for chain_nft_address field.
	petDescChainNftAddress := petFields[22].Descriptor()
	// pet.ChainNftAddressValidator is a validator for the "chain_nft_address" field. It is called by the builders before save.
	pet.ChainNftAddressValidator = petDescChainNftAddress.Validators[0].(func(string) error)
	// petDescTotalEarnedTai is the schema descriptor for total_earned_tai field.
	petDescTotalEarnedTai := petFields[25].Descriptor()
	// pet.DefaultTotalEarnedTai holds the default value on creation for the total_earned_tai field.
	pet.DefaultTotalEarnedTai = petDescTotalEarnedTai.Default.(float64)
	// petDescTotalSpentTai is the schema descriptor for total_spent_tai field.
	petDescTotalSpentTai := petFields[26].Descriptor()
	// pet.DefaultTotalSpentTai holds the default value on creation for the total_spent_tai field.
	pet.DefaultTotalSpentTai = petDescTotalSpentTai.Default.(float64)
	// petDescTotalTokensUsed is the schema descriptor for total_tokens_used field.
	petDescTotalTokensUsed := petFields[27].Descriptor()
	// pet.DefaultTotalTokensUsed holds the default value on creation for the total_tokens_used field.
	pet.DefaultTotalTokensUsed = petDescTotalTokensUsed.Default.(int64)
	// petDescTotalTasksDone is the schema descriptor for total_tasks_done field.
	petDescTotalTasksDone := petFields[28].Descriptor()
	// pet.DefaultTotalTasksDone holds the default value on creation for the total_tasks_done field.
	pet.DefaultTotalTasksDone = petDescTotalTasksDone.Default.(int)
	// petDescCreatedAt is the schema descriptor for created_at field.
	petDescCreatedAt := petFields[29].Descriptor()
	// pet.DefaultCreatedAt holds the default value on creation for the created_at field.
	pet.DefaultCreatedAt = petDescCreatedAt.Default.(func() time.Time)
	// petDescUpdatedAt is the schema descriptor for updated_at field.
	petDescUpdatedAt := petFields[30].Descriptor()
	// pet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pet.DefaultUpdatedAt = petDescUpdatedAt.Default.(func() time.Time)
	// pet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pet.UpdateDefaultUpdatedAt = petDescUpdatedAt.UpdateDefault.(func() time.Time)
	// petDescID is the schema descriptor for id field.
	petDescID := petFields[0].Descriptor()
	// pet.DefaultID holds the default value on creation for the id field.
	pet.DefaultID = petDescID.Default.(func() uuid.UUID)
	petskillFields := schema.PetSkill{}.Fields()
	_ = petskillFields
	// petskillDescSlotIndex is the schema descriptor for slot_index field.
	petskillDescSlotIndex := petskillFields[3].Descriptor()
	// petskill.DefaultSlotIndex holds the default value on creation for the slot_index field.
	petskill.DefaultSlotIndex = petskillDescSlotIndex.Default.(int)
	// petskillDescSource is the schema descriptor for source field.
	petskillDescSource := petskillFields[4].Descriptor()
	// petskill.DefaultSource holds the default value on creation for the source field.
	petskill.DefaultSource = petskillDescSource.Default.(string)
	// petskill.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	petskill.SourceValidator = petskillDescSource.Validators[0].(func(string) error)
	// petskillDescEquippedAt is the schema descriptor for equipped_at field.
	petskillDescEquippedAt := petskillFields[5].Descriptor()
	// petskill.DefaultEquippedAt holds the default value on creation for the equipped_at field.
	petskill.DefaultEquippedAt = petskillDescEquippedAt.Default.(func() time.Time)
	// petskillDescID is the schema descriptor for id field.
	petskillDescID := petskillFields[0].Descriptor()
	// petskill.DefaultID holds the default value on creation for the id field.
	petskill.DefaultID = petskillDescID.Default.(func() uuid.UUID)
	skillFields := schema.Skill{}.Fields()
	_ = skillFields
	// skillDescName is the schema descriptor for name field.
	skillDescName := skillFields[1].Descriptor()
	// skill.NameValidator is a validator for the "name" field. It is called by the builders before save.
	skill.NameValidator = skillDescName.Validators[0].(func(string) error)
	// skillDescNameEn is the schema descriptor for name_en field.
	skillDescNameEn := skillFields[2].Descriptor()
	// skill.NameEnValidator is a validator for the "name_en" field. It is called by the builders before save.
	skill.NameEnValidator = skillDescNameEn.Validators[0].(func(string) error)
	// skillDescQuality is the schema descriptor for quality field.
	skillDescQuality := skillFields[3].Descriptor()
	// skill.DefaultQuality holds the default value on creation for the quality field.
	skill.DefaultQuality = skillDescQuality.Default.(string)
	// skill.QualityValidator is a validator for the "quality" field. It is called by the builders before save.
	skill.QualityValidator = skillDescQuality.Validators[0].(func(string) error)
	// skillDescCategory is the schema descriptor for category field.
	skillDescCategory := skillFields[4].Descriptor()
	// skill.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	skill.CategoryValidator = skillDescCategory.Validators[0].(func(string) error)
	// skillDescWeaponVisual is the schema descriptor for weapon_visual field.
	skillDescWeaponVisual := skillFields[6].Descriptor()
	// skill.WeaponVisualValidator is a validator for the "weapon_visual" field. It is called by the builders before save.
	skill.WeaponVisualValidator = skillDescWeaponVisual.Validators[0].(func(string) error)
	// skillDescPowerBonus is the schema descriptor for power_bonus field.
	skillDescPowerBonus := skillFields[7].Descriptor()
	// skill.DefaultPowerBonus holds the default value on creation for the power_bonus field.
	skill.DefaultPowerBonus = skillDescPowerBonus.Default.(int)
	// skillDescIsPlatformExclusive is the schema descriptor for is_platform_exclusive field.
	skillDescIsPlatformExclusive := skillFields[9].Descriptor()
	// skill.DefaultIsPlatformExclusive holds the default value on creation for the is_platform_exclusive field.
	skill.DefaultIsPlatformExclusive = skillDescIsPlatformExclusive.Default.(bool)
	// skillDescTotalSupply is the schema descriptor for total_supply field.
	skillDescTotalSupply := skillFields[10].Descriptor()
	// skill.DefaultTotalSupply holds the default value on creation for the total_supply field.
	skill.DefaultTotalSupply = skillDescTotalSupply.Default.(int)
	// skillDescRemaining is the schema descriptor for remaining field.
	skillDescRemaining := skillFields[11].Descriptor()
	// skill.DefaultRemaining holds the default value on creation for the remaining field.
	skill.DefaultRemaining = skillDescRemaining.Default.(int)
	// skillDescPriceTai is the schema descriptor for price_tai field.
	skillDescPriceTai := skillFields[12].Descriptor()
	// skill.DefaultPriceTai holds the default value on creation for the price_tai field.
	skill.DefaultPriceTai = skillDescPriceTai.Default.(float64)
	// skillDescCreatedAt is the schema descriptor for created_at field.
	skillDescCreatedAt := skillFields[13].Descriptor()
	// skill.DefaultCreatedAt holds the default value on creation for the created_at field.
	skill.DefaultCreatedAt = skillDescCreatedAt.Default.(func() time.Time)
	// skillDescID is the schema descriptor for id field.
	skillDescID := skillFields[0].Descriptor()
	// skill.DefaultID holds the default value on creation for the id field.
	skill.DefaultID = skillDescID.Default.(func() uuid.UUID)
	tradeFields := schema.Trade{}.Fields()
	_ = tradeFields
	// tradeDescItemType is the schema descriptor for item_type field.
	tradeDescItemType := tradeFields[1].Descriptor()
	// trade.ItemTypeValidator is a validator for the "item_type" field. It is called by the builders before save.
	trade.ItemTypeValidator = tradeDescItemType.Validators[0].(func(string) error)
	// tradeDescCurrency is the schema descriptor for currency field.
	tradeDescCurrency := tradeFields[6].Descriptor()
	// trade.DefaultCurrency holds the default value on creation for the currency field.
	trade.DefaultCurrency = tradeDescCurrency.Default.(string)
	// trade.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	trade.CurrencyValidator = tradeDescCurrency.Validators[0].(func(string) error)
	// tradeDescFeeAmount is the schema descriptor for fee_amount field.
	tradeDescFeeAmount := tradeFields[7].Descriptor()
	// trade.DefaultFeeAmount holds the default value on creation for the fee_amount field.
	trade.DefaultFeeAmount = tradeDescFeeAmount.Default.(float64)
	// tradeDescFeeRate is the schema descriptor for fee_rate field.
	tradeDescFeeRate := tradeFields[8].Descriptor()
	// trade.DefaultFeeRate holds the default value on creation for the fee_rate field.
	trade.DefaultFeeRate = tradeDescFeeRate.Default.(float64)
	// tradeDescIsMarketMaker is the schema descriptor for is_market_maker field.
	tradeDescIsMarketMaker := tradeFields[9].Descriptor()
	// trade.DefaultIsMarketMaker holds the default value on creation for the is_market_maker field.
	trade.DefaultIsMarketMaker = tradeDescIsMarketMaker.Default.(bool)
	// tradeDescChainTxHash is the schema descriptor for chain_tx_hash field.
	tradeDescChainTxHash := tradeFields[10].Descriptor()
	// trade.ChainTxHashValidator is a validator for the "chain_tx_hash" field. It is called by the builders before save.
	trade.ChainTxHashValidator = tradeDescChainTxHash.Validators[0].(func(string) error)
	// tradeDescCreatedAt is the schema descriptor for created_at field.
	tradeDescCreatedAt := tradeFields[11].Descriptor()
	// trade.DefaultCreatedAt holds the default value on creation for the created_at field.
	trade.DefaultCreatedAt = tradeDescCreatedAt.Default.(func() time.Time)
	// tradeDescID is the schema descriptor for id field.
	tradeDescID := tradeFields[0].Descriptor()
	// trade.DefaultID holds the default value on creation for the id field.
	trade.DefaultID = tradeDescID.Default.(func() uuid.UUID)
	usagelogFields := schema.UsageLog{}.Fields()
	_ = usagelogFields
	// usagelogDescPetID is the schema descriptor for pet_id field.
	usagelogDescPetID := usagelogFields[1].Descriptor()
	// usagelog.PetIDValidator is a validator for the "pet_id" field. It is called by the builders before save.
	usagelog.PetIDValidator = usagelogDescPetID.Validators[0].(func(string) error)
	// usagelogDescModel is the schema descriptor for model field.
	usagelogDescModel := usagelogFields[2].Descriptor()
	// usagelog.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	usagelog.ModelValidator = usagelogDescModel.Validators[0].(func(string) error)
	// usagelogDescPromptTokens is the schema descriptor for prompt_tokens field.
	usagelogDescPromptTokens := usagelogFields[3].Descriptor()
	// usagelog.DefaultPromptTokens holds the default value on creation for the prompt_tokens field.
	usagelog.DefaultPromptTokens = usagelogDescPromptTokens.Default.(int)
	// usagelogDescCompletionTokens is the schema descriptor for completion_tokens field.
	usagelogDescCompletionTokens := usagelogFields[4].Descriptor()
	// usagelog.DefaultCompletionTokens holds the default value on creation for the completion_tokens field.
	usagelog.DefaultCompletionTokens = usagelogDescCompletionTokens.Default.(int)
	// usagelogDescTaiCost is the schema descriptor for tai_cost field.
	usagelogDescTaiCost := usagelogFields[5].Descriptor()
	// usagelog.DefaultTaiCost holds the default value on creation for the tai_cost field.
	usagelog.DefaultTaiCost = usagelogDescTaiCost.Default.(float64)
	// usagelogDescCreatedAt is the schema descriptor for created_at field.
	usagelogDescCreatedAt := usagelogFields[7].Descriptor()
	// usagelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	usagelog.DefaultCreatedAt = usagelogDescCreatedAt.Default.(func() time.Time)
	// usagelogDescID is the schema descriptor for id field.
	usagelogDescID := usagelogFields[0].Descriptor()
	// usagelog.DefaultID holds the default value on creation for the id field.
	usagelog.DefaultID = usagelogDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescTgUsername is the schema descriptor for tg_username field.
	userDescTgUsername := userFields[2].Descriptor()
	// user.TgUsernameValidator is a validator for the "tg_username" field. It is called by the builders before save.
	user.TgUsernameValidator = userDescTgUsername.Validators[0].(func(string) error)
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[3].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = userDescFirstName.Validators[0].(func(string) error)
	// userDescWalletAddress is the schema descriptor for wallet_address field.
	userDescWalletAddress := userFields[4].Descriptor()
	// user.WalletAddressValidator is a validator for the "wallet_address" field. It is called by the builders before save.
	user.WalletAddressValidator = userDescWalletAddress.Validators[0].(func(string) error)
	// userDescBalanceTai is the schema descriptor for balance_tai field.
	userDescBalanceTai := userFields[5].Descriptor()
	// user.DefaultBalanceTai holds the default value on creation for the balance_tai field.
	user.DefaultBalanceTai = userDescBalanceTai.Default.(float64)
	// userDescBalanceUsdt is the schema descriptor for balance_usdt field.
	userDescBalanceUsdt := userFields[6].Descriptor()
	// user.DefaultBalanceUsdt holds the default value on creation for the balance_usdt field.
	user.DefaultBalanceUsdt = userDescBalanceUsdt.Default.(float64)
	// userDescFrozenBalance is the schema descriptor for frozen_balance field.
	userDescFrozenBalance := userFields[7].Descriptor()
	// user.DefaultFrozenBalance holds the default value on creation for the frozen_balance field.
	user.DefaultFrozenBalance = userDescFrozenBalance.Default.(float64)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[8].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// user.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	user.RoleValidator = userDescRole.Validators[0].(func(string) error)
	// userDescReferralCode is the schema descriptor for referral_code field.
	userDescReferralCode := userFields[9].Descriptor()
	// user.ReferralCodeValidator is a validator for the "referral_code" field. It is called by the builders before save.
	user.ReferralCodeValidator = userDescReferralCode.Validators[0].(func(string) error)
	// userDescInviteCount is the schema descriptor for invite_count field.
	userDescInviteCount := userFields[11].Descriptor()
	// user.DefaultInviteCount holds the default value on creation for the invite_count field.
	user.DefaultInviteCount = userDescInviteCount.Default.(int)
	// userDescTotalEarned is the schema descriptor for total_earned field.
	userDescTotalEarned := userFields[12].Descriptor()
	// user.DefaultTotalEarned holds the default value on creation for the total_earned field.
	user.DefaultTotalEarned = userDescTotalEarned.Default.(float64)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[14].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// user.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	user.StatusValidator = userDescStatus.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[15].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[16].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
