// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/skill"
)

// Skill is the model entity for the Skill schema.
type Skill struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// NameEn holds the value of the "name_en" field.
	NameEn string `json:"name_en,omitempty"`
	// Quality holds the value of the "quality" field.
	Quality string `json:"quality,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// WeaponVisual holds the value of the "weapon_visual" field.
	WeaponVisual string `json:"weapon_visual,omitempty"`
	// PowerBonus holds the value of the "power_bonus" field.
	PowerBonus int `json:"power_bonus,omitempty"`
	// TaskTypes holds the value of the "task_types" field.
	TaskTypes []string `json:"task_types,omitempty"`
	// IsPlatformExclusive holds the value of the "is_platform_exclusive" field.
	IsPlatformExclusive bool `json:"is_platform_exclusive,omitempty"`
	// TotalSupply holds the value of the "total_supply" field.
	TotalSupply int `json:"total_supply,omitempty"`
	// Remaining holds the value of the "remaining" field.
	Remaining int `json:"remaining,omitempty"`
	// PriceTai holds the value of the "price_tai" field.
	PriceTai float64 `json:"price_tai,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Skill) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case skill.FieldTaskTypes:
			values[i] = new([]byte)
		case skill.FieldIsPlatformExclusive:
			values[i] = new(sql.NullBool)
		case skill.FieldPriceTai:
			values[i] = new(sql.NullFloat64)
		case skill.FieldPowerBonus, skill.FieldTotalSupply, skill.FieldRemaining:
			values[i] = new(sql.NullInt64)
		case skill.FieldName, skill.FieldNameEn, skill.FieldQuality, skill.FieldCategory, skill.FieldDescription, skill.FieldWeaponVisual:
			values[i] = new(sql.NullString)
		case skill.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case skill.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Skill fields.
func (_m *Skill) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case skill.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case skill.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case skill.FieldNameEn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_en", values[i])
			} else if value.Valid {
				_m.NameEn = value.String
			}
		case skill.FieldQuality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quality", values[i])
			} else if value.Valid {
				_m.Quality = value.String
			}
		case skill.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case skill.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case skill.FieldWeaponVisual:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field weapon_visual", values[i])
			} else if value.Valid {
				_m.WeaponVisual = value.String
			}
		case skill.FieldPowerBonus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field power_bonus", values[i])
			} else if value.Valid {
				_m.PowerBonus = int(value.Int64)
			}
		case skill.FieldTaskTypes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field task_types", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TaskTypes); err != nil {
					return fmt.Errorf("unmarshal field task_types: %w", err)
				}
			}
		case skill.FieldIsPlatformExclusive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_platform_exclusive", values[i])
			} else if value.Valid {
				_m.IsPlatformExclusive = value.Bool
			}
		case skill.FieldTotalSupply:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_supply", values[i])
			} else if value.Valid {
				_m.TotalSupply = int(value.Int64)
			}
		case skill.FieldRemaining:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field remaining", values[i])
			} else if value.Valid {
				_m.Remaining = int(value.Int64)
			}
		case skill.FieldPriceTai:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price_tai", values[i])
			} else if value.Valid {
				_m.PriceTai = value.Float64
			}
		case skill.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Skill.
// This includes values selected through modifiers, order, etc.
func (_m *Skill) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Skill.
// Note that you need to call Skill.Unwrap() before calling this method if this Skill
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Skill) Update() *SkillUpdateOne {
	return NewSkillClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Skill entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Skill) Unwrap() *Skill {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Skill is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Skill) String() string {
	var builder strings.Builder
	builder.WriteString("Skill(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("name_en=")
	builder.WriteString(_m.NameEn)
	builder.WriteString(", ")
	builder.WriteString("quality=")
	builder.WriteString(_m.Quality)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("weapon_visual=")
	builder.WriteString(_m.WeaponVisual)
	builder.WriteString(", ")
	builder.WriteString("power_bonus=")
	builder.WriteString(fmt.Sprintf("%v", _m.PowerBonus))
	builder.WriteString(", ")
	builder.WriteString("task_types=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskTypes))
	builder.WriteString(", ")
	builder.WriteString("is_platform_exclusive=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPlatformExclusive))
	builder.WriteString(", ")
	builder.WriteString("total_supply=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalSupply))
	builder.WriteString(", ")
	builder.WriteString("remaining=")
	builder.WriteString(fmt.Sprintf("%v", _m.Remaining))
	builder.WriteString(", ")
	builder.WriteString("price_tai=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceTai))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Skills is a parsable slice of Skill.
type Skills []*Skill
