// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/skill"
)

// SkillCreate is the builder for creating a Skill entity.
type SkillCreate struct {
	config
	mutation *SkillMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *SkillCreate) SetName(v string) *SkillCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNameEn sets the "name_en" field.
func (_c *SkillCreate) SetNameEn(v string) *SkillCreate {
	_c.mutation.SetNameEn(v)
	return _c
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (_c *SkillCreate) SetNillableNameEn(v *string) *SkillCreate {
	if v != nil {
		_c.SetNameEn(*v)
	}
	return _c
}

// SetQuality sets the "quality" field.
func (_c *SkillCreate) SetQuality(v string) *SkillCreate {
	_c.mutation.SetQuality(v)
	return _c
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_c *SkillCreate) SetNillableQuality(v *string) *SkillCreate {
	if v != nil {
		_c.SetQuality(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *SkillCreate) SetCategory(v string) *SkillCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SkillCreate) SetDescription(v string) *SkillCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SkillCreate) SetNillableDescription(v *string) *SkillCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetWeaponVisual sets the "weapon_visual" field.
func (_c *SkillCreate) SetWeaponVisual(v string) *SkillCreate {
	_c.mutation.SetWeaponVisual(v)
	return _c
}

// SetNillableWeaponVisual sets the "weapon_visual" field if the given value is not nil.
func (_c *SkillCreate) SetNillableWeaponVisual(v *string) *SkillCreate {
	if v != nil {
		_c.SetWeaponVisual(*v)
	}
	return _c
}

// SetPowerBonus sets the "power_bonus" field.
func (_c *SkillCreate) SetPowerBonus(v int) *SkillCreate {
	_c.mutation.SetPowerBonus(v)
	return _c
}

// SetNillablePowerBonus sets the "power_bonus" field if the given value is not nil.
func (_c *SkillCreate) SetNillablePowerBonus(v *int) *SkillCreate {
	if v != nil {
		_c.SetPowerBonus(*v)
	}
	return _c
}

// SetTaskTypes sets the "task_types" field.
func (_c *SkillCreate) SetTaskTypes(v []string) *SkillCreate {
	_c.mutation.SetTaskTypes(v)
	return _c
}

// SetIsPlatformExclusive sets the "is_platform_exclusive" field.
func (_c *SkillCreate) SetIsPlatformExclusive(v bool) *SkillCreate {
	_c.mutation.SetIsPlatformExclusive(v)
	return _c
}

// SetNillableIsPlatformExclusive sets the "is_platform_exclusive" field if the given value is not nil.
func (_c *SkillCreate) SetNillableIsPlatformExclusive(v *bool) *SkillCreate {
	if v != nil {
		_c.SetIsPlatformExclusive(*v)
	}
	return _c
}

// SetTotalSupply sets the "total_supply" field.
func (_c *SkillCreate) SetTotalSupply(v int) *SkillCreate {
	_c.mutation.SetTotalSupply(v)
	return _c
}

// SetNillableTotalSupply sets the "total_supply" field if the given value is not nil.
func (_c *SkillCreate) SetNillableTotalSupply(v *int) *SkillCreate {
	if v != nil {
		_c.SetTotalSupply(*v)
	}
	return _c
}

// SetRemaining sets the "remaining" field.
func (_c *SkillCreate) SetRemaining(v int) *SkillCreate {
	_c.mutation.SetRemaining(v)
	return _c
}

// SetNillableRemaining sets the "remaining" field if the given value is not nil.
func (_c *SkillCreate) SetNillableRemaining(v *int) *SkillCreate {
	if v != nil {
		_c.SetRemaining(*v)
	}
	return _c
}

// SetPriceTai sets the "price_tai" field.
func (_c *SkillCreate) SetPriceTai(v float64) *SkillCreate {
	_c.mutation.SetPriceTai(v)
	return _c
}

// SetNillablePriceTai sets the "price_tai" field if the given value is not nil.
func (_c *SkillCreate) SetNillablePriceTai(v *float64) *SkillCreate {
	if v != nil {
		_c.SetPriceTai(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SkillCreate) SetCreatedAt(v time.Time) *SkillCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SkillCreate) SetNillableCreatedAt(v *time.Time) *SkillCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SkillCreate) SetID(v uuid.UUID) *SkillCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SkillCreate) SetNillableID(v *uuid.UUID) *SkillCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SkillMutation object of the builder.
func (_c *SkillCreate) Mutation() *SkillMutation {
	return _c.mutation
}

// Save creates the Skill in the database.
func (_c *SkillCreate) Save(ctx context.Context) (*Skill, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SkillCreate) SaveX(ctx context.Context) *Skill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SkillCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SkillCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SkillCreate) defaults() {
	if _, ok := _c.mutation.Quality(); !ok {
		v := skill.DefaultQuality
		_c.mutation.SetQuality(v)
	}
	if _, ok := _c.mutation.PowerBonus(); !ok {
		v := skill.DefaultPowerBonus
		_c.mutation.SetPowerBonus(v)
	}
	if _, ok := _c.mutation.IsPlatformExclusive(); !ok {
		v := skill.DefaultIsPlatformExclusive
		_c.mutation.SetIsPlatformExclusive(v)
	}
	if _, ok := _c.mutation.TotalSupply(); !ok {
		v := skill.DefaultTotalSupply
		_c.mutation.SetTotalSupply(v)
	}
	if _, ok := _c.mutation.Remaining(); !ok {
		v := skill.DefaultRemaining
		_c.mutation.SetRemaining(v)
	}
	if _, ok := _c.mutation.PriceTai(); !ok {
		v := skill.DefaultPriceTai
		_c.mutation.SetPriceTai(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := skill.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := skill.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SkillCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Skill.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := skill.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Skill.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.NameEn(); ok {
		if err := skill.NameEnValidator(v); err != nil {
			return &ValidationError{Name: "name_en", err: fmt.Errorf(`ent: validator failed for field "Skill.name_en": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quality(); !ok {
		return &ValidationError{Name: "quality", err: errors.New(`ent: missing required field "Skill.quality"`)}
	}
	if v, ok := _c.mutation.Quality(); ok {
		if err := skill.QualityValidator(v); err != nil {
			return &ValidationError{Name: "quality", err: fmt.Errorf(`ent: validator failed for field "Skill.quality": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Skill.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := skill.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Skill.category": %w`, err)}
		}
	}
	if v, ok := _c.mutation.WeaponVisual(); ok {
		if err := skill.WeaponVisualValidator(v); err != nil {
			return &ValidationError{Name: "weapon_visual", err: fmt.Errorf(`ent: validator failed for field "Skill.weapon_visual": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PowerBonus(); !ok {
		return &ValidationError{Name: "power_bonus", err: errors.New(`ent: missing required field "Skill.power_bonus"`)}
	}
	if _, ok := _c.mutation.IsPlatformExclusive(); !ok {
		return &ValidationError{Name: "is_platform_exclusive", err: errors.New(`ent: missing required field "Skill.is_platform_exclusive"`)}
	}
	if _, ok := _c.mutation.TotalSupply(); !ok {
		return &ValidationError{Name: "total_supply", err: errors.New(`ent: missing required field "Skill.total_supply"`)}
	}
	if _, ok := _c.mutation.Remaining(); !ok {
		return &ValidationError{Name: "remaining", err: errors.New(`ent: missing required field "Skill.remaining"`)}
	}
	if _, ok := _c.mutation.PriceTai(); !ok {
		return &ValidationError{Name: "price_tai", err: errors.New(`ent: missing required field "Skill.price_tai"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Skill.created_at"`)}
	}
	return nil
}

func (_c *SkillCreate) sqlSave(ctx context.Context) (*Skill, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SkillCreate) createSpec() (*Skill, *sqlgraph.CreateSpec) {
	var (
		_node = &Skill{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(skill.Table, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.NameEn(); ok {
		_spec.SetField(skill.FieldNameEn, field.TypeString, value)
		_node.NameEn = value
	}
	if value, ok := _c.mutation.Quality(); ok {
		_spec.SetField(skill.FieldQuality, field.TypeString, value)
		_node.Quality = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(skill.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(skill.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.WeaponVisual(); ok {
		_spec.SetField(skill.FieldWeaponVisual, field.TypeString, value)
		_node.WeaponVisual = value
	}
	if value, ok := _c.mutation.PowerBonus(); ok {
		_spec.SetField(skill.FieldPowerBonus, field.TypeInt, value)
		_node.PowerBonus = value
	}
	if value, ok := _c.mutation.TaskTypes(); ok {
		_spec.SetField(skill.FieldTaskTypes, field.TypeJSON, value)
		_node.TaskTypes = value
	}
	if value, ok := _c.mutation.IsPlatformExclusive(); ok {
		_spec.SetField(skill.FieldIsPlatformExclusive, field.TypeBool, value)
		_node.IsPlatformExclusive = value
	}
	if value, ok := _c.mutation.TotalSupply(); ok {
		_spec.SetField(skill.FieldTotalSupply, field.TypeInt, value)
		_node.TotalSupply = value
	}
	if value, ok := _c.mutation.Remaining(); ok {
		_spec.SetField(skill.FieldRemaining, field.TypeInt, value)
		_node.Remaining = value
	}
	if value, ok := _c.mutation.PriceTai(); ok {
		_spec.SetField(skill.FieldPriceTai, field.TypeFloat64, value)
		_node.PriceTai = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(skill.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// SkillCreateBulk is the builder for creating many Skill entities in bulk.
type SkillCreateBulk struct {
	config
	err      error
	builders []*SkillCreate
}

// Save creates the Skill entities in the database.
func (_c *SkillCreateBulk) Save(ctx context.Context) ([]*Skill, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Skill, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SkillMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SkillCreateBulk) SaveX(ctx context.Context) []*Skill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SkillCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SkillCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
