// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/tii-mom/tai-protocol/backend/ent/predicate"
	"github.com/tii-mom/tai-protocol/backend/ent/skill"
)

// SkillUpdate is the builder for updating Skill entities.
type SkillUpdate struct {
	config
	hooks    []Hook
	mutation *SkillMutation
}

// Where appends a list predicates to the SkillUpdate builder.
func (_u *SkillUpdate) Where(ps ...predicate.Skill) *SkillUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SkillUpdate) SetName(v string) *SkillUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableName(v *string) *SkillUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNameEn sets the "name_en" field.
func (_u *SkillUpdate) SetNameEn(v string) *SkillUpdate {
	_u.mutation.SetNameEn(v)
	return _u
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableNameEn(v *string) *SkillUpdate {
	if v != nil {
		_u.SetNameEn(*v)
	}
	return _u
}

// ClearNameEn clears the value of the "name_en" field.
func (_u *SkillUpdate) ClearNameEn() *SkillUpdate {
	_u.mutation.ClearNameEn()
	return _u
}

// SetQuality sets the "quality" field.
func (_u *SkillUpdate) SetQuality(v string) *SkillUpdate {
	_u.mutation.SetQuality(v)
	return _u
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableQuality(v *string) *SkillUpdate {
	if v != nil {
		_u.SetQuality(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SkillUpdate) SetCategory(v string) *SkillUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableCategory(v *string) *SkillUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SkillUpdate) SetDescription(v string) *SkillUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableDescription(v *string) *SkillUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SkillUpdate) ClearDescription() *SkillUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetWeaponVisual sets the "weapon_visual" field.
func (_u *SkillUpdate) SetWeaponVisual(v string) *SkillUpdate {
	_u.mutation.SetWeaponVisual(v)
	return _u
}

// SetNillableWeaponVisual sets the "weapon_visual" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableWeaponVisual(v *string) *SkillUpdate {
	if v != nil {
		_u.SetWeaponVisual(*v)
	}
	return _u
}

// ClearWeaponVisual clears the value of the "weapon_visual" field.
func (_u *SkillUpdate) ClearWeaponVisual() *SkillUpdate {
	_u.mutation.ClearWeaponVisual()
	return _u
}

// SetPowerBonus sets the "power_bonus" field.
func (_u *SkillUpdate) SetPowerBonus(v int) *SkillUpdate {
	_u.mutation.ResetPowerBonus()
	_u.mutation.SetPowerBonus(v)
	return _u
}

// SetNillablePowerBonus sets the "power_bonus" field if the given value is not nil.
func (_u *SkillUpdate) SetNillablePowerBonus(v *int) *SkillUpdate {
	if v != nil {
		_u.SetPowerBonus(*v)
	}
	return _u
}

// AddPowerBonus adds value to the "power_bonus" field.
func (_u *SkillUpdate) AddPowerBonus(v int) *SkillUpdate {
	_u.mutation.AddPowerBonus(v)
	return _u
}

// SetTaskTypes sets the "task_types" field.
func (_u *SkillUpdate) SetTaskTypes(v []string) *SkillUpdate {
	_u.mutation.SetTaskTypes(v)
	return _u
}

// AppendTaskTypes appends value to the "task_types" field.
func (_u *SkillUpdate) AppendTaskTypes(v []string) *SkillUpdate {
	_u.mutation.AppendTaskTypes(v)
	return _u
}

// ClearTaskTypes clears the value of the "task_types" field.
func (_u *SkillUpdate) ClearTaskTypes() *SkillUpdate {
	_u.mutation.ClearTaskTypes()
	return _u
}

// SetIsPlatformExclusive sets the "is_platform_exclusive" field.
func (_u *SkillUpdate) SetIsPlatformExclusive(v bool) *SkillUpdate {
	_u.mutation.SetIsPlatformExclusive(v)
	return _u
}

// SetNillableIsPlatformExclusive sets the "is_platform_exclusive" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableIsPlatformExclusive(v *bool) *SkillUpdate {
	if v != nil {
		_u.SetIsPlatformExclusive(*v)
	}
	return _u
}

// SetTotalSupply sets the "total_supply" field.
func (_u *SkillUpdate) SetTotalSupply(v int) *SkillUpdate {
	_u.mutation.ResetTotalSupply()
	_u.mutation.SetTotalSupply(v)
	return _u
}

// SetNillableTotalSupply sets the "total_supply" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableTotalSupply(v *int) *SkillUpdate {
	if v != nil {
		_u.SetTotalSupply(*v)
	}
	return _u
}

// AddTotalSupply adds value to the "total_supply" field.
func (_u *SkillUpdate) AddTotalSupply(v int) *SkillUpdate {
	_u.mutation.AddTotalSupply(v)
	return _u
}

// SetRemaining sets the "remaining" field.
func (_u *SkillUpdate) SetRemaining(v int) *SkillUpdate {
	_u.mutation.ResetRemaining()
	_u.mutation.SetRemaining(v)
	return _u
}

// SetNillableRemaining sets the "remaining" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableRemaining(v *int) *SkillUpdate {
	if v != nil {
		_u.SetRemaining(*v)
	}
	return _u
}

// AddRemaining adds value to the "remaining" field.
func (_u *SkillUpdate) AddRemaining(v int) *SkillUpdate {
	_u.mutation.AddRemaining(v)
	return _u
}

// SetPriceTai sets the "price_tai" field.
func (_u *SkillUpdate) SetPriceTai(v float64) *SkillUpdate {
	_u.mutation.ResetPriceTai()
	_u.mutation.SetPriceTai(v)
	return _u
}

// SetNillablePriceTai sets the "price_tai" field if the given value is not nil.
func (_u *SkillUpdate) SetNillablePriceTai(v *float64) *SkillUpdate {
	if v != nil {
		_u.SetPriceTai(*v)
	}
	return _u
}

// AddPriceTai adds value to the "price_tai" field.
func (_u *SkillUpdate) AddPriceTai(v float64) *SkillUpdate {
	_u.mutation.AddPriceTai(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SkillUpdate) SetCreatedAt(v time.Time) *SkillUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableCreatedAt(v *time.Time) *SkillUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the SkillMutation object of the builder.
func (_u *SkillUpdate) Mutation() *SkillMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SkillUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SkillUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkillUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := skill.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Skill.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameEn(); ok {
		if err := skill.NameEnValidator(v); err != nil {
			return &ValidationError{Name: "name_en", err: fmt.Errorf(`ent: validator failed for field "Skill.name_en": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quality(); ok {
		if err := skill.QualityValidator(v); err != nil {
			return &ValidationError{Name: "quality", err: fmt.Errorf(`ent: validator failed for field "Skill.quality": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := skill.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Skill.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WeaponVisual(); ok {
		if err := skill.WeaponVisualValidator(v); err != nil {
			return &ValidationError{Name: "weapon_visual", err: fmt.Errorf(`ent: validator failed for field "Skill.weapon_visual": %w`, err)}
		}
	}
	return nil
}

func (_u *SkillUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skill.Table, skill.Columns, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameEn(); ok {
		_spec.SetField(skill.FieldNameEn, field.TypeString, value)
	}
	if _u.mutation.NameEnCleared() {
		_spec.ClearField(skill.FieldNameEn, field.TypeString)
	}
	if value, ok := _u.mutation.Quality(); ok {
		_spec.SetField(skill.FieldQuality, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(skill.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(skill.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(skill.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.WeaponVisual(); ok {
		_spec.SetField(skill.FieldWeaponVisual, field.TypeString, value)
	}
	if _u.mutation.WeaponVisualCleared() {
		_spec.ClearField(skill.FieldWeaponVisual, field.TypeString)
	}
	if value, ok := _u.mutation.PowerBonus(); ok {
		_spec.SetField(skill.FieldPowerBonus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPowerBonus(); ok {
		_spec.AddField(skill.FieldPowerBonus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TaskTypes(); ok {
		_spec.SetField(skill.FieldTaskTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTaskTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, skill.FieldTaskTypes, value)
		})
	}
	if _u.mutation.TaskTypesCleared() {
		_spec.ClearField(skill.FieldTaskTypes, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsPlatformExclusive(); ok {
		_spec.SetField(skill.FieldIsPlatformExclusive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TotalSupply(); ok {
		_spec.SetField(skill.FieldTotalSupply, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalSupply(); ok {
		_spec.AddField(skill.FieldTotalSupply, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Remaining(); ok {
		_spec.SetField(skill.FieldRemaining, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRemaining(); ok {
		_spec.AddField(skill.FieldRemaining, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PriceTai(); ok {
		_spec.SetField(skill.FieldPriceTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPriceTai(); ok {
		_spec.AddField(skill.FieldPriceTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(skill.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SkillUpdateOne is the builder for updating a single Skill entity.
type SkillUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SkillMutation
}

// SetName sets the "name" field.
func (_u *SkillUpdateOne) SetName(v string) *SkillUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableName(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNameEn sets the "name_en" field.
func (_u *SkillUpdateOne) SetNameEn(v string) *SkillUpdateOne {
	_u.mutation.SetNameEn(v)
	return _u
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableNameEn(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetNameEn(*v)
	}
	return _u
}

// ClearNameEn clears the value of the "name_en" field.
func (_u *SkillUpdateOne) ClearNameEn() *SkillUpdateOne {
	_u.mutation.ClearNameEn()
	return _u
}

// SetQuality sets the "quality" field.
func (_u *SkillUpdateOne) SetQuality(v string) *SkillUpdateOne {
	_u.mutation.SetQuality(v)
	return _u
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableQuality(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetQuality(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SkillUpdateOne) SetCategory(v string) *SkillUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableCategory(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SkillUpdateOne) SetDescription(v string) *SkillUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableDescription(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SkillUpdateOne) ClearDescription() *SkillUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetWeaponVisual sets the "weapon_visual" field.
func (_u *SkillUpdateOne) SetWeaponVisual(v string) *SkillUpdateOne {
	_u.mutation.SetWeaponVisual(v)
	return _u
}

// SetNillableWeaponVisual sets the "weapon_visual" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableWeaponVisual(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetWeaponVisual(*v)
	}
	return _u
}

// ClearWeaponVisual clears the value of the "weapon_visual" field.
func (_u *SkillUpdateOne) ClearWeaponVisual() *SkillUpdateOne {
	_u.mutation.ClearWeaponVisual()
	return _u
}

// SetPowerBonus sets the "power_bonus" field.
func (_u *SkillUpdateOne) SetPowerBonus(v int) *SkillUpdateOne {
	_u.mutation.ResetPowerBonus()
	_u.mutation.SetPowerBonus(v)
	return _u
}

// SetNillablePowerBonus sets the "power_bonus" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillablePowerBonus(v *int) *SkillUpdateOne {
	if v != nil {
		_u.SetPowerBonus(*v)
	}
	return _u
}

// AddPowerBonus adds value to the "power_bonus" field.
func (_u *SkillUpdateOne) AddPowerBonus(v int) *SkillUpdateOne {
	_u.mutation.AddPowerBonus(v)
	return _u
}

// SetTaskTypes sets the "task_types" field.
func (_u *SkillUpdateOne) SetTaskTypes(v []string) *SkillUpdateOne {
	_u.mutation.SetTaskTypes(v)
	return _u
}

// AppendTaskTypes appends value to the "task_types" field.
func (_u *SkillUpdateOne) AppendTaskTypes(v []string) *SkillUpdateOne {
	_u.mutation.AppendTaskTypes(v)
	return _u
}

// ClearTaskTypes clears the value of the "task_types" field.
func (_u *SkillUpdateOne) ClearTaskTypes() *SkillUpdateOne {
	_u.mutation.ClearTaskTypes()
	return _u
}

// SetIsPlatformExclusive sets the "is_platform_exclusive" field.
func (_u *SkillUpdateOne) SetIsPlatformExclusive(v bool) *SkillUpdateOne {
	_u.mutation.SetIsPlatformExclusive(v)
	return _u
}

// SetNillableIsPlatformExclusive sets the "is_platform_exclusive" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableIsPlatformExclusive(v *bool) *SkillUpdateOne {
	if v != nil {
		_u.SetIsPlatformExclusive(*v)
	}
	return _u
}

// SetTotalSupply sets the "total_supply" field.
func (_u *SkillUpdateOne) SetTotalSupply(v int) *SkillUpdateOne {
	_u.mutation.ResetTotalSupply()
	_u.mutation.SetTotalSupply(v)
	return _u
}

// SetNillableTotalSupply sets the "total_supply" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableTotalSupply(v *int) *SkillUpdateOne {
	if v != nil {
		_u.SetTotalSupply(*v)
	}
	return _u
}

// AddTotalSupply adds value to the "total_supply" field.
func (_u *SkillUpdateOne) AddTotalSupply(v int) *SkillUpdateOne {
	_u.mutation.AddTotalSupply(v)
	return _u
}

// SetRemaining sets the "remaining" field.
func (_u *SkillUpdateOne) SetRemaining(v int) *SkillUpdateOne {
	_u.mutation.ResetRemaining()
	_u.mutation.SetRemaining(v)
	return _u
}

// SetNillableRemaining sets the "remaining" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableRemaining(v *int) *SkillUpdateOne {
	if v != nil {
		_u.SetRemaining(*v)
	}
	return _u
}

// AddRemaining adds value to the "remaining" field.
func (_u *SkillUpdateOne) AddRemaining(v int) *SkillUpdateOne {
	_u.mutation.AddRemaining(v)
	return _u
}

// SetPriceTai sets the "price_tai" field.
func (_u *SkillUpdateOne) SetPriceTai(v float64) *SkillUpdateOne {
	_u.mutation.ResetPriceTai()
	_u.mutation.SetPriceTai(v)
	return _u
}

// SetNillablePriceTai sets the "price_tai" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillablePriceTai(v *float64) *SkillUpdateOne {
	if v != nil {
		_u.SetPriceTai(*v)
	}
	return _u
}

// AddPriceTai adds value to the "price_tai" field.
func (_u *SkillUpdateOne) AddPriceTai(v float64) *SkillUpdateOne {
	_u.mutation.AddPriceTai(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SkillUpdateOne) SetCreatedAt(v time.Time) *SkillUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableCreatedAt(v *time.Time) *SkillUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the SkillMutation object of the builder.
func (_u *SkillUpdateOne) Mutation() *SkillMutation {
	return _u.mutation
}

// Where appends a list predicates to the SkillUpdate builder.
func (_u *SkillUpdateOne) Where(ps ...predicate.Skill) *SkillUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SkillUpdateOne) Select(field string, fields ...string) *SkillUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Skill entity.
func (_u *SkillUpdateOne) Save(ctx context.Context) (*Skill, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillUpdateOne) SaveX(ctx context.Context) *Skill {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SkillUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkillUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := skill.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Skill.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameEn(); ok {
		if err := skill.NameEnValidator(v); err != nil {
			return &ValidationError{Name: "name_en", err: fmt.Errorf(`ent: validator failed for field "Skill.name_en": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quality(); ok {
		if err := skill.QualityValidator(v); err != nil {
			return &ValidationError{Name: "quality", err: fmt.Errorf(`ent: validator failed for field "Skill.quality": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := skill.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Skill.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WeaponVisual(); ok {
		if err := skill.WeaponVisualValidator(v); err != nil {
			return &ValidationError{Name: "weapon_visual", err: fmt.Errorf(`ent: validator failed for field "Skill.weapon_visual": %w`, err)}
		}
	}
	return nil
}

func (_u *SkillUpdateOne) sqlSave(ctx context.Context) (_node *Skill, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skill.Table, skill.Columns, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Skill.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, skill.FieldID)
		for _, f := range fields {
			if !skill.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != skill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameEn(); ok {
		_spec.SetField(skill.FieldNameEn, field.TypeString, value)
	}
	if _u.mutation.NameEnCleared() {
		_spec.ClearField(skill.FieldNameEn, field.TypeString)
	}
	if value, ok := _u.mutation.Quality(); ok {
		_spec.SetField(skill.FieldQuality, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(skill.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(skill.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(skill.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.WeaponVisual(); ok {
		_spec.SetField(skill.FieldWeaponVisual, field.TypeString, value)
	}
	if _u.mutation.WeaponVisualCleared() {
		_spec.ClearField(skill.FieldWeaponVisual, field.TypeString)
	}
	if value, ok := _u.mutation.PowerBonus(); ok {
		_spec.SetField(skill.FieldPowerBonus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPowerBonus(); ok {
		_spec.AddField(skill.FieldPowerBonus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TaskTypes(); ok {
		_spec.SetField(skill.FieldTaskTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTaskTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, skill.FieldTaskTypes, value)
		})
	}
	if _u.mutation.TaskTypesCleared() {
		_spec.ClearField(skill.FieldTaskTypes, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsPlatformExclusive(); ok {
		_spec.SetField(skill.FieldIsPlatformExclusive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TotalSupply(); ok {
		_spec.SetField(skill.FieldTotalSupply, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalSupply(); ok {
		_spec.AddField(skill.FieldTotalSupply, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Remaining(); ok {
		_spec.SetField(skill.FieldRemaining, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRemaining(); ok {
		_spec.AddField(skill.FieldRemaining, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PriceTai(); ok {
		_spec.SetField(skill.FieldPriceTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPriceTai(); ok {
		_spec.AddField(skill.FieldPriceTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(skill.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Skill{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
