// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/usagelog"
)

// UsageLogCreate is the builder for creating a UsageLog entity.
type UsageLogCreate struct {
	config
	mutation *UsageLogMutation
	hooks    []Hook
}

// SetPetID sets the "pet_id" field.
func (_c *UsageLogCreate) SetPetID(v string) *UsageLogCreate {
	_c.mutation.SetPetID(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *UsageLogCreate) SetModel(v string) *UsageLogCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetPromptTokens sets the "prompt_tokens" field.
func (_c *UsageLogCreate) SetPromptTokens(v int) *UsageLogCreate {
	_c.mutation.SetPromptTokens(v)
	return _c
}

// SetNillablePromptTokens sets the "prompt_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillablePromptTokens(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetPromptTokens(*v)
	}
	return _c
}

// SetCompletionTokens sets the "completion_tokens" field.
func (_c *UsageLogCreate) SetCompletionTokens(v int) *UsageLogCreate {
	_c.mutation.SetCompletionTokens(v)
	return _c
}

// SetNillableCompletionTokens sets the "completion_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCompletionTokens(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetCompletionTokens(*v)
	}
	return _c
}

// SetTaiCost sets the "tai_cost" field.
func (_c *UsageLogCreate) SetTaiCost(v float64) *UsageLogCreate {
	_c.mutation.SetTaiCost(v)
	return _c
}

// SetNillableTaiCost sets the "tai_cost" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableTaiCost(v *float64) *UsageLogCreate {
	if v != nil {
		_c.SetTaiCost(*v)
	}
	return _c
}

// SetBountyID sets the "bounty_id" field.
func (_c *UsageLogCreate) SetBountyID(v string) *UsageLogCreate {
	_c.mutation.SetBountyID(v)
	return _c
}

// SetNillableBountyID sets the "bounty_id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableBountyID(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetBountyID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageLogCreate) SetCreatedAt(v time.Time) *UsageLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCreatedAt(v *time.Time) *UsageLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UsageLogCreate) SetID(v uuid.UUID) *UsageLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableID(v *uuid.UUID) *UsageLogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the UsageLogMutation object of the builder.
func (_c *UsageLogCreate) Mutation() *UsageLogMutation {
	return _c.mutation
}

// Save creates the UsageLog in the database.
func (_c *UsageLogCreate) Save(ctx context.Context) (*UsageLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageLogCreate) SaveX(ctx context.Context) *UsageLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageLogCreate) defaults() {
	if _, ok := _c.mutation.PromptTokens(); !ok {
		v := usagelog.DefaultPromptTokens
		_c.mutation.SetPromptTokens(v)
	}
	if _, ok := _c.mutation.CompletionTokens(); !ok {
		v := usagelog.DefaultCompletionTokens
		_c.mutation.SetCompletionTokens(v)
	}
	if _, ok := _c.mutation.TaiCost(); !ok {
		v := usagelog.DefaultTaiCost
		_c.mutation.SetTaiCost(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usagelog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := usagelog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageLogCreate) check() error {
	if _, ok := _c.mutation.PetID(); !ok {
		return &ValidationError{Name: "pet_id", err: errors.New(`ent: missing required field "UsageLog.pet_id"`)}
	}
	if v, ok := _c.mutation.PetID(); ok {
		if err := usagelog.PetIDValidator(v); err != nil {
			return &ValidationError{Name: "pet_id", err: fmt.Errorf(`ent: validator failed for field "UsageLog.pet_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "UsageLog.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := usagelog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "UsageLog.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PromptTokens(); !ok {
		return &ValidationError{Name: "prompt_tokens", err: errors.New(`ent: missing required field "UsageLog.prompt_tokens"`)}
	}
	if _, ok := _c.mutation.CompletionTokens(); !ok {
		return &ValidationError{Name: "completion_tokens", err: errors.New(`ent: missing required field "UsageLog.completion_tokens"`)}
	}
	if _, ok := _c.mutation.TaiCost(); !ok {
		return &ValidationError{Name: "tai_cost", err: errors.New(`ent: missing required field "UsageLog.tai_cost"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageLog.created_at"`)}
	}
	return nil
}

func (_c *UsageLogCreate) sqlSave(ctx context.Context) (*UsageLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageLogCreate) createSpec() (*UsageLog, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagelog.Table, sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PetID(); ok {
		_spec.SetField(usagelog.FieldPetID, field.TypeString, value)
		_node.PetID = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(usagelog.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.PromptTokens(); ok {
		_spec.SetField(usagelog.FieldPromptTokens, field.TypeInt, value)
		_node.PromptTokens = value
	}
	if value, ok := _c.mutation.CompletionTokens(); ok {
		_spec.SetField(usagelog.FieldCompletionTokens, field.TypeInt, value)
		_node.CompletionTokens = value
	}
	if value, ok := _c.mutation.TaiCost(); ok {
		_spec.SetField(usagelog.FieldTaiCost, field.TypeFloat64, value)
		_node.TaiCost = value
	}
	if value, ok := _c.mutation.BountyID(); ok {
		_spec.SetField(usagelog.FieldBountyID, field.TypeString, value)
		_node.BountyID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// UsageLogCreateBulk is the builder for creating many UsageLog entities in bulk.
type UsageLogCreateBulk struct {
	config
	err      error
	builders []*UsageLogCreate
}

// Save creates the UsageLog entities in the database.
func (_c *UsageLogCreateBulk) Save(ctx context.Context) ([]*UsageLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageLogCreateBulk) SaveX(ctx context.Context) []*UsageLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
