// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/pet"
	"github.com/tii-mom/tai-protocol/backend/ent/predicate"
	"github.com/tii-mom/tai-protocol/backend/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTgUserID sets the "tg_user_id" field.
func (_u *UserUpdate) SetTgUserID(v int64) *UserUpdate {
	_u.mutation.ResetTgUserID()
	_u.mutation.SetTgUserID(v)
	return _u
}

// SetNillableTgUserID sets the "tg_user_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTgUserID(v *int64) *UserUpdate {
	if v != nil {
		_u.SetTgUserID(*v)
	}
	return _u
}

// AddTgUserID adds value to the "tg_user_id" field.
func (_u *UserUpdate) AddTgUserID(v int64) *UserUpdate {
	_u.mutation.AddTgUserID(v)
	return _u
}

// SetTgUsername sets the "tg_username" field.
func (_u *UserUpdate) SetTgUsername(v string) *UserUpdate {
	_u.mutation.SetTgUsername(v)
	return _u
}

// SetNillableTgUsername sets the "tg_username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTgUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetTgUsername(*v)
	}
	return _u
}

// ClearTgUsername clears the value of the "tg_username" field.
func (_u *UserUpdate) ClearTgUsername() *UserUpdate {
	_u.mutation.ClearTgUsername()
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *UserUpdate) SetFirstName(v string) *UserUpdate {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableFirstName(v *string) *UserUpdate {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// ClearFirstName clears the value of the "first_name" field.
func (_u *UserUpdate) ClearFirstName() *UserUpdate {
	_u.mutation.ClearFirstName()
	return _u
}

// SetWalletAddress sets the "wallet_address" field.
func (_u *UserUpdate) SetWalletAddress(v string) *UserUpdate {
	_u.mutation.SetWalletAddress(v)
	return _u
}

// SetNillableWalletAddress sets the "wallet_address" field if the given value is not nil.
func (_u *UserUpdate) SetNillableWalletAddress(v *string) *UserUpdate {
	if v != nil {
		_u.SetWalletAddress(*v)
	}
	return _u
}

// ClearWalletAddress clears the value of the "wallet_address" field.
func (_u *UserUpdate) ClearWalletAddress() *UserUpdate {
	_u.mutation.ClearWalletAddress()
	return _u
}

// SetBalanceTai sets the "balance_tai" field.
func (_u *UserUpdate) SetBalanceTai(v float64) *UserUpdate {
	_u.mutation.ResetBalanceTai()
	_u.mutation.SetBalanceTai(v)
	return _u
}

// SetNillableBalanceTai sets the "balance_tai" field if the given value is not nil.
func (_u *UserUpdate) SetNillableBalanceTai(v *float64) *UserUpdate {
	if v != nil {
		_u.SetBalanceTai(*v)
	}
	return _u
}

// AddBalanceTai adds value to the "balance_tai" field.
func (_u *UserUpdate) AddBalanceTai(v float64) *UserUpdate {
	_u.mutation.AddBalanceTai(v)
	return _u
}

// SetBalanceUsdt sets the "balance_usdt" field.
func (_u *UserUpdate) SetBalanceUsdt(v float64) *UserUpdate {
	_u.mutation.ResetBalanceUsdt()
	_u.mutation.SetBalanceUsdt(v)
	return _u
}

// SetNillableBalanceUsdt sets the "balance_usdt" field if the given value is not nil.
func (_u *UserUpdate) SetNillableBalanceUsdt(v *float64) *UserUpdate {
	if v != nil {
		_u.SetBalanceUsdt(*v)
	}
	return _u
}

// AddBalanceUsdt adds value to the "balance_usdt" field.
func (_u *UserUpdate) AddBalanceUsdt(v float64) *UserUpdate {
	_u.mutation.AddBalanceUsdt(v)
	return _u
}

// SetFrozenBalance sets the "frozen_balance" field.
func (_u *UserUpdate) SetFrozenBalance(v float64) *UserUpdate {
	_u.mutation.ResetFrozenBalance()
	_u.mutation.SetFrozenBalance(v)
	return _u
}

// SetNillableFrozenBalance sets the "frozen_balance" field if the given value is not nil.
func (_u *UserUpdate) SetNillableFrozenBalance(v *float64) *UserUpdate {
	if v != nil {
		_u.SetFrozenBalance(*v)
	}
	return _u
}

// AddFrozenBalance adds value to the "frozen_balance" field.
func (_u *UserUpdate) AddFrozenBalance(v float64) *UserUpdate {
	_u.mutation.AddFrozenBalance(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *UserUpdate) SetRole(v string) *UserUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *UserUpdate) SetNillableRole(v *string) *UserUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetReferralCode sets the "referral_code" field.
func (_u *UserUpdate) SetReferralCode(v string) *UserUpdate {
	_u.mutation.SetReferralCode(v)
	return _u
}

// SetNillableReferralCode sets the "referral_code" field if the given value is not nil.
func (_u *UserUpdate) SetNillableReferralCode(v *string) *UserUpdate {
	if v != nil {
		_u.SetReferralCode(*v)
	}
	return _u
}

// ClearReferralCode clears the value of the "referral_code" field.
func (_u *UserUpdate) ClearReferralCode() *UserUpdate {
	_u.mutation.ClearReferralCode()
	return _u
}

// SetReferredBy sets the "referred_by" field.
func (_u *UserUpdate) SetReferredBy(v uuid.UUID) *UserUpdate {
	_u.mutation.SetReferredBy(v)
	return _u
}

// SetNillableReferredBy sets the "referred_by" field if the given value is not nil.
func (_u *UserUpdate) SetNillableReferredBy(v *uuid.UUID) *UserUpdate {
	if v != nil {
		_u.SetReferredBy(*v)
	}
	return _u
}

// ClearReferredBy clears the value of the "referred_by" field.
func (_u *UserUpdate) ClearReferredBy() *UserUpdate {
	_u.mutation.ClearReferredBy()
	return _u
}

// SetInviteCount sets the "invite_count" field.
func (_u *UserUpdate) SetInviteCount(v int) *UserUpdate {
	_u.mutation.ResetInviteCount()
	_u.mutation.SetInviteCount(v)
	return _u
}

// SetNillableInviteCount sets the "invite_count" field if the given value is not nil.
func (_u *UserUpdate) SetNillableInviteCount(v *int) *UserUpdate {
	if v != nil {
		_u.SetInviteCount(*v)
	}
	return _u
}

// AddInviteCount adds value to the "invite_count" field.
func (_u *UserUpdate) AddInviteCount(v int) *UserUpdate {
	_u.mutation.AddInviteCount(v)
	return _u
}

// SetTotalEarned sets the "total_earned" field.
func (_u *UserUpdate) SetTotalEarned(v float64) *UserUpdate {
	_u.mutation.ResetTotalEarned()
	_u.mutation.SetTotalEarned(v)
	return _u
}

// SetNillableTotalEarned sets the "total_earned" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTotalEarned(v *float64) *UserUpdate {
	if v != nil {
		_u.SetTotalEarned(*v)
	}
	return _u
}

// AddTotalEarned adds value to the "total_earned" field.
func (_u *UserUpdate) AddTotalEarned(v float64) *UserUpdate {
	_u.mutation.AddTotalEarned(v)
	return _u
}

// SetGuildID sets the "guild_id" field.
func (_u *UserUpdate) SetGuildID(v uuid.UUID) *UserUpdate {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGuildID(v *uuid.UUID) *UserUpdate {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// ClearGuildID clears the value of the "guild_id" field.
func (_u *UserUpdate) ClearGuildID() *UserUpdate {
	_u.mutation.ClearGuildID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserUpdate) SetStatus(v string) *UserUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserUpdate) SetNillableStatus(v *string) *UserUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPetIDs adds the "pets" edge to the Pet entity by IDs.
func (_u *UserUpdate) AddPetIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddPetIDs(ids...)
	return _u
}

// AddPets adds the "pets" edges to the Pet entity.
func (_u *UserUpdate) AddPets(v ...*Pet) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPetIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearPets clears all "pets" edges to the Pet entity.
func (_u *UserUpdate) ClearPets() *UserUpdate {
	_u.mutation.ClearPets()
	return _u
}

// RemovePetIDs removes the "pets" edge to Pet entities by IDs.
func (_u *UserUpdate) RemovePetIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemovePetIDs(ids...)
	return _u
}

// RemovePets removes "pets" edges to Pet entities.
func (_u *UserUpdate) RemovePets(v ...*Pet) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePetIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.TgUsername(); ok {
		if err := user.TgUsernameValidator(v); err != nil {
			return &ValidationError{Name: "tg_username", err: fmt.Errorf(`ent: validator failed for field "User.tg_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirstName(); ok {
		if err := user.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "User.first_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WalletAddress(); ok {
		if err := user.WalletAddressValidator(v); err != nil {
			return &ValidationError{Name: "wallet_address", err: fmt.Errorf(`ent: validator failed for field "User.wallet_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := user.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "User.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReferralCode(); ok {
		if err := user.ReferralCodeValidator(v); err != nil {
			return &ValidationError{Name: "referral_code", err: fmt.Errorf(`ent: validator failed for field "User.referral_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := user.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "User.status": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TgUserID(); ok {
		_spec.SetField(user.FieldTgUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTgUserID(); ok {
		_spec.AddField(user.FieldTgUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TgUsername(); ok {
		_spec.SetField(user.FieldTgUsername, field.TypeString, value)
	}
	if _u.mutation.TgUsernameCleared() {
		_spec.ClearField(user.FieldTgUsername, field.TypeString)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(user.FieldFirstName, field.TypeString, value)
	}
	if _u.mutation.FirstNameCleared() {
		_spec.ClearField(user.FieldFirstName, field.TypeString)
	}
	if value, ok := _u.mutation.WalletAddress(); ok {
		_spec.SetField(user.FieldWalletAddress, field.TypeString, value)
	}
	if _u.mutation.WalletAddressCleared() {
		_spec.ClearField(user.FieldWalletAddress, field.TypeString)
	}
	if value, ok := _u.mutation.BalanceTai(); ok {
		_spec.SetField(user.FieldBalanceTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceTai(); ok {
		_spec.AddField(user.FieldBalanceTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceUsdt(); ok {
		_spec.SetField(user.FieldBalanceUsdt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceUsdt(); ok {
		_spec.AddField(user.FieldBalanceUsdt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FrozenBalance(); ok {
		_spec.SetField(user.FieldFrozenBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrozenBalance(); ok {
		_spec.AddField(user.FieldFrozenBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReferralCode(); ok {
		_spec.SetField(user.FieldReferralCode, field.TypeString, value)
	}
	if _u.mutation.ReferralCodeCleared() {
		_spec.ClearField(user.FieldReferralCode, field.TypeString)
	}
	if value, ok := _u.mutation.ReferredBy(); ok {
		_spec.SetField(user.FieldReferredBy, field.TypeUUID, value)
	}
	if _u.mutation.ReferredByCleared() {
		_spec.ClearField(user.FieldReferredBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.InviteCount(); ok {
		_spec.SetField(user.FieldInviteCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInviteCount(); ok {
		_spec.AddField(user.FieldInviteCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalEarned(); ok {
		_spec.SetField(user.FieldTotalEarned, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalEarned(); ok {
		_spec.AddField(user.FieldTotalEarned, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(user.FieldGuildID, field.TypeUUID, value)
	}
	if _u.mutation.GuildIDCleared() {
		_spec.ClearField(user.FieldGuildID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(user.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PetsTable,
			Columns: []string{user.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPetsIDs(); len(nodes) > 0 && !_u.mutation.PetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PetsTable,
			Columns: []string{user.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PetsTable,
			Columns: []string{user.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetTgUserID sets the "tg_user_id" field.
func (_u *UserUpdateOne) SetTgUserID(v int64) *UserUpdateOne {
	_u.mutation.ResetTgUserID()
	_u.mutation.SetTgUserID(v)
	return _u
}

// SetNillableTgUserID sets the "tg_user_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTgUserID(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetTgUserID(*v)
	}
	return _u
}

// AddTgUserID adds value to the "tg_user_id" field.
func (_u *UserUpdateOne) AddTgUserID(v int64) *UserUpdateOne {
	_u.mutation.AddTgUserID(v)
	return _u
}

// SetTgUsername sets the "tg_username" field.
func (_u *UserUpdateOne) SetTgUsername(v string) *UserUpdateOne {
	_u.mutation.SetTgUsername(v)
	return _u
}

// SetNillableTgUsername sets the "tg_username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTgUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetTgUsername(*v)
	}
	return _u
}

// ClearTgUsername clears the value of the "tg_username" field.
func (_u *UserUpdateOne) ClearTgUsername() *UserUpdateOne {
	_u.mutation.ClearTgUsername()
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *UserUpdateOne) SetFirstName(v string) *UserUpdateOne {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableFirstName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// ClearFirstName clears the value of the "first_name" field.
func (_u *UserUpdateOne) ClearFirstName() *UserUpdateOne {
	_u.mutation.ClearFirstName()
	return _u
}

// SetWalletAddress sets the "wallet_address" field.
func (_u *UserUpdateOne) SetWalletAddress(v string) *UserUpdateOne {
	_u.mutation.SetWalletAddress(v)
	return _u
}

// SetNillableWalletAddress sets the "wallet_address" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableWalletAddress(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetWalletAddress(*v)
	}
	return _u
}

// ClearWalletAddress clears the value of the "wallet_address" field.
func (_u *UserUpdateOne) ClearWalletAddress() *UserUpdateOne {
	_u.mutation.ClearWalletAddress()
	return _u
}

// SetBalanceTai sets the "balance_tai" field.
func (_u *UserUpdateOne) SetBalanceTai(v float64) *UserUpdateOne {
	_u.mutation.ResetBalanceTai()
	_u.mutation.SetBalanceTai(v)
	return _u
}

// SetNillableBalanceTai sets the "balance_tai" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableBalanceTai(v *float64) *UserUpdateOne {
	if v != nil {
		_u.SetBalanceTai(*v)
	}
	return _u
}

// AddBalanceTai adds value to the "balance_tai" field.
func (_u *UserUpdateOne) AddBalanceTai(v float64) *UserUpdateOne {
	_u.mutation.AddBalanceTai(v)
	return _u
}

// SetBalanceUsdt sets the "balance_usdt" field.
func (_u *UserUpdateOne) SetBalanceUsdt(v float64) *UserUpdateOne {
	_u.mutation.ResetBalanceUsdt()
	_u.mutation.SetBalanceUsdt(v)
	return _u
}

// SetNillableBalanceUsdt sets the "balance_usdt" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableBalanceUsdt(v *float64) *UserUpdateOne {
	if v != nil {
		_u.SetBalanceUsdt(*v)
	}
	return _u
}

// AddBalanceUsdt adds value to the "balance_usdt" field.
func (_u *UserUpdateOne) AddBalanceUsdt(v float64) *UserUpdateOne {
	_u.mutation.AddBalanceUsdt(v)
	return _u
}

// SetFrozenBalance sets the "frozen_balance" field.
func (_u *UserUpdateOne) SetFrozenBalance(v float64) *UserUpdateOne {
	_u.mutation.ResetFrozenBalance()
	_u.mutation.SetFrozenBalance(v)
	return _u
}

// SetNillableFrozenBalance sets the "frozen_balance" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableFrozenBalance(v *float64) *UserUpdateOne {
	if v != nil {
		_u.SetFrozenBalance(*v)
	}
	return _u
}

// AddFrozenBalance adds value to the "frozen_balance" field.
func (_u *UserUpdateOne) AddFrozenBalance(v float64) *UserUpdateOne {
	_u.mutation.AddFrozenBalance(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *UserUpdateOne) SetRole(v string) *UserUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableRole(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetReferralCode sets the "referral_code" field.
func (_u *UserUpdateOne) SetReferralCode(v string) *UserUpdateOne {
	_u.mutation.SetReferralCode(v)
	return _u
}

// SetNillableReferralCode sets the "referral_code" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableReferralCode(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetReferralCode(*v)
	}
	return _u
}

// ClearReferralCode clears the value of the "referral_code" field.
func (_u *UserUpdateOne) ClearReferralCode() *UserUpdateOne {
	_u.mutation.ClearReferralCode()
	return _u
}

// SetReferredBy sets the "referred_by" field.
func (_u *UserUpdateOne) SetReferredBy(v uuid.UUID) *UserUpdateOne {
	_u.mutation.SetReferredBy(v)
	return _u
}

// SetNillableReferredBy sets the "referred_by" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableReferredBy(v *uuid.UUID) *UserUpdateOne {
	if v != nil {
		_u.SetReferredBy(*v)
	}
	return _u
}

// ClearReferredBy clears the value of the "referred_by" field.
func (_u *UserUpdateOne) ClearReferredBy() *UserUpdateOne {
	_u.mutation.ClearReferredBy()
	return _u
}

// SetInviteCount sets the "invite_count" field.
func (_u *UserUpdateOne) SetInviteCount(v int) *UserUpdateOne {
	_u.mutation.ResetInviteCount()
	_u.mutation.SetInviteCount(v)
	return _u
}

// SetNillableInviteCount sets the "invite_count" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableInviteCount(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetInviteCount(*v)
	}
	return _u
}

// AddInviteCount adds value to the "invite_count" field.
func (_u *UserUpdateOne) AddInviteCount(v int) *UserUpdateOne {
	_u.mutation.AddInviteCount(v)
	return _u
}

// SetTotalEarned sets the "total_earned" field.
func (_u *UserUpdateOne) SetTotalEarned(v float64) *UserUpdateOne {
	_u.mutation.ResetTotalEarned()
	_u.mutation.SetTotalEarned(v)
	return _u
}

// SetNillableTotalEarned sets the "total_earned" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTotalEarned(v *float64) *UserUpdateOne {
	if v != nil {
		_u.SetTotalEarned(*v)
	}
	return _u
}

// AddTotalEarned adds value to the "total_earned" field.
func (_u *UserUpdateOne) AddTotalEarned(v float64) *UserUpdateOne {
	_u.mutation.AddTotalEarned(v)
	return _u
}

// SetGuildID sets the "guild_id" field.
func (_u *UserUpdateOne) SetGuildID(v uuid.UUID) *UserUpdateOne {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGuildID(v *uuid.UUID) *UserUpdateOne {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// ClearGuildID clears the value of the "guild_id" field.
func (_u *UserUpdateOne) ClearGuildID() *UserUpdateOne {
	_u.mutation.ClearGuildID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserUpdateOne) SetStatus(v string) *UserUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableStatus(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPetIDs adds the "pets" edge to the Pet entity by IDs.
func (_u *UserUpdateOne) AddPetIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddPetIDs(ids...)
	return _u
}

// AddPets adds the "pets" edges to the Pet entity.
func (_u *UserUpdateOne) AddPets(v ...*Pet) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPetIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearPets clears all "pets" edges to the Pet entity.
func (_u *UserUpdateOne) ClearPets() *UserUpdateOne {
	_u.mutation.ClearPets()
	return _u
}

// RemovePetIDs removes the "pets" edge to Pet entities by IDs.
func (_u *UserUpdateOne) RemovePetIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemovePetIDs(ids...)
	return _u
}

// RemovePets removes "pets" edges to Pet entities.
func (_u *UserUpdateOne) RemovePets(v ...*Pet) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePetIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.TgUsername(); ok {
		if err := user.TgUsernameValidator(v); err != nil {
			return &ValidationError{Name: "tg_username", err: fmt.Errorf(`ent: validator failed for field "User.tg_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirstName(); ok {
		if err := user.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "User.first_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WalletAddress(); ok {
		if err := user.WalletAddressValidator(v); err != nil {
			return &ValidationError{Name: "wallet_address", err: fmt.Errorf(`ent: validator failed for field "User.wallet_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := user.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "User.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReferralCode(); ok {
		if err := user.ReferralCodeValidator(v); err != nil {
			return &ValidationError{Name: "referral_code", err: fmt.Errorf(`ent: validator failed for field "User.referral_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := user.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "User.status": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TgUserID(); ok {
		_spec.SetField(user.FieldTgUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTgUserID(); ok {
		_spec.AddField(user.FieldTgUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TgUsername(); ok {
		_spec.SetField(user.FieldTgUsername, field.TypeString, value)
	}
	if _u.mutation.TgUsernameCleared() {
		_spec.ClearField(user.FieldTgUsername, field.TypeString)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(user.FieldFirstName, field.TypeString, value)
	}
	if _u.mutation.FirstNameCleared() {
		_spec.ClearField(user.FieldFirstName, field.TypeString)
	}
	if value, ok := _u.mutation.WalletAddress(); ok {
		_spec.SetField(user.FieldWalletAddress, field.TypeString, value)
	}
	if _u.mutation.WalletAddressCleared() {
		_spec.ClearField(user.FieldWalletAddress, field.TypeString)
	}
	if value, ok := _u.mutation.BalanceTai(); ok {
		_spec.SetField(user.FieldBalanceTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceTai(); ok {
		_spec.AddField(user.FieldBalanceTai, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceUsdt(); ok {
		_spec.SetField(user.FieldBalanceUsdt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceUsdt(); ok {
		_spec.AddField(user.FieldBalanceUsdt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FrozenBalance(); ok {
		_spec.SetField(user.FieldFrozenBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrozenBalance(); ok {
		_spec.AddField(user.FieldFrozenBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReferralCode(); ok {
		_spec.SetField(user.FieldReferralCode, field.TypeString, value)
	}
	if _u.mutation.ReferralCodeCleared() {
		_spec.ClearField(user.FieldReferralCode, field.TypeString)
	}
	if value, ok := _u.mutation.ReferredBy(); ok {
		_spec.SetField(user.FieldReferredBy, field.TypeUUID, value)
	}
	if _u.mutation.ReferredByCleared() {
		_spec.ClearField(user.FieldReferredBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.InviteCount(); ok {
		_spec.SetField(user.FieldInviteCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInviteCount(); ok {
		_spec.AddField(user.FieldInviteCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalEarned(); ok {
		_spec.SetField(user.FieldTotalEarned, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalEarned(); ok {
		_spec.AddField(user.FieldTotalEarned, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(user.FieldGuildID, field.TypeUUID, value)
	}
	if _u.mutation.GuildIDCleared() {
		_spec.ClearField(user.FieldGuildID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(user.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PetsTable,
			Columns: []string{user.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPetsIDs(); len(nodes) > 0 && !_u.mutation.PetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PetsTable,
			Columns: []string{user.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PetsTable,
			Columns: []string{user.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
