// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BountiesColumns holds the columns for the "bounties" table.
	BountiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "publisher_id", Type: field.TypeString},
		{Name: "difficulty", Type: field.TypeEnum, Enums: []string{"D", "C", "B", "A", "S"}, Default: "D"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"open", "accepted", "submitted", "confirmed", "expired", "cancelled"}, Default: "open"},
		{Name: "acceptor_pet_id", Type: field.TypeString, Nullable: true},
		{Name: "reward_tai", Type: field.TypeFloat64, Default: 0},
		{Name: "submission", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
	}
	// BountiesTable holds the schema information for the "bounties" table.
	BountiesTable = &schema.Table{
		Name:       "bounties",
		Columns:    BountiesColumns,
		PrimaryKey: []*schema.Column{BountiesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "bounty_status",
				Unique:  false,
				Columns: []*schema.Column{BountiesColumns[5]},
			},
			{
				Name:    "bounty_publisher_id",
				Unique:  false,
				Columns: []*schema.Column{BountiesColumns[3]},
			},
		},
	}
	// GuildsColumns holds the columns for the "guilds" table.
	GuildsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 50},
		{Name: "leader_id", Type: field.TypeUUID},
		{Name: "level", Type: field.TypeInt, Default: 1},
		{Name: "reputation", Type: field.TypeInt64, Default: 0},
		{Name: "member_count", Type: field.TypeInt, Default: 1},
		{Name: "max_members", Type: field.TypeInt, Default: 50},
		{Name: "season_rank", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
	}
	// GuildsTable holds the schema information for the "guilds" table.
	GuildsTable = &schema.Table{
		Name:       "guilds",
		Columns:    GuildsColumns,
		PrimaryKey: []*schema.Column{GuildsColumns[0]},
	}
	// OrdersColumns holds the columns for the "orders" table.
	OrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "item_type", Type: field.TypeString, Size: 10},
		{Name: "item_id", Type: field.TypeUUID},
		{Name: "side", Type: field.TypeString, Size: 4},
		{Name: "price", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "currency", Type: field.TypeString, Size: 10, Default: "TAI"},
		{Name: "status", Type: field.TypeString, Size: 10, Default: "open"},
		{Name: "filled_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// OrdersTable holds the schema information for the "orders" table.
	OrdersTable = &schema.Table{
		Name:       "orders",
		Columns:    OrdersColumns,
		PrimaryKey: []*schema.Column{OrdersColumns[0]},
	}
	// PetsColumns holds the columns for the "pets" table.
	PetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 50, Default: "未命名"},
		{Name: "species", Type: field.TypeString, Size: 30},
		{Name: "quality", Type: field.TypeString, Size: 10, Default: "common"},
		{Name: "generation", Type: field.TypeInt, Default: 0},
		{Name: "growth_rate", Type: field.TypeFloat64, Default: 1, SchemaType: map[string]string{"postgres": "decimal(4,2)"}},
		{Name: "apt_hp", Type: field.TypeInt, Default: 20},
		{Name: "apt_atk", Type: field.TypeInt, Default: 20},
		{Name: "apt_def", Type: field.TypeInt, Default: 20},
		{Name: "apt_spd", Type: field.TypeInt, Default: 20},
		{Name: "apt_int", Type: field.TypeInt, Default: 20},
		{Name: "skill_slots", Type: field.TypeInt, Default: 2},
		{Name: "personality", Type: field.TypeString, Size: 20, Default: "balanced"},
		{Name: "level", Type: field.TypeInt, Default: 1},
		{Name: "exp", Type: field.TypeInt64, Default: 0},
		{Name: "mood", Type: field.TypeInt, Default: 80},
		{Name: "energy", Type: field.TypeInt, Default: 100},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "idle"},
		{Name: "tai_balance", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "image_url", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "is_on_chain", Type: field.TypeBool, Default: false},
		{Name: "chain_nft_address", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "chain_minted_at", Type: field.TypeTime, Nullable: true},
		{Name: "breed_cooldown_until", Type: field.TypeTime, Nullable: true},
		{Name: "total_earned_tai", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "total_spent_tai", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "total_tokens_used", Type: field.TypeInt64, Default: 0},
		{Name: "total_tasks_done", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "owner_id", Type: field.TypeUUID},
	}
	// PetsTable holds the schema information for the "pets" table.
	PetsTable = &schema.Table{
		Name:       "pets",
		Columns:    PetsColumns,
		PrimaryKey: []*schema.Column{PetsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pets_users_pets",
				Columns:    []*schema.Column{PetsColumns[30]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "pet_owner_id",
				Unique:  false,
				Columns: []*schema.Column{PetsColumns[30]},
			},
			{
				Name:    "pet_quality",
				Unique:  false,
				Columns: []*schema.Column{PetsColumns[3]},
			},
			{
				Name:    "pet_status",
				Unique:  false,
				Columns: []*schema.Column{PetsColumns[17]},
			},
			{
				Name:    "pet_species",
				Unique:  false,
				Columns: []*schema.Column{PetsColumns[2]},
			},
		},
	}
	// PetSkillsColumns holds the columns for the "pet_skills" table.
	PetSkillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "pet_id", Type: field.TypeUUID},
		{Name: "skill_id", Type: field.TypeUUID},
		{Name: "slot_index", Type: field.TypeInt, Default: 0},
		{Name: "source", Type: field.TypeString, Size: 20, Default: "purchase"},
		{Name: "equipped_at", Type: field.TypeTime},
		{Name: "pet_skills", Type: field.TypeUUID, Nullable: true},
	}
	// PetSkillsTable holds the schema information for the "pet_skills" table.
	PetSkillsTable = &schema.Table{
		Name:       "pet_skills",
		Columns:    PetSkillsColumns,
		PrimaryKey: []*schema.Column{PetSkillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pet_skills_pets_skills",
				Columns:    []*schema.Column{PetSkillsColumns[6]},
				RefColumns: []*schema.Column{PetsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SkillsColumns holds the columns for the "skills" table.
	SkillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 50},
		{Name: "name_en", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "quality", Type: field.TypeString, Size: 10, Default: "normal"},
		{Name: "category", Type: field.TypeString, Size: 30},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "weapon_visual", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "power_bonus", Type: field.TypeInt, Default: 0},
		{Name: "task_types", Type: field.TypeJSON, Nullable: true},
		{Name: "is_platform_exclusive", Type: field.TypeBool, Default: false},
		{Name: "total_supply", Type: field.TypeInt, Default: -1},
		{Name: "remaining", Type: field.TypeInt, Default: 0},
		{Name: "price_tai", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SkillsTable holds the schema information for the "skills" table.
	SkillsTable = &schema.Table{
		Name:       "skills",
		Columns:    SkillsColumns,
		PrimaryKey: []*schema.Column{SkillsColumns[0]},
	}
	// TradesColumns holds the columns for the "trades" table.
	TradesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "item_type", Type: field.TypeString, Size: 10},
		{Name: "item_id", Type: field.TypeUUID},
		{Name: "seller_id", Type: field.TypeUUID},
		{Name: "buyer_id", Type: field.TypeUUID},
		{Name: "price", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "currency", Type: field.TypeString, Size: 10, Default: "TAI"},
		{Name: "fee_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "fee_rate", Type: field.TypeFloat64, Default: 0.03, SchemaType: map[string]string{"postgres": "decimal(5,4)"}},
		{Name: "is_market_maker", Type: field.TypeBool, Default: false},
		{Name: "chain_tx_hash", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TradesTable holds the schema information for the "trades" table.
	TradesTable = &schema.Table{
		Name:       "trades",
		Columns:    TradesColumns,
		PrimaryKey: []*schema.Column{TradesColumns[0]},
	}
	// UsageLogsColumns holds the columns for the "usage_logs" table.
	UsageLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "pet_id", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "prompt_tokens", Type: field.TypeInt, Default: 0},
		{Name: "completion_tokens", Type: field.TypeInt, Default: 0},
		{Name: "tai_cost", Type: field.TypeFloat64, Default: 0},
		{Name: "bounty_id", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsageLogsTable holds the schema information for the "usage_logs" table.
	UsageLogsTable = &schema.Table{
		Name:       "usage_logs",
		Columns:    UsageLogsColumns,
		PrimaryKey: []*schema.Column{UsageLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "usagelog_pet_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[1]},
			},
			{
				Name:    "usagelog_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[7]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tg_user_id", Type: field.TypeInt64, Unique: true},
		{Name: "tg_username", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "first_name", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "wallet_address", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "balance_tai", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "balance_usdt", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "frozen_balance", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "role", Type: field.TypeString, Size: 20, Default: "user"},
		{Name: "referral_code", Type: field.TypeString, Unique: true, Nullable: true, Size: 20},
		{Name: "referred_by", Type: field.TypeUUID, Nullable: true},
		{Name: "invite_count", Type: field.TypeInt, Default: 0},
		{Name: "total_earned", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "guild_id", Type: field.TypeUUID, Nullable: true},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_tg_user_id",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
			{
				Name:    "user_referral_code",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[9]},
			},
			{
				Name:    "user_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[14]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BountiesTable,
		GuildsTable,
		OrdersTable,
		PetsTable,
		PetSkillsTable,
		SkillsTable,
		TradesTable,
		UsageLogsTable,
		UsersTable,
	}
)

func init() {
	GuildsTable.Annotation = &entsql.Annotation{
		Table: "guilds",
	}
	OrdersTable.Annotation = &entsql.Annotation{
		Table: "orders",
	}
	PetsTable.ForeignKeys[0].RefTable = UsersTable
	PetsTable.Annotation = &entsql.Annotation{
		Table: "pets",
	}
	PetSkillsTable.ForeignKeys[0].RefTable = PetsTable
	PetSkillsTable.Annotation = &entsql.Annotation{
		Table: "pet_skills",
	}
	SkillsTable.Annotation = &entsql.Annotation{
		Table: "skills",
	}
	TradesTable.Annotation = &entsql.Annotation{
		Table: "trades",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
}
