// Code generated by ent, DO NOT EDIT.

package skill

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldName, v))
}

// NameEn applies equality check predicate on the "name_en" field. It's identical to NameEnEQ.
func NameEn(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldNameEn, v))
}

// Quality applies equality check predicate on the "quality" field. It's identical to QualityEQ.
func Quality(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldQuality, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldCategory, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldDescription, v))
}

// WeaponVisual applies equality check predicate on the "weapon_visual" field. It's identical to WeaponVisualEQ.
func WeaponVisual(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldWeaponVisual, v))
}

// PowerBonus applies equality check predicate on the "power_bonus" field. It's identical to PowerBonusEQ.
func PowerBonus(v int) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldPowerBonus, v))
}

// IsPlatformExclusive applies equality check predicate on the "is_platform_exclusive" field. It's identical to IsPlatformExclusiveEQ.
func IsPlatformExclusive(v bool) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldIsPlatformExclusive, v))
}

// TotalSupply applies equality check predicate on the "total_supply" field. It's identical to TotalSupplyEQ.
func TotalSupply(v int) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldTotalSupply, v))
}

// Remaining applies equality check predicate on the "remaining" field. It's identical to RemainingEQ.
func Remaining(v int) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldRemaining, v))
}

// PriceTai applies equality check predicate on the "price_tai" field. It's identical to PriceTaiEQ.
func PriceTai(v float64) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldPriceTai, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldName, v))
}

// NameEnEQ applies the EQ predicate on the "name_en" field.
func NameEnEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldNameEn, v))
}

// NameEnNEQ applies the NEQ predicate on the "name_en" field.
func NameEnNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldNameEn, v))
}

// NameEnIn applies the In predicate on the "name_en" field.
func NameEnIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldNameEn, vs...))
}

// NameEnNotIn applies the NotIn predicate on the "name_en" field.
func NameEnNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldNameEn, vs...))
}

// NameEnGT applies the GT predicate on the "name_en" field.
func NameEnGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldNameEn, v))
}

// NameEnGTE applies the GTE predicate on the "name_en" field.
func NameEnGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldNameEn, v))
}

// NameEnLT applies the LT predicate on the "name_en" field.
func NameEnLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldNameEn, v))
}

// NameEnLTE applies the LTE predicate on the "name_en" field.
func NameEnLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldNameEn, v))
}

// NameEnContains applies the Contains predicate on the "name_en" field.
func NameEnContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldNameEn, v))
}

// NameEnHasPrefix applies the HasPrefix predicate on the "name_en" field.
func NameEnHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldNameEn, v))
}

// NameEnHasSuffix applies the HasSuffix predicate on the "name_en" field.
func NameEnHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldNameEn, v))
}

// NameEnIsNil applies the IsNil predicate on the "name_en" field.
func NameEnIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldNameEn))
}

// NameEnNotNil applies the NotNil predicate on the "name_en" field.
func NameEnNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldNameEn))
}

// NameEnEqualFold applies the EqualFold predicate on the "name_en" field.
func NameEnEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldNameEn, v))
}

// NameEnContainsFold applies the ContainsFold predicate on the "name_en" field.
func NameEnContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldNameEn, v))
}

// QualityEQ applies the EQ predicate on the "quality" field.
func QualityEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldQuality, v))
}

// QualityNEQ applies the NEQ predicate on the "quality" field.
func QualityNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldQuality, v))
}

// QualityIn applies the In predicate on the "quality" field.
func QualityIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldQuality, vs...))
}

// QualityNotIn applies the NotIn predicate on the "quality" field.
func QualityNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldQuality, vs...))
}

// QualityGT applies the GT predicate on the "quality" field.
func QualityGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldQuality, v))
}

// QualityGTE applies the GTE predicate on the "quality" field.
func QualityGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldQuality, v))
}

// QualityLT applies the LT predicate on the "quality" field.
func QualityLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldQuality, v))
}

// QualityLTE applies the LTE predicate on the "quality" field.
func QualityLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldQuality, v))
}

// QualityContains applies the Contains predicate on the "quality" field.
func QualityContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldQuality, v))
}

// QualityHasPrefix applies the HasPrefix predicate on the "quality" field.
func QualityHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldQuality, v))
}

// QualityHasSuffix applies the HasSuffix predicate on the "quality" field.
func QualityHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldQuality, v))
}

// QualityEqualFold applies the EqualFold predicate on the "quality" field.
func QualityEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldQuality, v))
}

// QualityContainsFold applies the ContainsFold predicate on the "quality" field.
func QualityContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldQuality, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldCategory, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldDescription, v))
}

// WeaponVisualEQ applies the EQ predicate on the "weapon_visual" field.
func WeaponVisualEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldWeaponVisual, v))
}

// WeaponVisualNEQ applies the NEQ predicate on the "weapon_visual" field.
func WeaponVisualNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldWeaponVisual, v))
}

// WeaponVisualIn applies the In predicate on the "weapon_visual" field.
func WeaponVisualIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldWeaponVisual, vs...))
}

// WeaponVisualNotIn applies the NotIn predicate on the "weapon_visual" field.
func WeaponVisualNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldWeaponVisual, vs...))
}

// WeaponVisualGT applies the GT predicate on the "weapon_visual" field.
func WeaponVisualGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldWeaponVisual, v))
}

// WeaponVisualGTE applies the GTE predicate on the "weapon_visual" field.
func WeaponVisualGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldWeaponVisual, v))
}

// WeaponVisualLT applies the LT predicate on the "weapon_visual" field.
func WeaponVisualLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldWeaponVisual, v))
}

// WeaponVisualLTE applies the LTE predicate on the "weapon_visual" field.
func WeaponVisualLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldWeaponVisual, v))
}

// WeaponVisualContains applies the Contains predicate on the "weapon_visual" field.
func WeaponVisualContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldWeaponVisual, v))
}

// WeaponVisualHasPrefix applies the HasPrefix predicate on the "weapon_visual" field.
func WeaponVisualHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldWeaponVisual, v))
}

// WeaponVisualHasSuffix applies the HasSuffix predicate on the "weapon_visual" field.
func WeaponVisualHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldWeaponVisual, v))
}

// WeaponVisualIsNil applies the IsNil predicate on the "weapon_visual" field.
func WeaponVisualIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldWeaponVisual))
}

// WeaponVisualNotNil applies the NotNil predicate on the "weapon_visual" field.
func WeaponVisualNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldWeaponVisual))
}

// WeaponVisualEqualFold applies the EqualFold predicate on the "weapon_visual" field.
func WeaponVisualEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldWeaponVisual, v))
}

// WeaponVisualContainsFold applies the ContainsFold predicate on the "weapon_visual" field.
func WeaponVisualContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldWeaponVisual, v))
}

// PowerBonusEQ applies the EQ predicate on the "power_bonus" field.
func PowerBonusEQ(v int) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldPowerBonus, v))
}

// PowerBonusNEQ applies the NEQ predicate on the "power_bonus" field.
func PowerBonusNEQ(v int) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldPowerBonus, v))
}

// PowerBonusIn applies the In predicate on the "power_bonus" field.
func PowerBonusIn(vs ...int) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldPowerBonus, vs...))
}

// PowerBonusNotIn applies the NotIn predicate on the "power_bonus" field.
func PowerBonusNotIn(vs ...int) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldPowerBonus, vs...))
}

// PowerBonusGT applies the GT predicate on the "power_bonus" field.
func PowerBonusGT(v int) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldPowerBonus, v))
}

// PowerBonusGTE applies the GTE predicate on the "power_bonus" field.
func PowerBonusGTE(v int) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldPowerBonus, v))
}

// PowerBonusLT applies the LT predicate on the "power_bonus" field.
func PowerBonusLT(v int) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldPowerBonus, v))
}

// PowerBonusLTE applies the LTE predicate on the "power_bonus" field.
func PowerBonusLTE(v int) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldPowerBonus, v))
}

// TaskTypesIsNil applies the IsNil predicate on the "task_types" field.
func TaskTypesIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldTaskTypes))
}

// TaskTypesNotNil applies the NotNil predicate on the "task_types" field.
func TaskTypesNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldTaskTypes))
}

// IsPlatformExclusiveEQ applies the EQ predicate on the "is_platform_exclusive" field.
func IsPlatformExclusiveEQ(v bool) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldIsPlatformExclusive, v))
}

// IsPlatformExclusiveNEQ applies the NEQ predicate on the "is_platform_exclusive" field.
func IsPlatformExclusiveNEQ(v bool) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldIsPlatformExclusive, v))
}

// TotalSupplyEQ applies the EQ predicate on the "total_supply" field.
func TotalSupplyEQ(v int) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldTotalSupply, v))
}

// TotalSupplyNEQ applies the NEQ predicate on the "total_supply" field.
func TotalSupplyNEQ(v int) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldTotalSupply, v))
}

// TotalSupplyIn applies the In predicate on the "total_supply" field.
func TotalSupplyIn(vs ...int) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldTotalSupply, vs...))
}

// TotalSupplyNotIn applies the NotIn predicate on the "total_supply" field.
func TotalSupplyNotIn(vs ...int) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldTotalSupply, vs...))
}

// TotalSupplyGT applies the GT predicate on the "total_supply" field.
func TotalSupplyGT(v int) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldTotalSupply, v))
}

// TotalSupplyGTE applies the GTE predicate on the "total_supply" field.
func TotalSupplyGTE(v int) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldTotalSupply, v))
}

// TotalSupplyLT applies the LT predicate on the "total_supply" field.
func TotalSupplyLT(v int) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldTotalSupply, v))
}

// TotalSupplyLTE applies the LTE predicate on the "total_supply" field.
func TotalSupplyLTE(v int) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldTotalSupply, v))
}

// RemainingEQ applies the EQ predicate on the "remaining" field.
func RemainingEQ(v int) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldRemaining, v))
}

// RemainingNEQ applies the NEQ predicate on the "remaining" field.
func RemainingNEQ(v int) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldRemaining, v))
}

// RemainingIn applies the In predicate on the "remaining" field.
func RemainingIn(vs ...int) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldRemaining, vs...))
}

// RemainingNotIn applies the NotIn predicate on the "remaining" field.
func RemainingNotIn(vs ...int) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldRemaining, vs...))
}

// RemainingGT applies the GT predicate on the "remaining" field.
func RemainingGT(v int) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldRemaining, v))
}

// RemainingGTE applies the GTE predicate on the "remaining" field.
func RemainingGTE(v int) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldRemaining, v))
}

// RemainingLT applies the LT predicate on the "remaining" field.
func RemainingLT(v int) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldRemaining, v))
}

// RemainingLTE applies the LTE predicate on the "remaining" field.
func RemainingLTE(v int) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldRemaining, v))
}

// PriceTaiEQ applies the EQ predicate on the "price_tai" field.
func PriceTaiEQ(v float64) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldPriceTai, v))
}

// PriceTaiNEQ applies the NEQ predicate on the "price_tai" field.
func PriceTaiNEQ(v float64) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldPriceTai, v))
}

// PriceTaiIn applies the In predicate on the "price_tai" field.
func PriceTaiIn(vs ...float64) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldPriceTai, vs...))
}

// PriceTaiNotIn applies the NotIn predicate on the "price_tai" field.
func PriceTaiNotIn(vs ...float64) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldPriceTai, vs...))
}

// PriceTaiGT applies the GT predicate on the "price_tai" field.
func PriceTaiGT(v float64) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldPriceTai, v))
}

// PriceTaiGTE applies the GTE predicate on the "price_tai" field.
func PriceTaiGTE(v float64) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldPriceTai, v))
}

// PriceTaiLT applies the LT predicate on the "price_tai" field.
func PriceTaiLT(v float64) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldPriceTai, v))
}

// PriceTaiLTE applies the LTE predicate on the "price_tai" field.
func PriceTaiLTE(v float64) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldPriceTai, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Skill) predicate.Skill {
	return predicate.Skill(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Skill) predicate.Skill {
	return predicate.Skill(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Skill) predicate.Skill {
	return predicate.Skill(sql.NotPredicates(p))
}
