// Code generated by ent, DO NOT EDIT.

package bounty

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tii-mom/tai-protocol/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Bounty {
	return predicate.Bounty(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Bounty {
	return predicate.Bounty(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Bounty {
	return predicate.Bounty(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Bounty {
	return predicate.Bounty(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Bounty {
	return predicate.Bounty(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Bounty {
	return predicate.Bounty(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Bounty {
	return predicate.Bounty(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldDescription, v))
}

// PublisherID applies equality check predicate on the "publisher_id" field. It's identical to PublisherIDEQ.
func PublisherID(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldPublisherID, v))
}

// AcceptorPetID applies equality check predicate on the "acceptor_pet_id" field. It's identical to AcceptorPetIDEQ.
func AcceptorPetID(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldAcceptorPetID, v))
}

// RewardTai applies equality check predicate on the "reward_tai" field. It's identical to RewardTaiEQ.
func RewardTai(v float64) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldRewardTai, v))
}

// Submission applies equality check predicate on the "submission" field. It's identical to SubmissionEQ.
func Submission(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldSubmission, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldCreatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldExpiresAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldCompletedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Bounty {
	return predicate.Bounty(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Bounty {
	return predicate.Bounty(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Bounty {
	return predicate.Bounty(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Bounty {
	return predicate.Bounty(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Bounty {
	return predicate.Bounty(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Bounty {
	return predicate.Bounty(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldContainsFold(FieldDescription, v))
}

// PublisherIDEQ applies the EQ predicate on the "publisher_id" field.
func PublisherIDEQ(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldPublisherID, v))
}

// PublisherIDNEQ applies the NEQ predicate on the "publisher_id" field.
func PublisherIDNEQ(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldNEQ(FieldPublisherID, v))
}

// PublisherIDIn applies the In predicate on the "publisher_id" field.
func PublisherIDIn(vs ...string) predicate.Bounty {
	return predicate.Bounty(sql.FieldIn(FieldPublisherID, vs...))
}

// PublisherIDNotIn applies the NotIn predicate on the "publisher_id" field.
func PublisherIDNotIn(vs ...string) predicate.Bounty {
	return predicate.Bounty(sql.FieldNotIn(FieldPublisherID, vs...))
}

// PublisherIDGT applies the GT predicate on the "publisher_id" field.
func PublisherIDGT(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldGT(FieldPublisherID, v))
}

// PublisherIDGTE applies the GTE predicate on the "publisher_id" field.
func PublisherIDGTE(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldGTE(FieldPublisherID, v))
}

// PublisherIDLT applies the LT predicate on the "publisher_id" field.
func PublisherIDLT(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldLT(FieldPublisherID, v))
}

// PublisherIDLTE applies the LTE predicate on the "publisher_id" field.
func PublisherIDLTE(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldLTE(FieldPublisherID, v))
}

// PublisherIDContains applies the Contains predicate on the "publisher_id" field.
func PublisherIDContains(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldContains(FieldPublisherID, v))
}

// PublisherIDHasPrefix applies the HasPrefix predicate on the "publisher_id" field.
func PublisherIDHasPrefix(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldHasPrefix(FieldPublisherID, v))
}

// PublisherIDHasSuffix applies the HasSuffix predicate on the "publisher_id" field.
func PublisherIDHasSuffix(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldHasSuffix(FieldPublisherID, v))
}

// PublisherIDEqualFold applies the EqualFold predicate on the "publisher_id" field.
func PublisherIDEqualFold(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEqualFold(FieldPublisherID, v))
}

// PublisherIDContainsFold applies the ContainsFold predicate on the "publisher_id" field.
func PublisherIDContainsFold(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldContainsFold(FieldPublisherID, v))
}

// DifficultyEQ applies the EQ predicate on the "difficulty" field.
func DifficultyEQ(v Difficulty) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldDifficulty, v))
}

// DifficultyNEQ applies the NEQ predicate on the "difficulty" field.
func DifficultyNEQ(v Difficulty) predicate.Bounty {
	return predicate.Bounty(sql.FieldNEQ(FieldDifficulty, v))
}

// DifficultyIn applies the In predicate on the "difficulty" field.
func DifficultyIn(vs ...Difficulty) predicate.Bounty {
	return predicate.Bounty(sql.FieldIn(FieldDifficulty, vs...))
}

// DifficultyNotIn applies the NotIn predicate on the "difficulty" field.
func DifficultyNotIn(vs ...Difficulty) predicate.Bounty {
	return predicate.Bounty(sql.FieldNotIn(FieldDifficulty, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Bounty {
	return predicate.Bounty(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Bounty {
	return predicate.Bounty(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Bounty {
	return predicate.Bounty(sql.FieldNotIn(FieldStatus, vs...))
}

// AcceptorPetIDEQ applies the EQ predicate on the "acceptor_pet_id" field.
func AcceptorPetIDEQ(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldAcceptorPetID, v))
}

// AcceptorPetIDNEQ applies the NEQ predicate on the "acceptor_pet_id" field.
func AcceptorPetIDNEQ(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldNEQ(FieldAcceptorPetID, v))
}

// AcceptorPetIDIn applies the In predicate on the "acceptor_pet_id" field.
func AcceptorPetIDIn(vs ...string) predicate.Bounty {
	return predicate.Bounty(sql.FieldIn(FieldAcceptorPetID, vs...))
}

// AcceptorPetIDNotIn applies the NotIn predicate on the "acceptor_pet_id" field.
func AcceptorPetIDNotIn(vs ...string) predicate.Bounty {
	return predicate.Bounty(sql.FieldNotIn(FieldAcceptorPetID, vs...))
}

// AcceptorPetIDGT applies the GT predicate on the "acceptor_pet_id" field.
func AcceptorPetIDGT(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldGT(FieldAcceptorPetID, v))
}

// AcceptorPetIDGTE applies the GTE predicate on the "acceptor_pet_id" field.
func AcceptorPetIDGTE(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldGTE(FieldAcceptorPetID, v))
}

// AcceptorPetIDLT applies the LT predicate on the "acceptor_pet_id" field.
func AcceptorPetIDLT(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldLT(FieldAcceptorPetID, v))
}

// AcceptorPetIDLTE applies the LTE predicate on the "acceptor_pet_id" field.
func AcceptorPetIDLTE(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldLTE(FieldAcceptorPetID, v))
}

// AcceptorPetIDContains applies the Contains predicate on the "acceptor_pet_id" field.
func AcceptorPetIDContains(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldContains(FieldAcceptorPetID, v))
}

// AcceptorPetIDHasPrefix applies the HasPrefix predicate on the "acceptor_pet_id" field.
func AcceptorPetIDHasPrefix(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldHasPrefix(FieldAcceptorPetID, v))
}

// AcceptorPetIDHasSuffix applies the HasSuffix predicate on the "acceptor_pet_id" field.
func AcceptorPetIDHasSuffix(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldHasSuffix(FieldAcceptorPetID, v))
}

// AcceptorPetIDIsNil applies the IsNil predicate on the "acceptor_pet_id" field.
func AcceptorPetIDIsNil() predicate.Bounty {
	return predicate.Bounty(sql.FieldIsNull(FieldAcceptorPetID))
}

// AcceptorPetIDNotNil applies the NotNil predicate on the "acceptor_pet_id" field.
func AcceptorPetIDNotNil() predicate.Bounty {
	return predicate.Bounty(sql.FieldNotNull(FieldAcceptorPetID))
}

// AcceptorPetIDEqualFold applies the EqualFold predicate on the "acceptor_pet_id" field.
func AcceptorPetIDEqualFold(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEqualFold(FieldAcceptorPetID, v))
}

// AcceptorPetIDContainsFold applies the ContainsFold predicate on the "acceptor_pet_id" field.
func AcceptorPetIDContainsFold(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldContainsFold(FieldAcceptorPetID, v))
}

// RewardTaiEQ applies the EQ predicate on the "reward_tai" field.
func RewardTaiEQ(v float64) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldRewardTai, v))
}

// RewardTaiNEQ applies the NEQ predicate on the "reward_tai" field.
func RewardTaiNEQ(v float64) predicate.Bounty {
	return predicate.Bounty(sql.FieldNEQ(FieldRewardTai, v))
}

// RewardTaiIn applies the In predicate on the "reward_tai" field.
func RewardTaiIn(vs ...float64) predicate.Bounty {
	return predicate.Bounty(sql.FieldIn(FieldRewardTai, vs...))
}

// RewardTaiNotIn applies the NotIn predicate on the "reward_tai" field.
func RewardTaiNotIn(vs ...float64) predicate.Bounty {
	return predicate.Bounty(sql.FieldNotIn(FieldRewardTai, vs...))
}

// RewardTaiGT applies the GT predicate on the "reward_tai" field.
func RewardTaiGT(v float64) predicate.Bounty {
	return predicate.Bounty(sql.FieldGT(FieldRewardTai, v))
}

// RewardTaiGTE applies the GTE predicate on the "reward_tai" field.
func RewardTaiGTE(v float64) predicate.Bounty {
	return predicate.Bounty(sql.FieldGTE(FieldRewardTai, v))
}

// RewardTaiLT applies the LT predicate on the "reward_tai" field.
func RewardTaiLT(v float64) predicate.Bounty {
	return predicate.Bounty(sql.FieldLT(FieldRewardTai, v))
}

// RewardTaiLTE applies the LTE predicate on the "reward_tai" field.
func RewardTaiLTE(v float64) predicate.Bounty {
	return predicate.Bounty(sql.FieldLTE(FieldRewardTai, v))
}

// SubmissionEQ applies the EQ predicate on the "submission" field.
func SubmissionEQ(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldSubmission, v))
}

// SubmissionNEQ applies the NEQ predicate on the "submission" field.
func SubmissionNEQ(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldNEQ(FieldSubmission, v))
}

// SubmissionIn applies the In predicate on the "submission" field.
func SubmissionIn(vs ...string) predicate.Bounty {
	return predicate.Bounty(sql.FieldIn(FieldSubmission, vs...))
}

// SubmissionNotIn applies the NotIn predicate on the "submission" field.
func SubmissionNotIn(vs ...string) predicate.Bounty {
	return predicate.Bounty(sql.FieldNotIn(FieldSubmission, vs...))
}

// SubmissionGT applies the GT predicate on the "submission" field.
func SubmissionGT(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldGT(FieldSubmission, v))
}

// SubmissionGTE applies the GTE predicate on the "submission" field.
func SubmissionGTE(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldGTE(FieldSubmission, v))
}

// SubmissionLT applies the LT predicate on the "submission" field.
func SubmissionLT(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldLT(FieldSubmission, v))
}

// SubmissionLTE applies the LTE predicate on the "submission" field.
func SubmissionLTE(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldLTE(FieldSubmission, v))
}

// SubmissionContains applies the Contains predicate on the "submission" field.
func SubmissionContains(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldContains(FieldSubmission, v))
}

// SubmissionHasPrefix applies the HasPrefix predicate on the "submission" field.
func SubmissionHasPrefix(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldHasPrefix(FieldSubmission, v))
}

// SubmissionHasSuffix applies the HasSuffix predicate on the "submission" field.
func SubmissionHasSuffix(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldHasSuffix(FieldSubmission, v))
}

// SubmissionIsNil applies the IsNil predicate on the "submission" field.
func SubmissionIsNil() predicate.Bounty {
	return predicate.Bounty(sql.FieldIsNull(FieldSubmission))
}

// SubmissionNotNil applies the NotNil predicate on the "submission" field.
func SubmissionNotNil() predicate.Bounty {
	return predicate.Bounty(sql.FieldNotNull(FieldSubmission))
}

// SubmissionEqualFold applies the EqualFold predicate on the "submission" field.
func SubmissionEqualFold(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldEqualFold(FieldSubmission, v))
}

// SubmissionContainsFold applies the ContainsFold predicate on the "submission" field.
func SubmissionContainsFold(v string) predicate.Bounty {
	return predicate.Bounty(sql.FieldContainsFold(FieldSubmission, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldLTE(FieldCreatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.Bounty {
	return predicate.Bounty(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.Bounty {
	return predicate.Bounty(sql.FieldNotNull(FieldExpiresAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.Bounty {
	return predicate.Bounty(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.Bounty {
	return predicate.Bounty(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.Bounty {
	return predicate.Bounty(sql.FieldNotNull(FieldCompletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bounty) predicate.Bounty {
	return predicate.Bounty(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bounty) predicate.Bounty {
	return predicate.Bounty(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bounty) predicate.Bounty {
	return predicate.Bounty(sql.NotPredicates(p))
}
